export const BLOG_LT = [
{
  slug: "all-on-4-ar-all-on-6-kas-jums-tinka",
  title: "All-on-4 ar All-on-6: Kas jums tinka?",
  description: "Ir All-on-4, ir All-on-6 suteikia visą fiksuotą dantų lanką ant implantų. Štai tikras skirtumas tarp jų ir kaip odontologas nusprendžia, kas tinka jūsų žandikauliui.",
  date: "2026-09-01",
  relatedTreatment: "all-on-4-5-6-implantai-istanbul",
  body: [
    { h: "Trumpas atsakymas" },
    { p: "All-on-4 ir All-on-6 naudoja tą pačią pagrindinę idėją — visą fiksuotų dantų lanką, palaikomą nedidelio skaičiaus implantų, įdiegtų žandikaulyje. Skaičius pavadinime tiesiog nurodo, kiek implantų palaiko tą lanką. Keturių dažnai pakanka; šeši naudojami, kai jūsų atveju naudinga papildoma parama." },
    { h: "Kodėl jums gali prireikti šešių vietoj keturių?" },
    { p: "Sprendimas dažniausiai priklauso nuo kaulo. All-on-4 buvo specialiai sukurtas dirbti su kaulu, kurį dauguma pacientų jau turi, naudojant du pakreiptus implantus žandikaulio gale, kad būtų išvengta kaulo netekimo sričių." },
    { h: "Ar papildomas implantas keičia rezultatą, kurį jaučiate kasdien?" },
    { p: "Ne. Nesvarbu, ar jūsų naujas lankas remiasi keturiais ar šešiais implantais, baigtas tiltas atrodo ir jaučiasi vienodai jūsų burnoje." },
    { h: "Kaip sprendimas iš tikrųjų priimamas" },
    { p: "Tinkamas 3D skenavimas (paprastai CBCT) parodo jūsų odontologui tiksliai, kiek kaulo yra prieinama kiekvienoje jūsų žandikaulio srityje." },
    { h: "Trumpai tariant" },
    { p: "All-on-4 yra standartinis, gerai išbandytas pradinis taškas daugumai pacientų. All-on-6 egzistuoja žmonėms, kurių kaulo tankis, sukandimo jėga ar kaulo netekimo modelis tikrai reikalauja papildomos paramos." },
  ]
},
{
  slug: "cirkonis-ar-emax-tinkamos-medziagos-pasirinkimas",
  title: "Cirkonis ar E-max: Tinkamos medžiagos pasirinkimas jūsų šypsenai",
  description: "Cirkonis ir E-max yra dvi medžiagos, esančios daugumos šiuolaikinių karūnėlių ir fasečių pagrindu.",
  date: "2026-09-01",
  relatedTreatment: "monolitinis-cirkonis-karunieles-istanbul",
  body: [
    { h: "Du skirtingi uždaviniai, dvi skirtingos medžiagos" },
    { p: "Cirkonis ir E-max (ličio disilikatas) yra abi aukštos kokybės keramikos, naudojamos šiuolaikinėje restauracinėje ir kosmetinėje odontologijoje, tačiau jos nėra keičiamos." },
    { h: "Kur laimi cirkonis" },
    { p: "Cirkonis yra itin tvirtas ir atsparus skilimui ar lūžimui net ant apkrovą laikančių galinių dantų. Monolitinis cirkonis pašalina pagrindinę senesnių cirkonio karūnėlių silpnybę." },
    { h: "Kur laimi E-max" },
    { p: "E-max turi stiklišką permatomumą, kuris labiau imituoja natūralų danties emalį. Priekiniams dantims tai daro E-max dažnesniu pasirinkimu fasetėms." },
    { h: "Tad kas iš tikrųjų jums tinka?" },
    { p: "Praktikoje daugelis pacientų gauna mišinį: E-max priekyje geriausiam kosmetiniam rezultatui, cirkonis toliau gale tvirtumui." },
  ]
},
{
  slug: "kiek-dienu-reikia-stambule-dantu-gydymui",
  title: "Kiek dienų reikia Stambule dantų gydymui?",
  description: "Atsakymas visiškai priklauso nuo gydymo, kurį gaunate.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Nėra vieno atsakymo — priklauso nuo gydymo" },
    { p: "Tai vienas iš dažniausiai užduodamų klausimų kiekvienam, planuojančiam dantų gydymą užsienyje, o sąžiningas atsakymas: labai priklauso nuo to, ką darote." },
    { h: "Vieno apsilankymo gydymai (3–7 dienos)" },
    { p: "Fasetės, karūnėlės, dantų balinimas ir Hollywood Smile pertvarkymai, neapimantys implantų, paprastai baigiami per vieną kelionę." },
    { h: "Implantų gydymai (du apsilankymai, per kelis mėnesius)" },
    { p: "Dantų implantams reikia laiko susilieti su žandikaulio kaulu (procesas vadinamas osteointegracija), prieš pritvirtinant nuolatinę karūnėlę ar tiltą." },
    { h: "All-on-4 / All-on-6 konkrečiai" },
    { p: "Viso lanko implantų atvejai seka tuo pačiu dviejų apsilankymų modeliu, tačiau daugelis pacientų išvyksta iš pirmojo apsilankymo jau su laikinu fiksuotu tiltu." },
    { h: "Planavimas aplink tai" },
    { p: "Jei derinate gydymus, papildomas kosmetinis darbas paprastai planuojamas aplink implantų grafiką." },
  ]
},
{
  slug: "fasetes-ar-karunieles-koks-skirtumas",
  title: "Fasetės ar karūnėlės: Koks skirtumas ir ko jums reikia?",
  description: "Fasetės ir karūnėlės sprendžia skirtingas problemas.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Pagrindinis skirtumas" },
    { p: "Fasetė dengia tik priekinę, matomą danties paviršių. Karūnėlė dengia visą dantį, iš visų pusių." },
    { h: "Kada fasetė yra tinkamas įrankis" },
    { p: "Fasetės skirtos dantims, kurie yra kosmetiškai pažeisti, bet struktūriškai sveiki." },
    { h: "Kada karūnėlė yra tinkamas įrankis" },
    { p: "Karūnėlės skirtos struktūriškai susilpnėjusiems dantims — didelei plombai, kuri nepavyko, ar dantiui po šaknies kanalo gydymo." },
    { h: "Ar jos gali būti maišomos vienoje šypsenoje?" },
    { p: "Taip, ir tai įprasta. Pilnas šypsenos pertvarkymas dažnai derina abu, pasirinktus dantis po danties." },
    { h: "Ką tai reiškia jūsų konsultacijai" },
    { p: "Jei klinika siūlo karūnėles ant dantų, rodančių tik kosmetines problemas be struktūrinio pažeidimo, verta paklausti kodėl." },
  ]
},
{
  slug: "kas-atsitinka-jei-neturite-pakankamai-kaulo-implantams",
  title: "Kas atsitinka, jei neturite pakankamai kaulo implantams?",
  description: "Kaulo netekimas automatiškai neatmeta implantų.",
  date: "2026-09-01",
  relatedTreatment: "sinuso-pakelimas-istanbul",
  body: [
    { h: "Kaulo netekimas yra dažnas, o ne diskvalifikuojantis" },
    { p: "Po to, kai dantis trūksta kurį laiką, žandikaulio kaulas toje srityje natūraliai sumažėja." },
    { h: "Kaip odontologas iš tikrųjų patikrina" },
    { p: "3D skenavimas (CBCT) parodo tikslų prieinamo kaulo aukštį ir plotį implanto vietoje." },
    { h: "1 variantas — Pasvirasis implanto įdiegimas" },
    { p: "Tokie metodai kaip All-on-4 buvo iš dalies sukurti būtent aplink šią problemą." },
    { h: "2 variantas — Kaulo priauga" },
    { p: "Kai tikrai nepakanka kaulo tūrio net su pasviru įdiegimu, kaulo priauga prideda medžiagos." },
    { h: "3 variantas — Sinuso pakėlimas" },
    { p: "Viršutinis galinis žandikaulis yra arti sinuso ertmių." },
    { h: "Išvada" },
    { p: "„Neturiu pakankamai kaulo“ retai yra pokalbio pabaiga — tai šiek tiek kitokio gydymo plano pradžia." },
  ]
},
{
  slug: "priezziura-po-implantacijos-kas-atsitinka-grizus-namo",
  title: "Priežiūra po implantacijos: Kas atsitinka grįžus namo?",
  description: "Implantų gavimas užsienyje nereiškia, kad esate vieni po nusileidimo namuose.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Priežiūra po gydymo neturėtų baigtis oro uoste" },
    { p: "Įprastas (ir pagrįstas) rūpestis dėl implantų gavimo užsienyje yra tai, kas atsitinka, jei kažkas atrodo netinkamai grįžus." },
    { h: "Kaip jaučiasi normalus gijimas" },
    { p: "Lengvas skausmas, tam tikras patinimas ir jautrumas dienomis iš karto po implanto operacijos yra normalūs ir tikėtini." },
    { h: "Ką apima tikras priežiūros po gydymo planas" },
    { p: "Rašytinė garantija, nurodanti, kas dengiama ir kiek laiko, tiesioginio kontakto su jūsų odontologu būdas." },
    { h: "Ką paklausti prieš įsipareigojant" },
    { p: "Prieš rezervuojant protinga tiesiogiai paklausti: kas atsitinka, jei implantas neprigyja." },
    { h: "Realistinis vaizdas" },
    { p: "Dauguma implantų gijimo vyksta be įvykių." },
  ]
},
{
  slug: "ar-emax-fasetems-reikia-dantu-slifavimo",
  title: "Ar E-max fasetėms reikia dantų šlifavimo?",
  description: "Viena iš dažniausių problemų dėl fasečių.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Sąžiningas atsakymas: priklauso nuo jūsų pradinio taško" },
    { p: "E-max fasetės dažnai apibūdinamos kaip „minimalus paruošimas“, ir tam yra gera priežastis." },
    { h: "Kada reikia labai mažo ar jokio sumažinimo" },
    { p: "Jei jūsų dantys jau pakankamai gerai sulygiuoti, plona E-max fasetė dažnai gali būti priklijuota su mažai ar visai be emalio pašalinimo." },
    { h: "Kada iš tikrųjų reikia daugiau paruošimo" },
    { p: "Jei dantis yra žymiai nesulygiuotas, paprastai reikia tam tikro emalio sumažinimo." },
    { h: "Kodėl tai turėtų būti nuspręsta prieš kelionę, o ne po jos" },
    { p: "Skaitmeninio šypsenos dizaino skenavimas iš tikrųjų atsako į šį klausimą jūsų konkretiems dantims." },
    { h: "Ką paklausti" },
    { p: "Visiškai protinga tiesiogiai paklausti: „kiek mano natūralaus danties reikės pašalinti šiam dizainui?“" },
  ]
},
{
  slug: "kiek-laiko-uztrunka-cirkonio-karuneles-gamyba",
  title: "Kiek laiko užtrunka cirkonio karūnėlės gamyba?",
  description: "Nuo pirmojo jūsų apsilankymo iki baigtos karūnėlės.",
  date: "2026-09-02",
  relatedTreatment: "monolitinis-cirkonis-karunieles-istanbul",
  body: [
    { h: "Trumpa versija" },
    { p: "Viena cirkonio karūnėlė, kai dantis paruoštas ir nuskenuotas, paprastai užtrunka kelias dienas projektavimui, frezavimui ir apdailai." },
    { h: "Kas iš tikrųjų vyksta per šį laiką" },
    { p: "Kai jūsų dantis paruoštas ir skaitmeniniu būdu nuskenuotas, failas siunčiamas frezavimui." },
    { h: "Kodėl vidinis frezavimas svarbus jūsų tvarkaraščiui" },
    { p: "Klinikos su savo frezavimo laboratorija gali užbaigti karūnėlę per dieną ar dvi." },
    { h: "Kada tai užtrunka ilgiau" },
    { p: "Kelios karūnėlės ar pilnas šypsenos pertvarkymas natūraliai užima daugiau jūsų vizito laiko." },
  ]
},
{
  slug: "ka-is-tikruju-apima-sypsenos-dizaino-gydymas",
  title: "Ką iš tikrųjų apima šypsenos dizaino gydymas?",
  description: "„Šypsenos dizainas“ ir „Skaitmeninis šypsenos dizainas“ naudojami laisvai.",
  date: "2026-09-02",
  relatedTreatment: "skaitmeninis-sypsenos-dizainas-istanbul",
  body: [
    { h: "Tai planavimo procesas, o ne viena procedūra" },
    { p: "Skaitmeninis šypsenos dizainas savaime nėra gydymas — tai planavimo etapas." },
    { h: "1 žingsnis — Jūsų veido, o ne tik dantų, analizė" },
    { p: "Fotografuojami ir kartais filmuojami jūsų šypsena, lūpų linija ir veido proporcijos." },
    { h: "2 žingsnis — 3D skenavimas ir skaitmeninis maketas" },
    { p: "Intraoralinis skenavimas sukuria 3D jūsų dantų modelį." },
    { h: "3 žingsnis — Nustatymas, kokio gydymo iš tikrųjų reikia" },
    { p: "Iš to plano jūsų odontologas nustato gydymo derinį." },
    { h: "4 žingsnis — Fizinis maketas burnoje" },
    { p: "Prieš prasidedant nuolatiniam darbui, daugelis klinikų gali parodyti laikiną dizaino versiją tiesiai ant jūsų dantų." },
    { h: "Kodėl tai svarbu" },
    { p: "Jei klinika siūlo „šypsenos dizainą“ be skaitmeninio skenavimo ar maketo žingsnio, greičiausiai gaunate standartinį kosmetinį paketą." },
  ]
},
{
  slug: "hollywood-smile-prieš-fasetes-tikrasis-skirtumas",
  title: "Hollywood Smile prieš fasetes: Koks tikrasis skirtumas?",
  description: "„Hollywood Smile“ nėra atskira medžiaga ar procedūra nuo fasečių.",
  date: "2026-09-02",
  relatedTreatment: "hollywood-smile-istanbul",
  body: [
    { h: "Hollywood Smile yra rezultatas, o ne medžiaga" },
    { p: "„Fasetės“ apibūdina konkretų restauravimą. „Hollywood Smile“ apibūdina platesnį kosmetinį tikslą." },
    { h: "Taigi Hollywood Smile gali naudoti fasetes, o gal ir ne" },
    { p: "Priklausomai nuo jūsų dantų būklės, Hollywood Smile rezultatas gali būti pasiektas visiškai fasetėmis, visiškai karūnėlėmis." },
    { h: "Kodėl šis skirtumas svarbus lyginant pasiūlymus" },
    { p: "Jei viena klinika duoda jums pasiūlymą už „fasetes“, o kita už „Hollywood Smile paketą“, jos gali nelyginti to paties dalyko." },
    { h: "Kas iš tikrųjų lemia, ar fasetės yra teisingas pasirinkimas" },
    { p: "Tai grįžta prie konkretaus danties būklės." },
  ]
},
{
  slug: "invisalign-prieš-tradicinius-breketus-ka-pasirinkti",
  title: "Invisalign prieš tradicinius breketus: Ką pasirinkti?",
  description: "Skaidrūs breketai ir metaliniai breketai abu tiesina dantis.",
  date: "2026-09-02",
  relatedTreatment: "invisalign-skaidrus-breketai-istanbul",
  body: [
    { h: "Abu veikia — klausimas yra tinkamumas, ne pranašumas" },
    { p: "Skaidrūs breketai ir tradiciniai breketai abu juda dantis naudojant kontroliuojamą, laipsnišką slėgį." },
    { h: "Kur gerai veikia skaidrūs breketai" },
    { p: "Lengvas iki vidutinio susikimšimas, tarpai ar paprastos sąkandžio problemos paprastai gerai tinka kapoms." },
    { h: "Kur tradiciniai breketai vis dar geresnis įrankis" },
    { p: "Sudėtingesni judesiai dažnai geriau sprendžiami fiksuotais breketais." },
    { h: "Disciplinos veiksnys" },
    { p: "Kapos veikia tik jei dėvimos kaip paskirta, paprastai 20–22 valandas per dieną." },
    { h: "Kaip sprendimas iš tikrųjų priimamas" },
    { p: "3D skenavimas ir sąkandžio įvertinimas parodys, kokių judesių iš tikrųjų reikia jūsų atveju." },
  ]
},
{
  slug: "dantu-tiltas-ar-implantas-kaip-pasirinkti",
  title: "Dantų tiltas ar implantas: Kaip pasirinkti",
  description: "Abu pakeičia trūkstamą dantį, tačiau veikia labai skirtingai.",
  date: "2026-09-02",
  relatedTreatment: "dantu-tiltas-istanbul",
  body: [
    { h: "Pagrindinis skirtumas" },
    { p: "Implantas tiesiogiai pakeičia trūkstamą danties šaknį. Tiltas pakeičia tik matomą dantį." },
    { h: "Kodėl tiltas dažnai greitesnis ir pigesnis" },
    { p: "Tiltui nereikia operacijos ar gijimo laikotarpio kaulo integracijai." },
    { h: "Kodėl implantas dažnai stipresnis ilgalaikis pasirinkimas" },
    { p: "Kadangi implantas nepriklauso nuo gretimų dantų, jam nereikia paruošti kitaip sveikų dantų." },
    { h: "Lemiamas veiksnys: gretimų dantų būklė" },
    { p: "Jei dantys šalia tarpo jau reikia karūnėlių, tiltas yra efektyvus pasirinkimas." },
    { h: "Sąžiningas klausimas, kurį verta užduoti" },
    { p: "Jei klinika rekomenduoja tiltą vietoj implanto, protinga paklausti kodėl." },
  ]
},
{
  slug: "kas-vyksta-saknies-kanalo-gydymo-metu-zingsnis-po-zingsnio",
  title: "Kas vyksta šaknies kanalo gydymo metu, žingsnis po žingsnio",
  description: "Aiškus, žingsnis po žingsnio aprašymas to, kas iš tikrųjų vyksta šaknies kanalo gydymo metu.",
  date: "2026-09-02",
  relatedTreatment: "saknies-kanalo-gydymas-istanbul",
  body: [
    { h: "Kodėl ši procedūra turi blogesnę reputaciją nei patirtis" },
    { p: "Dažnai manoma, kad šaknies kanalo gydymas yra skausmingas, tačiau nepatogumas paprastai kyla iš pačios infekcijos." },
    { h: "1 žingsnis — Diagnozė ir rentgenas" },
    { p: "Rentgenas patvirtina infekcijos mastą ir kiek kanalų turi danties šaknis." },
    { h: "2 žingsnis — Vietinė nejautra" },
    { p: "Dantis ir aplinkinė sritis anestezuojami prieš vykstant bet kam kitam." },
    { h: "3 žingsnis — Infekuoto audinio pašalinimas" },
    { p: "Dantyje sukuriama maža anga prieigai prie infekuotos pulpos viduje." },
    { h: "4 žingsnis — Kanalo valymas ir dezinfekcija" },
    { p: "Tuščia kanalo erdvė valoma, formuojama ir dezinfekuojama." },
    { h: "5 žingsnis — Danties uždarymas" },
    { p: "Išvalytas kanalas užpildomas biologiškai suderinama medžiaga." },
    { h: "6 žingsnis — Paprastai apsauginė karūnėlė" },
    { p: "Kadangi dantis po šaknies kanalo gydymo gali tapti trapesnis, paprastai rekomenduojama karūnėlė." },
    { h: "Kaip iš tikrųjų jaučiasi atsigavimas" },
    { p: "Lengvas skausmas dieną ar dvi po to yra normalus ir valdomas standartiniais skausmą malšinančiais vaistais." },
  ]
},

{
  slug: "pozymiai-kad-gali-prireikti-gingivektomijos",
  title: "Požymiai, kad gali prireikti gingivektomijos",
  description: "Gingivektomija skirta ne tik „dantenų šypsenai“ — štai praktiniai požymiai, kad dantenų perdailinimas iš tikrųjų verta aptarti su odontologu.",
  date: "2026-09-02",
  relatedTreatment: "gingivektomija-istanbul",
  body: [
    { h: "Tai daugiau nei tik išvaizda" },
    { p: "Gingivektomija dažnai minima tik kosmetiniame kontekste, tačiau perteklinis ar netolygus dantenų audinys taip pat gali būti tikra burnos sveikatos problema." },
    { h: "1 požymis — Šypsodamiesi rodote pastebimai daugiau dantenų nei danties" },
    { p: "„Dantenų šypsena“, kai plati dantenų audinio juosta matoma virš dantų natūraliai šypsantis, yra dažniausiai pripažįstama priežastis, kodėl žmonės svarsto gingivektomiją." },
    { h: "2 požymis — Jūsų dantenų linija netolygi išilgai priekinių dantų" },
    { p: "Net kai bendras matomo dantenų kiekis nėra perteklinis, netolygūs lygiai gali sukelti kitaip gerai suformuotų dantų neatitikimą." },
    { h: "3 požymis — Perteklinis dantenų audinys apsunkina tinkamą dantų valymą" },
    { p: "Audinys, kuris persidengia ar kaupiasi aplink dantis, gali sulaikyti apnašas taip, kad tikrai sunku efektyviai valyti šepetėliu ar siūlu." },
    { h: "4 požymis — Planuojate fasetes ar karūnėles, o jūsų dantenų lygiai netolygūs" },
    { p: "Jei kosmetinis atvejis planuojamas aplink netolygias dantenas jų pirmiausia nekoreguojant, baigti dantys gali atrodyti netolygūs." },
    { h: "Ką iš tikrųjų daryti" },
    { p: "Nė vienas iš šių požymių nereiškia, kad gingivektomija automatiškai yra teisingas atsakymas būtent jums." },
  ]
},
{
  slug: "klausimai-pries-renkantis-klinika-uzsienyje",
  title: "Klausimai, kuriuos reikia užduoti prieš renkantis odontologijos kliniką užsienyje",
  description: "Praktinis kontrolinis sąrašas to, ko iš tikrųjų paklausti prieš rezervuojant dantų gydymą kitoje šalyje.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Vien kainų palyginimas nedaug pasako" },
    { p: "Dvi klinikos gali pasiūlyti tą pačią kainą už „All-on-4“ ir turėti omenyje tikrai skirtingus dalykus." },
    { h: "1. Kokį konkretų implanto ar medžiagos prekės ženklą naudojate?" },
    { p: "Tikri, nusistovėję prekės ženklai turi atsekamą gamybos istoriją." },
    { h: "2. Ar garantija yra rašytinė ir ką tiksliai ji apima?" },
    { p: "„Visą gyvenimą galiojanti garantija“ turėtų nurodyti, kas įtraukta." },
    { h: "3. Kas atlieka atvejo planavimą ir ar tai grindžiama mano pačių skenavimais?" },
    { p: "Jūsų gydymo planas turėtų būti sudarytas iš jūsų pačių 3D skenavimų." },
    { h: "4. Kas atsitinka, jei kažkam reikia dėmesio po to, kai grįžtu namo?" },
    { p: "Klinika, pasitikinti savo darbu, turėtų turėti aiškų atsakymą." },
    { h: "5. Ar klinika oficialiai įgaliota tarptautiniams pacientams?" },
    { p: "Konkrečiai Turkijoje klinikos, gydančios tarptautinius pacientus, turėtų turėti galiojantį leidimą." },
    { h: "6. Kas iš tikrųjų įtraukta į nurodytą kainą?" },
    { p: "Paklauskite konkrečiai, ar pasiūlymas apima konsultaciją, visus skenavimus ir tolesnius vizitus." },
  ]
},
{
  slug: "kokius-sertifikatus-turetu-tureti-odontologijos-klinika-uzsienyje",
  title: "Kokius sertifikatus iš tikrųjų turėtų turėti odontologijos klinika užsienyje?",
  description: "Sertifikatus ir akreditacijos ženklelius lengva parodyti ir sunku patikrinti vien iš svetainės.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Ne visi sertifikatai turi tą patį svorį" },
    { p: "Klinikų svetainėse dažnai rodoma eilė ženklelių ir antspaudų." },
    { h: "Tarptautinio sveikatos turizmo leidimas (specifinis Turkijai)" },
    { p: "Turkijoje klinikos, teisėtai gydančios tarptautinius pacientus, turėtų turėti šį leidimą iš Sveikatos ministerijos." },
    { h: "ISO sertifikatai" },
    { p: "Tai bendri kokybės valdymo ar skundų nagrinėjimo standartai, taikomi daugelyje pramonės šakų." },
    { h: "Implantų gamintojų sertifikatai" },
    { p: "Kai kurios klinikos rodo sertifikatus, patvirtinančius, kad jos yra įgaliotos konkretaus implanto prekės ženklo naudotojos." },
    { h: "Ką iš tikrųjų daryti su šia informacija" },
    { p: "Nepasikliaukite vien ženkleliais, rodomais svetainėje — paklauskite klinikos tiesiogiai leidimo numerio." },
  ]
},
{
  slug: "kiek-iš-tikrujų-trunka-cirkonio-karuneles",
  title: "Kiek iš tikrųjų trunka cirkonio karūnėlės?",
  description: "Realistiškas žvilgsnis į cirkonio karūnėlių tarnavimo laiką.",
  date: "2026-09-02",
  relatedTreatment: "monolitinis-cirkonis-karunieles-istanbul",
  body: [
    { h: "Bendras intervalas" },
    { p: "Gerai pagamintos cirkonio karūnėlės paprastai tarnauja 10–15 metų ar ilgiau su pagrįsta priežiūra." },
    { h: "Kodėl monolitinis cirkonis linkęs tarnauti ilgiau nei senesnės cirkonio karūnėlės" },
    { p: "Senesnės cirkonio karūnėlės naudojo cirkonio šerdį su atskiru porceliano sluoksniu estetikai." },
    { h: "Kas iš tikrųjų sutrumpina karūnėlės tarnavimo laiką" },
    { p: "Negydomas dantų griežimas (bruksizmas) sukuria pasikartojančią per didelę jėgą karūnėlei." },
    { h: "Ką galite padaryti, kad ji tarnautų ilgiau" },
    { p: "Normalus šepetėlio ir siūlo naudojimas, naktinis apsaugas, jei esate žinomas griežėjas." },
    { h: "Kai „gedimas“ iš tikrųjų nesusijęs su karūnėle" },
    { p: "Jei karūnėlę reikia pakeisti po kelerių metų, verta suprasti kodėl." },
  ]
},
{
  slug: "monolitinis-ar-sluoksniuotas-cirkonis-koks-skirtumas",
  title: "Monolitinis ar sluoksniuotas cirkonis: Koks skirtumas?",
  description: "Abu vadinami „cirkonio karūnėlėmis“, tačiau konstrukcija iš tikrųjų skiriasi.",
  date: "2026-09-02",
  relatedTreatment: "monolitinis-cirkonis-karunieles-istanbul",
  body: [
    { h: "Ta pati bazinė medžiaga, skirtinga konstrukcija" },
    { p: "Ir monolitinis, ir sluoksniuotas cirkonis naudoja cirkonio oksidą, tačiau jų konstravimo būdas iš tikrųjų skiriasi." },
    { h: "Sluoksniuotas cirkonis" },
    { p: "Sluoksniuota karūnėlė turi cirkonio šerdį tvirtumui, vainikuotą atskiru porceliano sluoksniu." },
    { h: "Monolitinis cirkonis" },
    { p: "Monolitinė karūnėlė visiškai frezuojama iš vieno cirkonio bloko, be atskiro porceliano sluoksnio." },
    { h: "Kur kiekvienas paprastai naudojamas" },
    { p: "Monolitinis cirkonis paprastai teikiamas pirmenybė galiniams dantims." },
    { h: "Išvada" },
    { p: "Jei patvarumas prieš atplaišėjimą yra jūsų pagrindinis prioritetas, monolitinis cirkonis paprastai yra saugesnis pasirinkimas." },
  ]
},
{
  slug: "ar-galima-derinti-implantus-ir-fasetes-vienoje-keliones",
  title: "Ar galima derinti implantus ir fasetes vienoje kelionėje?",
  description: "Gydymo derinimas yra dažnas, tačiau implanto gijimo grafikas keičia planavimo būdą.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Taip, bet implanto grafikas nustato tempą" },
    { p: "Implantų derinimas su fasetėmis, karūnėlėmis ar balinimu yra dažnas prašymas." },
    { h: "Kaip tai paprastai planuojama" },
    { p: "Per pirmąjį apsilankymą implantai įdiegiami." },
    { h: "Kodėl balinimo laikas čia ypač svarbus" },
    { p: "Jei taip pat gaunate fasetes ar karūnėles, balinimas turėtų vykti prieš jų gamybą." },
    { h: "Ką turėtų pasakyti derinamas gydymo planas" },
    { p: "Tinkamas planas išsamiai aprašo, kas vyksta kiekvieną kiekvieno apsilankymo dieną." },
    { h: "Praktinė derinimo nauda" },
    { p: "Gydymo derinimas iš tikrųjų sumažina bendrą kelionę." },
  ]
},
{
  slug: "odontologinio-nerimo-valdymas-keliaujant-gydymui",
  title: "Odontologinio nerimo valdymas keliaujant gydymui",
  description: "Odontologinis nerimas neišnyksta vien todėl, kad keliaujate gydymui.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Tai dažnas rūpestis, ne neįprastas" },
    { p: "Odontologinis nerimas yra itin paplitęs, o kelionė į užsienį gydymui gali pridėti papildomą streso sluoksnį." },
    { h: "Iš tikrųjų prieinami raminimo variantai" },
    { p: "Dauguma klinikų siūlo variantus, viršijančius vien vietinę nejautrą." },
    { h: "Bendravimas svarbesnis nei žmonės tikisi" },
    { p: "Nerimas dažnai blogesnis, kai visiškai nesuprantate, kas vyksta." },
    { h: "Planavimas padeda daugiau, nei dauguma žmonių supranta" },
    { p: "Iš anksto žinojimas savo dienos tvarkaraščio sumažina neapibrėžtumą." },
    { h: "Protinga tai pasakyti iš anksto" },
    { p: "Tiesioginis pasakymas savo koordinatoriui, kad jaučiate odontologinį nerimą, duoda jiems galimybę planuoti aplink tai." },
  ]
},
{
  slug: "ka-pasiruosti-pries-odontologini-gydyma-uzsienyje",
  title: "Ką pasiruošti prieš odontologinį gydymą užsienyje",
  description: "Praktinis kontrolinis sąrašas prieš kelionę.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Prieš ką nors rezervuojant" },
    { p: "Gaukite rašytinį gydymo planą, pagrįstą jūsų pačių nuotraukomis ar skenavimais." },
    { h: "Medicininė informacija, kurią reikia turėti paruoštą" },
    { p: "Vartojamų vaistų, alergijų ir susijusių sveikatos būklių sąrašas turėtų būti pasidalintas prieš keliaujant." },
    { h: "Esami dantų įrašai, jei turite" },
    { p: "Nauji rentgenai ar pastabos iš įprasto odontologo gali paspartinti planavimą." },
    { h: "Praktinė kelionės logistika" },
    { p: "Konkrečiai implantų atvejais patvirtinkite abi apsilankymo datas iš anksto." },
    { h: "Klausimai, į kuriuos reikia atsakyti prieš skrendant" },
    { p: "Bendras reikalingų apsilankymų skaičius, kas apima kiekvieną iš jų." },
    { h: "Ką iš tikrųjų pasiimti" },
    { p: "Aukščiau minėtą vaistų sąrašą ar esamus įrašus, patogius drabužius." },
  ]
},
{
  slug: "karunele-ar-plomba-koks-skirtumas",
  title: "Karūnėlė ar plomba: Koks skirtumas ir kada reikia kurios?",
  description: "Abi taiso pažeistą dantį, tačiau labai skirtingais pažeidimo lygiais.",
  date: "2026-09-03",
  relatedTreatment: "monolitinis-cirkonis-karunieles-istanbul",
  body: [
    { h: "Viskas priklauso nuo to, kiek sveiko danties lieka" },
    { p: "Plomba taiso mažą ar vidutinę pažeidimo sritį, paprastai nuo ėduonies." },
    { h: "Kada plombos pakanka" },
    { p: "Maži ir vidutiniai ėduonys, pakankamai anksti pastebėti, paprastai gerai išsprendžiami plomba." },
    { h: "Kada plombos nepakanka" },
    { p: "Jei ėduonys išplitęs, ar dantis įtrūkęs, karūnėlė vietoj to suteikia pilną dengimą." },
    { h: "Kodėl plombos dėjimas ten, kur reikia karūnėlės, neišlieka" },
    { p: "Per didelė plomba, palyginti su likusia danties struktūra, labiau linkusi įtrūkti." },
    { h: "Sąžiningas atsakymas iš gero odontologo" },
    { p: "Odontologas, tiesiogiai žiūrintis į rentgeną ir patį dantį, gali pasakyti, ko reikia jūsų konkrečiam dančiui." },
  ]
},
{
  slug: "all-on-4-kaina-kas-iš-tikrujų-ijeita",
  title: "All-on-4 kaina: Kas iš tikrųjų įeina į kainą?",
  description: "All-on-4 pasiūlymai gali atrodyti labai skirtingai tarp klinikų dėl priežasčių, neturinčių nieko bendra su kokybe.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-implantai-istanbul",
  body: [
    { h: "Kodėl ta pati procedūra gauna labai skirtingus pasiūlymus" },
    { p: "Dvi klinikos gali abi pasiūlyti „All-on-4“ labai skirtingomis kainomis." },
    { h: "Implanto prekės ženklas ir kokybė" },
    { p: "Nusistovėję, kliniškai patvirtinti implantų prekės ženklai paprastai kainuoja daugiau." },
    { h: "Kas įtraukta į nurodytą kainą" },
    { p: "Paklauskite konkrečiai, ar pasiūlymas apima pradinę konsultaciją, 3D skenavimą." },
    { h: "Ar tikėtina kaulo priauga ar sinuso pakėlimas, ir ar tai įtraukta" },
    { p: "Jei jūsų atveju gali prireikti papildomo kaulo darbo, pasiūlymas, duotas prieš peržiūrint skenavimą, negali to atsižvelgti." },
    { h: "Tolesnės priežiūros ir garantijos sąlygos" },
    { p: "Patikrinkite, ar priežiūros po gydymo patikrinimai ir garantijos laikotarpis įtraukti į kainą." },
    { h: "Vienas klausimas, kuris paaiškina daugumą to" },
    { p: "Paklauskite tiesiogiai: „kas pakeistų šią galutinę kainą?“" },
  ]
},
{
  slug: "ar-galima-idiegti-dantu-implantus-jei-rukote",
  title: "Ar galima įdiegti dantų implantus, jei rūkote?",
  description: "Rūkymas automatiškai neatmeta implantų, tačiau tai realus veiksnys, į kurį odontologai žiūri rimtai.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-implantai-istanbul",
  body: [
    { h: "Rūkymas yra rizikos veiksnys, ne automatinis diskvalifikavimas" },
    { p: "Daugelis rūkalių gauna sėkmingus, ilgalaikius dantų implantus." },
    { h: "Kodėl gijimo laikotarpis čia toks svarbus" },
    { p: "Osteointegracija priklauso nuo sveiko kraujo tiekimo į tą sritį." },
    { h: "Ką iš tikrųjų rekomenduoja dauguma odontologų" },
    { p: "Daugelis klinikų rekomenduoja mesti rūkyti, ar bent žymiai sumažinti." },
    { h: "Svarbu būti atviram apie tai" },
    { p: "Pasakymas savo odontologui, kad rūkote, leidžia jam tinkamai planuoti aplink tai." },
    { h: "Išvada" },
    { p: "Rūkymas daro implantų gydymą šiek tiek rizikingesnį, ne neįmanomą." },
  ]
},
{
  slug: "kas-yra-osteointegracija-ir-kodel-tai-svarbu-implantams",
  title: "Kas yra osteointegracija, ir kodėl tai svarbu implantams?",
  description: "Terminas, paaiškinantis, kodėl implantų gydymas trunka mėnesius, o ne dienas.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-implantai-istanbul",
  body: [
    { h: "Žodis, paaiškinantis dviejų apsilankymų implanto grafiką" },
    { p: "Osteointegracija yra procesas, kurio metu titano implantas fiziškai susilieja su aplinkiniu žandikaulio kaulu." },
    { h: "Kodėl konkrečiai titanas" },
    { p: "Titanas turi tikrai neįprastą savybę: gyvos kaulo ląstelės auga tiesiogiai ant jo paviršiaus ir jame." },
    { h: "Kiek laiko tai trunka" },
    { p: "Osteointegracija paprastai trunka kelis mėnesius, dažnai minima kaip apie tris–šešis mėnesius." },
    { h: "Kas atsitinka, jei šis žingsnis skubinamas" },
    { p: "Implanto apkrovimas galutine, nuolatine restauracija prieš baigiantis osteointegracijai rizikuoja." },
    { h: "Kodėl tai svarbu lyginant klinikas" },
    { p: "Klinika, žadanti visiškai nuolatinę implanto restauraciją vienu trumpu apsilankymu, arba dirba su neįprastai paprastu atveju." },
  ]
},
{
  slug: "kiek-kainuoja-danti-implantai-turkijoje",
  title: "Kiek kainuoja dantų implantai Turkijoje?",
  description: "Realistiška dantų implantų kainos Turkijoje apžvalga, kodėl kainos skiriasi tarp klinikų ir ką tikrai reikėtų palyginti prieš priimant sprendimą.",
  date: "2026-09-10",
  relatedTreatment: "dantu-implantai-istanbul",
  body: [
    { h: "Nėra vieno skaičiaus, ir bet kuri klinika, nurodanti kainą prieš pamatydama jūsų atvejį, spėlioja" },
    { p: "Implanto kaina priklauso nuo naudojamo implanto prekės ženklo, kaulo transplantacijos poreikio ir reikalingų implantų skaičiaus." },
    { h: "Implanto prekės ženklas yra didžiausias kainos veiksnys" },
    { p: "Klinikos paprastai siūlo daugiau nei vieną implantų sistemą, o kainų skirtumas tarp jų yra realus — dažnai 30-40% tarp ekonominės ir premium sistemos." },
    { h: "Kiek paprastai kainuoja vienas implantas" },
    { p: "Už vieną danties implantą (tik patį varžtą, be karūnėlės viršuje), kainos Stambulo klinikose paprastai svyruoja nuo ~300€ iki 450€+ premium sistemoms." },
    { h: "Kodėl karūnėlė yra atskira išlaida" },
    { p: "Implantas pakeičia šaknį; karūnėlė pakeičia matomą dantį. Pilnas \"implantas + karūnėlė\" pasiūlymas turėtų aiškiai nurodyti abu." },
    { h: "Kas iš tikrųjų keičia bendrą sumą" },
    { p: "Kaulo transplantacija arba sinuso pakėlimas, jei jūsų atvejui to reikia, pridedami prie bendros sumos — tai tikrai priklauso nuo jūsų žandikaulio kaulo būklės." },
    { h: "Kaip gauti realų skaičių savo atvejui" },
    { p: "Atsiųskite naujausią panoraminę rentgeno nuotrauką, jei turite, arba suplanuokite 3D skenavimą konsultacijos metu." },
  ]
},
{
  slug: "all-on-4-kaina-turkija-vs-uk-jav",
  title: "All-on-4 kaina Turkijoje vs JK ir JAV: Ką tikrai lyginate",
  description: "Kodėl All-on-4 pasiūlymai taip skiriasi tarp šalių, ir kas iš tikrųjų sukelia skirtumą, be darbo jėgos kaštų.",
  date: "2026-09-10",
  relatedTreatment: "all-on-4-5-6-implantai-istanbul",
  body: [
    { h: "Skirtumas yra realus, bet tai ne tik \"pigesnė darbo jėga\"" },
    { p: "All-on-4 Turkijoje paprastai siūlomas už maždaug trečdalį iki pusės tipinės JK ar JAV kainos." },
    { h: "Ką paprastai apima pilno lanko atvejis Turkijoje" },
    { p: "Pilnas fiksuotas lankas ant keturių implantų, įskaitant operaciją, paprastai kainuoja nuo ~2900€ lankui su prieinamesne sistema iki 3400€ su premium sistema." },
    { h: "Kodėl All-on-5 ar All-on-6 kainuoja daugiau" },
    { p: "Penkto ar šešto implanto pridėjimas padidina sumą maždaug 300-450€ už papildomą implantą." },
    { h: "Ką gali apimti JK ir JAV kainos, ko neturi pasiūlymas iš Turkijos" },
    { p: "Palyginkite, kas iš tikrųjų yra įtraukta kiekviename pasiūlyme: ar JK kaina apima kontrolinį vizitą?" },
    { h: "Tikras kaštų svarstymas, kurį dauguma praleidžia" },
    { p: "Net atsižvelgiant į skrydžius ir apgyvendinimą, bendra suma už pilno lanko atvejį užsienyje paprastai išlieka žymiai mažesnė." },
    { h: "Ką paklausti prieš lyginant du pasiūlymus" },
    { p: "Paklauskite kiekvienos klinikos, kokia implanto prekės ženklas naudojamas ir ką iš tikrųjų dengia garantija." },
  ]
},
{
  slug: "laminuotu-fasieciu-kaina-stambulas",
  title: "Laminuotų fasečių kaina Stambule: Kas iš tikrųjų įtraukta",
  description: "Aiškus žvilgsnis į tai, kas lemia laminuotų fasečių kainą Stambule, ir ką turėtų apimti teisingas pasiūlymas.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Kaina paprastai nurodoma už dantį, ne už šypseną" },
    { p: "Laminuotų fasečių kainodara beveik visada yra už atskirą dantį, todėl bendra suma visiškai priklauso nuo to, kiek dantų įtraukta į jūsų šypsenos dizainą." },
    { h: "Kiek paprastai kainuoja viena fasetė" },
    { p: "Kaina už dantį laminuotoms fasetėms Stambule paprastai patenka į maždaug 300-400€ diapazoną." },
    { h: "Kodėl medžiaga įtakoja kainą ir rezultatą" },
    { p: "Ploni porceliano laminatai reikalauja tikslaus, minimalaus danties paruošimo ir įgudusio keramiko." },
    { h: "Ką turėtų apimti siūloma kaina" },
    { p: "Teisingas fasečių pasiūlymas turėtų apimti skaitmeninio šypsenos dizaino konsultaciją ir cementavimą." },
    { h: "Laikinųjų fasečių etapas" },
    { p: "Tarp paruoštų dantų ir galutinių fasečių uždėjimo paprastai nešiosite laikinąsias fasetes kelias dienas." },
    { h: "Kodėl pigiausias pasiūlymas nėra automatiškai geriausia vertė" },
    { p: "Žymiai žemesnė kaina už dantį nei viskas kita, ką matote, verta tiesioginio klausimo." },
  ]
},
{
  slug: "hollywood-smile-kaina-kas-lemia-kaina",
  title: "Hollywood Smile kaina: Kas lemia galutinę kainą",
  description: "Hollywood Smile kainodara skiriasi labiau nei beveik bet kuris kitas gydymas, nes tai ne viena fiksuota procedūra.",
  date: "2026-09-10",
  relatedTreatment: "hollywood-smile-istanbul",
  body: [
    { h: "\"Hollywood Smile\" apibūdina rezultatą, ne fiksuotą kainoraštį" },
    { p: "Kadangi Hollywood Smile gali būti pasiektas fasetėmis, karūnėlėmis ar abiejų mišiniu, dvi klinikos su labai skirtingomis sumomis gali iš tikrųjų kainoti skirtingus gydymo planus." },
    { h: "Įtrauktų dantų skaičius yra didžiausias vienas veiksnys" },
    { p: "Pilna Hollywood Smile transformacija paprastai apima viršutinius matomus 16-20 dantų." },
    { h: "Fasetės vs karūnėlės keičia kainą už dantį" },
    { p: "Laminuotos fasetės ir pilnos cirkonio karūnėlės kainuojamos skirtingai." },
    { h: "Ką prideda pilnas skaitmeninis šypsenos dizainas" },
    { p: "Teisingas Hollywood Smile planas prasideda 3D skaitmeniniu šypsenos dizainu." },
    { h: "Kodėl du \"Hollywood Smile paketai\" gali skirtis tūkstančiais eurų" },
    { p: "Didžiausi svyravimai kyla iš įtrauktų dantų skaičiaus ir medžiagos klasės." },
    { h: "Klausimas, kurį verta užduoti tiesiogiai" },
    { p: "Paklauskite tiksliai, kiek dantų įtraukta į siūlomą kainą." },
  ]
},
{
  slug: "cirkonio-karuneles-kaina-pigiau-ne-visada-geriau",
  title: "Cirkonio karūnėlės kaina: Pigiau ne visada geriau",
  description: "Kas iš tikrųjų įtakoja cirkonio karūnėlės kainą, ir kodėl žemiausias pasiūlymas kartais gali kainuoti daugiau ilgalaikėje perspektyvoje.",
  date: "2026-09-10",
  relatedTreatment: "monolitinis-cirkonis-karunieles-istanbul",
  body: [
    { h: "Bazinė kaina paprastai kukli — kaupiasi būtent papildomos paslaugos" },
    { p: "Viena cirkonio karūnėlė savaime yra viena iš prieinamesnių restauracijos galimybių — paprastai 120-180€ už vienetą Stambule." },
    { h: "Monolitinis vs sluoksniuotas cirkonis" },
    { p: "Monolitinis cirkonis, frezuotas iš vieno vientiso bloko, paprastai yra atsparesnis skilimams." },
    { h: "Ką prideda titano pagrindas" },
    { p: "Specifiškai implantais paremtoms karūnėlėms titano pagrindas prideda reikšmingą sumą prie kainos." },
    { h: "Kodėl žymiai pigesnis pasiūlymas verta tiesioginio klausimo" },
    { p: "Paklauskite konkrečiai, ar tai monolitinis, ar sluoksniuotas cirkonis, ir kokia garantijos trukmė įtraukta." },
    { h: "Kaip karūnėlių skaičius greitai keičia bendrą sumą" },
    { p: "Kadangi kainodara yra už vienetą, gaukite vieneto kainą ir padauginkite ją patys." },
    { h: "Ką iš tikrųjų nurodo sąžiningas pasiūlymas" },
    { p: "Patikimas pasiūlymas nurodo kainą už karūnėlę, konkretų cirkonio tipą ir garantijos trukmę." },
  ]
},
{
  slug: "saknies-kanalo-gydymo-kaina-turkija",
  title: "Šaknies kanalo gydymo kaina Turkijoje: Ko tikėtis",
  description: "Tiesioginis žvilgsnis į tai, kiek paprastai kainuoja šaknies kanalo gydymas Turkijoje, ir ko dar gali prireikti.",
  date: "2026-09-10",
  relatedTreatment: "saknies-kanalo-gydymas-istanbul",
  body: [
    { h: "Pats šaknies kanalo gydymas yra viena iš prieinamesnių procedūrų" },
    { p: "Pats savaime, šaknies kanalo gydymas Stambule paprastai kainuoja apie 130-170€ už dantį." },
    { h: "Kodėl krūminiai dantys gali kainuoti daugiau nei priekiniai" },
    { p: "Dantis su daugiau kanalų užtrunka ilgiau kruopščiai išvalyti ir užpildyti." },
    { h: "Papildoma kaina, kurios žmonės ne visada planuoja: karūnėlė po to" },
    { p: "Dantis po šaknies kanalo gydymo yra labiau linkęs lūžti laikui bėgant." },
    { h: "Ką prideda pluoštinis kaištis" },
    { p: "Jei trūksta didelės natūralios danties struktūros dalies, kartais prieš karūnėlę į kanalą įdedamas mažas pluoštinis kaištis." },
    { h: "Šaknies kanalo gydymo kainos palyginimas su alternatyva" },
    { p: "Danties ištraukimas ir pakeitimas implantu yra žymiai didesnė kaina." },
    { h: "Ką prašyti savo pasiūlyme" },
    { p: "Paklauskite, ar pasiūlymas tik dėl šaknies kanalo gydymo, ar apima tolesnę karūnėlę." },
  ]
},
{
  slug: "pilno-protezo-kaina-stambulas-galimybes",
  title: "Pilno protezo kaina Stambule: Galimybės ir kainos",
  description: "Kiek paprastai kainuoja pilnas protezas Stambule, kaip jis lyginamas su implantais paremtomis galimybėmis.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Tradicinis pilnas protezas yra viena iš prieinamesnių galimybių" },
    { p: "Pilnas nuimamas protezas vienam lankui paprastai kainuoja apie 700-900€ Stambule." },
    { h: "Kodėl jis kainuoja mažiau nei implantais paremtos galimybės" },
    { p: "Tradicinis protezas neapima implantacijos operacijos — jis dedamas tiesiai ant dantenų." },
    { h: "Kompromisas, kurį verta suprasti prieš sprendimą" },
    { p: "Nuimamas protezas reikalauja daugiau koregavimų laikui bėgant." },
    { h: "Nakties įtvaras yra susijusi, atskira kaina" },
    { p: "Jei griežiate dantimis, nakties įtvaras apsaugo jūsų investiciją bet kuriuo atveju." },
    { h: "Kaip tai lyginama su All-on-4" },
    { p: "All-on-4 kainuoja žymiai daugiau iš pradžių, daugiausia dėl implantacijos operacijos." },
    { h: "Ką apima teisingas protezo pasiūlymas" },
    { p: "Pilnas pasiūlymas turėtų nurodyti, ar tai pilnas, ar dalinis protezas." },
  ]
},
{
  slug: "dantu-balinimo-kaina-viena-sesija-vs-paketas",
  title: "Dantų balinimo kaina: Viena sesija vs paketas",
  description: "Kiek paprastai kainuoja profesionalus dantų balinimas, ir kodėl jis dažnai sujungiamas su kitais gydymo būdais.",
  date: "2026-09-10",
  relatedTreatment: "dantu-balinimas-istanbul",
  body: [
    { h: "Balinimas yra viena iš prieinamesnių savarankiškų procedūrų" },
    { p: "Viena profesionalaus balinimo sesija, įskaitant išankstinį valymą, paprastai kainuoja apie 130-170€ Stambule." },
    { h: "Kodėl jis dažnai įtraukiamas kartu su kitu darbu" },
    { p: "Jei taip pat darotės fasetes, likusių natūralių dantų balinimas paprastai atliekamas iš anksto." },
    { h: "Akmenų valymas, kuris paprastai įtrauktas" },
    { p: "Teisinga balinimo sesija paprastai pirmiausia apima paviršinio akmens ir apnašų šalinimą." },
    { h: "Kodėl rezultatai skiriasi tarp pacientų" },
    { p: "Kiek labiau pašviesėja jūsų dantys, priklauso nuo pradinio atspalvio." },
    { h: "Viena sesija vs kelios" },
    { p: "Dauguma pacientų mato pilną rezultatą po vienos sesijos klinikoje." },
    { h: "Ką patvirtinti prieš rezervuojant" },
    { p: "Patvirtinkite, ar siūloma kaina apima valymą prieš balinimą." },
  ]
},
{
  slug: "sinuso-pakelimo-kaina-kada-reikalinga",
  title: "Sinuso pakėlimo kaina: Kada reikalinga ir ką prideda",
  description: "Aiškus paaiškinimas, kada sinuso pakėlimas yra tikrai reikalingas, ir kiek jis paprastai kainuoja.",
  date: "2026-09-10",
  relatedTreatment: "sinuso-pakelimas-istanbul",
  body: [
    { h: "Sinuso pakėlimas pridedamas tik tada, kai jūsų skenavimas tikrai tai parodo" },
    { p: "Tai ne gydymas, kurį kas nors pasirenka iš anksto — jis pridedamas prie implantacijos plano tik tada, kai 3D skenavimas parodo nepakankamą kaulo aukštį." },
    { h: "Kiek paprastai kainuoja standartinis sinuso pakėlimas" },
    { p: "Sinuso pakėlimas, kai reikalingas, paprastai prideda apie 350-450€ prie implantacijos gydymo plano." },
    { h: "Kodėl kai kuriems atvejams tikrai reikia, o kitiems ne" },
    { p: "Danties trūkstant kurį laiką, sinuso ertmė gali palaipsniui plėstis." },
    { h: "Skirtumas tarp \"uždaro\" ir \"atviro\" sinuso pakėlimo" },
    { p: "Uždaras sinuso pakėlimas yra mažesnė, mažiau invazinė technika, naudojama, kai reikia tik nedidelio papildomo aukščio." },
    { h: "Kodėl tai įtakoja ne tik kainą, bet ir jūsų gydymo grafiką" },
    { p: "Jei reikia atviro sinuso pakėlimo, tai paprastai prideda kelis mėnesius prie bendro grafiko." },
    { h: "Sąžininga išvada" },
    { p: "Nežinosite, ar jums reikia sinuso pakėlimo, kol jūsų atvejis nebus iš tikrųjų ištirtas 3D skenavimu." },
  ]
},
{
  slug: "danti-implantu-prekiu-zenklai-kodel-itakoja-kaina",
  title: "Dantų implantų prekių ženklai: Kodėl jie taip stipriai įtakoja kainą",
  description: "Kodėl ta pati implantacijos procedūra gali būti kainojama labai skirtingai priklausomai nuo naudojamos implantų sistemos.",
  date: "2026-09-10",
  relatedTreatment: "dantu-implantai-istanbul",
  body: [
    { h: "Ne visi implantai yra tas pats produktas" },
    { p: "Implantas yra titano varžtas, pagamintas konkrečios kompanijos, su savo tyrimais." },
    { h: "Kas paprastai skiria premium sistemą nuo prieinamesnės" },
    { p: "Premium implantų sistemos paprastai turi ilgesnę publikuotų ilgalaikių klinikinių tyrimų istoriją." },
    { h: "Kodėl tai svarbu, jei galiausiai lankotės pas kitą odontologą" },
    { p: "Plačiai pripažintą tarptautinį prekės ženklą paprastai lengviau rasti dalimis." },
    { h: "Tai nereiškia, kad prieinamesnis pasirinkimas yra blogas pasirinkimas" },
    { p: "Tiek premium, tiek prieinamesnės implantų sistemos yra teisėti medicinos prietaisai su CE ženklu." },
    { h: "Kainų skirtumas praktikoje" },
    { p: "Skirtumas paprastai yra apie 30-40% už implantą." },
    { h: "Vienintelis klausimas, kuris tikrai svarbus" },
    { p: "Paklauskite bet kurios klinikos tiksliai, kokį implanto prekės ženklą jie siūlo." },
  ]
},
{
  slug: "kodel-danti-kainos-turkijoje-tokios-zemesnes",
  title: "Kodėl dantų kainos Turkijoje tokios daug žemesnės? Tikras paaiškinimas",
  description: "Tikros ekonominės priežastys, kodėl dantų gydymas kainuoja mažiau Turkijoje.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Tai ne todėl, kad odontologija yra žemesnės kokybės" },
    { p: "Kainų skirtumas tarp Turkijos ir Vakarų Europos kyla iš kelių sudėtinių veiksnių." },
    { h: "Pragyvenimo kaštai ir klinikos pridėtinės išlaidos" },
    { p: "Nuoma ir personalo atlyginimai struktūriškai yra žemesni Turkijoje nei Londone ar Berlyne." },
    { h: "Valiutų kursai veikia tarptautinių pacientų naudai" },
    { p: "Kadangi klinikos kaštai daugiausia yra Turkijos liromis, valiutų kursai sustiprina kainų pranašumą." },
    { h: "Vyriausybės parama sveikatos turizmo sektoriui" },
    { p: "Turkijos vyriausybė aktyviai investavo į šalies pozicionavimą kaip sveikatos turizmo tikslą." },
    { h: "Didesnis pacientų srautas keičia ekonomiką" },
    { p: "Klinikos, kurios priima daug tarptautinių pacientų, gali investuoti į savo laboratorijas." },
    { h: "Ko tai nereiškia" },
    { p: "Žemesnė kaina automatiškai nereiškia žemesnių standartų." },
  ]
},
{
  slug: "ar-saugus-dantu-turizmas-turkijoje",
  title: "Ar saugus dantų turizmas Turkijoje? Ką iš tikrųjų rodo duomenys",
  description: "Faktinė apžvalga apie dantų turizmo saugumą Turkijoje — reglamentavimą už jo, pramonės mastą ir kas iš tikrųjų apsaugo pacientus.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Tai pirmasis klausimas, kurį užduoda beveik kiekvienas potencialus pacientas" },
    { p: "Trumpas atsakymas yra tas, kad Turkija turi oficialią, valstybės reguliuojamą sistemą tam." },
    { h: "Reguliavimo sistema buvo sustiprinta 2025 metais" },
    { p: "Turkijos sveikatos turizmo taisyklės buvo sustiprintos 2025 m. balandį." },
    { h: "Pramonės mastas tikrais skaičiais" },
    { p: "Pagal Turkijos sveikatos turizmo asociacijos duomenis, šalis 2025 metais priėmė daugiau nei 1,39 milijono lankytojų." },
    { h: "Konkreti Turkijos padėtis dantų turizme" },
    { p: "Pagal Sveikatos ministerijos duomenis, Turkija 2023 metais vien priėmė daugiau nei 400 000 dantų turistų." },
    { h: "Nuo ko iš tikrųjų priklauso \"saugumas\"" },
    { p: "Saugumas šiame kontekste nėra šalies kaip visumos savybė." },
    { h: "Ką galite patikrinti patys prieš rezervuodami" },
    { p: "Paprašykite klinikos USTYB sertifikato, patikrinkite registraciją HealthTürkiye portale." },
  ]
},
{
  slug: "tarptautinio-sveikatos-turizmo-sertifikatas-paaiskinimas",
  title: "Turkijos tarptautinio sveikatos turizmo įgaliojimo sertifikatas (USTYB) paaiškintas",
  description: "Kas iš tikrųjų yra USTYB sertifikatas, kodėl jis svarbus, ir kaip patikrinti, ar klinika tikrai jį turi.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Sertifikatas, kuris atskiria įgaliotą kliniką nuo nereguliuojamos" },
    { p: "USTYB sertifikatas išduodamas Turkijos sveikatos ministerijos specialiai sveikatos priežiūros įstaigoms, įgaliotoms gydyti tarptautinius pacientus." },
    { h: "Ką klinika iš tikrųjų turi įrodyti, kad jį gautų" },
    { p: "Klinikos, siekiančios šio įgaliojimo, turi atitikti apibrėžtus standartus." },
    { h: "Kodėl šis konkretus sertifikatas svarbesnis nei bendri rinkodaros teiginiai" },
    { p: "USTYB sertifikatas konkrečiai susietas su patikrinama registracija Sveikatos ministerijoje." },
    { h: "Ryšys su HealthTürkiye portalu" },
    { p: "Taip pat tikimasi, kad įgaliotos klinikos bus išvardytos oficialiame portale." },
    { h: "Ką iš tikrųjų paklausti klinikos prieš rezervuojant" },
    { p: "Paprašykite tiesiogiai pamatyti sertifikatą, o ne tik logotipą svetainėje." },
    { h: "Kodėl verta patikrinti šią vieną detalę" },
    { p: "Blizgi svetainė ir patrauklios kainos nepakeičia reguliacinio teisėtumo." },
  ]
},
{
  slug: "kaip-patikrinti-uzsienio-dantu-klinikos-teisetuma",
  title: "Kaip iš tikrųjų patikrinti, ar užsienio dantų klinika yra teisėta",
  description: "Praktinis kontrolinis sąrašas, patvirtinantis, kad užsienio dantų klinika yra tinkamai sertifikuota ir saugi.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Patikrinimas trunka dešimt minučių" },
    { p: "Dauguma teisėtų klinikų sveikina šiuos klausimus." },
    { h: "1. Paprašykite USTYB sertifikato" },
    { p: "Teisėta klinika parodys jums šį dokumentą tiesiogiai." },
    { h: "2. Patikrinkite registraciją HealthTürkiye portale" },
    { p: "Tai nepriklausomas būdas patikrinti klinikos teiginius." },
    { h: "3. Paklauskite, kokie konkretūs implantų prekių ženklai naudojami" },
    { p: "Konkretus, įvardytas prekės ženklas su dokumentuota gamybos istorija yra geras ženklas." },
    { h: "4. Paklauskite, ar garantija yra rašytinė" },
    { p: "Žodinė \"garantija visam gyvenimui\" reiškia mažai be rašytinio dokumento." },
    { h: "5. Ieškokite ISO sertifikatų" },
    { p: "Jie rodo, kad klinika investavo į formalius procesus." },
    { h: "6. Paklauskite, kas iš tikrųjų planuoja jūsų atvejį" },
    { p: "Jūsų gydymo planas turėtų būti sukurtas iš jūsų pačių skenavimų." },
  ]
},
{
  slug: "kas-nutinka-jei-kas-nors-negerai-po-grizimo-namo",
  title: "Kas nutinka, jei kas nors negerai po grįžimo namo?",
  description: "Tiesioginis žvilgsnis į priežiūrą po gydymo ir garantijos apsaugą pacientams, keliaujantiems į užsienį dantų gydymui.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Tai rūpestis, slypintis beveik už kiekvieno svyravimo dėl gydymo užsienyje" },
    { p: "Klinika, iš tikrųjų pritaikyta tarptautiniams pacientams, turi realius atsakymus į tai." },
    { h: "Ką nurodo tikras garantijos dokumentas" },
    { p: "Teisinga rašytinė garantija tiksliai nurodo, kas dengiama ir kiek laiko." },
    { h: "Nuotolinis stebėjimas, kol kas nors tampa skubu" },
    { p: "Daugelį problemų galima pirmiausia įvertinti nuotoliniu būdu." },
    { h: "Kada iš tikrųjų reikia grįžtamojo vizito" },
    { p: "Tikrų garantijos atvejų atveju teisėta klinika turėtų padengti patį gydymą." },
    { h: "Kuo gali ir negali padėti vietiniai odontologai jūsų šalyje" },
    { p: "Odontologas jūsų gimtojoje šalyje paprastai gali susitvarkyti su tikromis skubiomis situacijomis." },
    { h: "Sąžiningas atsakymas" },
    { p: "Realistiška implantų gijimo dauguma vyksta be incidentų." },
  ]
},
{
  slug: "kodel-milijonai-pacientu-renkasi-turkija-danti-priezziurai",
  title: "Kodėl milijonai pacientų renkasi Turkiją dantų priežiūrai",
  description: "Tikras dantų turizmo į Turkiją mastas, ir veiksniai, dėl kurių tiek daug tarptautinių pacientų renkasi keliauti ten.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Skaičiai už tendencijos yra didesni, nei tikisi dauguma žmonių" },
    { p: "Turkija 2025 metais priėmė daugiau nei 1,39 milijono sveikatos turizmo lankytojų." },
    { h: "Konkreti Turkijos padėtis pasauliniame dantų turizme" },
    { p: "Turkija per vienerius metus priėmė daugiau nei 400 000 dantų turistų." },
    { h: "Pasaulinė rinka iš tikrųjų plečiasi" },
    { p: "Pasaulinė dantų turizmo rinka 2024 metais buvo įvertinta maždaug 7,2 milijardo dolerių." },
    { h: "Kaina yra dažniausiai minima priežastis, bet retai vienintelė" },
    { p: "Be kainų skirtumo, pacientai dažnai mini greitesnį vizitų prieinamumą." },
    { h: "Infrastruktūra bręsta kartu su paklausa" },
    { p: "Vyriausybės investicijos padarė bendrą patirtį žymiai labiau struktūrizuotą." },
    { h: "Ką ši tendencija reiškia potencialiam pacientui" },
    { p: "Didelė, nusistovėjusi pramonė reiškia daugiau konkurencijos ir pasirinkimo." },
  ]
},
{
  slug: "nucleoss-implantai-ekonomiskiausias-patikimas-pasirinkimas",
  title: "NucleOSS implantai: Ekonomiškiausias patikimas pasirinkimas Turkijoje",
  description: "Kas iš tikrųjų yra NucleOSS implantai, kodėl jie yra vienas iš prieinamesnių pasirinkimų.",
  date: "2026-09-12",
  relatedTreatment: "dantu-implantai-istanbul",
  body: [
    { h: "Vietinis Turkijos prekės ženklas, ne nežinomas" },
    { p: "NucleOSS buvo įkurta 2001 metais Izmire, Turkijoje — pirmoji šalies vietinė dantų implantų gamintoja." },
    { h: "Kodėl jis kainoja prieinamiau nei importuotos sistemos" },
    { p: "Vienas NucleOSS implanto varžtas paprastai kainuojamas apie 150-200€." },
    { h: "Iš ko jis iš tikrųjų pagamintas" },
    { p: "NucleOSS implantai gaminami iš gryno titano." },
    { h: "Kur jis naudojamas už Turkijos ribų" },
    { p: "NucleOSS platinamas daugiau nei 18 šalių." },
    { h: "Ką čia nereiškia \"ekonomiškas\"" },
    { p: "Žemesnė kaina nereiškia, kad implantas nereguliuojamas — NucleOSS turi CE sertifikatą." },
    { h: "Kam iš tikrųjų tinka šis pasirinkimas" },
    { p: "Pacientams, teikiantiems prioritetą kainai, tai teisėtas vidurio kelias." },
    { h: "Sąžiningas kompromisas, kurį verta žinoti" },
    { p: "Palyginti su Šveicarijos sistemomis, NucleOSS turi trumpesnę publikacijų istoriją." },
  ]
},
{
  slug: "nucleoss-24-metai-turkijos-gamybos",
  title: "NucleOSS implantai: Ką iš tikrųjų reiškia 24 metai Turkijos gamybos",
  description: "Žvilgsnis į NucleOSS gamybos istoriją ir ką du dešimtmečiai nuolatinės gamybos sako apie patikimumą.",
  date: "2026-09-12",
  relatedTreatment: "dantu-implantai-istanbul",
  body: [
    { h: "Ilgaamžiškumas kaip gamintojas yra tikras signalas" },
    { p: "Kompanija, nuolat gaminanti nuo 2001 metų, turi 24+ metus realaus klinikinio grįžtamojo ryšio." },
    { h: "Produktų asortimentas atspindi tikrą investiciją į MTEP" },
    { p: "NucleOSS siūlo kelias implantų linijas, sukurtas skirtingoms klinikinėms situacijoms." },
    { h: "Gaminama Turkijoje, ne tik surenkama" },
    { p: "NucleOSS implantai gaminami vietoje Izmire." },
    { h: "Ką jums reiškia \"kūginiai\" vs \"tiesūs\" implantų dizainai" },
    { p: "Skirtingos implanto korpuso formos tinka skirtingoms kaulo sąlygoms." },
    { h: "Komponentų suderinamumo klausimas" },
    { p: "Plati suderinamų komponentų ekosistema reiškia dalis, prieinamas po metų." },
    { h: "Kaip tai praktiškai lyginama su naujesnio prekės ženklo pasirinkimu" },
    { p: "Prekės ženklas su trumpesne istorija tiesiog neturėjo tiek laiko įrodyti ilgalaikius rezultatus." },
    { h: "Ką tai reiškia jūsų sprendimui" },
    { p: "NucleOSS 24 metų nuolatinė istorija yra teisėtas veiksnys jos naudai." },
  ]
},
{
  slug: "porceliano-karuneles-kaina-stambulas-biudzetine-galimybe",
  title: "Porceliano karūnėlės kaina Stambule: Tradicinė, biudžetinė galimybė",
  description: "Kiek paprastai kainuoja metalo-keramikos karūnėlė, kaip ji skiriasi nuo cirkonio.",
  date: "2026-09-12",
  relatedTreatment: null,
  body: [
    { h: "Senesnis, gerai nusistovėjęs karūnėlės tipas — ne nuosmukis, kitas pasirinkimas" },
    { p: "Metalo-keramikos (PFM) karūnėlės odontologijoje naudojamos dešimtmečiais." },
    { h: "Kiek paprastai kainuoja porceliano karūnėlė" },
    { p: "Stambule PFM karūnėlė paprastai kainuoja apie 80-100€ už vienetą." },
    { h: "Kaip ji iš tikrųjų sukonstruota" },
    { p: "PFM karūnėlė turi metalinę pastruktūrę stiprumui." },
    { h: "Vienintelis sąžiningas kompromisas, kurį verta žinoti" },
    { p: "Po daugelio metų metalinis kraštas prie dantenų linijos gali tapti šiek tiek matomas." },
    { h: "Kur porceliano karūnėlės iš tikrųjų turi prasmę" },
    { p: "Užpakaliniams krūminiams dantims, kur karūnėlė retai matoma, tai protingas pasirinkimas." },
    { h: "Kur paprastai teikiama pirmenybė cirkoniui" },
    { p: "Priekiniams, matomiems dantims dauguma dabar linksta į cirkonį." },
    { h: "Ką nurodo sąžiningas pasiūlymas" },
    { p: "Teisingas pasiūlymas turėtų aiškiai nurodyti, ar tai PFM, ar cirkonis." },
  ]
},
{
  slug: "porcelianas-vs-cirkonis-karuneles-kuris-tinka-jusu-biudzetui",
  title: "Porcelianas vs cirkonis karūnėlės: Kuris iš tikrųjų tinka jūsų biudžetui ir atvejui",
  description: "Tiesioginis, praktiškas palyginimas tarp metalo-keramikos ir cirkonio karūnėlių.",
  date: "2026-09-12",
  relatedTreatment: null,
  body: [
    { h: "Du teisėti pasirinkimai, ne \"gera vs bloga\" pasirinkimas" },
    { p: "Ir metalo-keramikos, ir cirkonio karūnėlės yra nusistovėjusios, patikimos restauracijos." },
    { h: "Kainų skirtumas praktikoje" },
    { p: "PFM karūnėlės paprastai kainuoja apie 80-100€, monolitinis cirkonis — apie 120-180€." },
    { h: "Ilgaamžiškumas: arčiau nei dauguma mano" },
    { p: "Abu medžiagos tipai yra iš tikrųjų ilgaamžiai, kai tinkamai pritaikyti." },
    { h: "Išvaizda: kur pasireiškia tikras skirtumas" },
    { p: "Didžiausias cirkonio pranašumas yra tas, kad jis visiškai neturi metalo." },
    { h: "Protingas būdas galvoti apie abiejų maišymą" },
    { p: "Daugelis pacientų protingai renkasi cirkonį matomiems priekiniams dantims." },
    { h: "Kas lemia, kurią rekomenduos jūsų odontologas" },
    { p: "Jūsų odontologas atsižvelgs, kiek natūralios danties struktūros liko." },
    { h: "Klausimas, kurį verta užduoti prieš sprendimą" },
    { p: "Paklauskite savo odontologo tiesiogiai, kokią medžiagą jis rekomenduotų." },
  ]
}
];
