export const BLOG_SK = [
{
  slug: "all-on-4-alebo-all-on-6-co-je-pre-vas-vhodne",
  title: "All-on-4 alebo All-on-6: Čo je pre vás vhodné?",
  description: "All-on-4 aj All-on-6 vám poskytujú kompletný pevný oblúk zubov na implantátoch. Tu je skutočný rozdiel medzi nimi a ako stomatológ rozhoduje, čo sa hodí pre vašu čeľusť.",
  date: "2026-09-01",
  relatedTreatment: "all-on-4-5-6-implantaty-istanbul",
  body: [
    { h: "Krátka odpoveď" },
    { p: "All-on-4 a All-on-6 využívajú rovnakú základnú myšlienku — kompletný oblúk pevných zubov podopretý malým počtom implantátov umiestnených v čeľusti. Číslo v názve jednoducho udáva, koľko implantátov tento oblúk podopiera. Štyri často stačia; šesť sa používa, keď váš prípad ťaží z dodatočnej podpory." },
    { h: "Prečo by ste mohli potrebovať šesť namiesto štyroch?" },
    { p: "Rozhodnutie zvyčajne závisí od kosti. All-on-4 bolo špeciálne navrhnuté tak, aby fungovalo s kosťou, ktorú väčšina pacientov už má, pričom sa využívajú dva naklonené implantáty v zadnej časti čeľuste, aby sa predišlo oblastiam s úbytkom kosti." },
    { h: "Mení dodatočný implantát výsledok, ktorý cítite deň čo deň?" },
    { p: "Nie. Či už váš nový oblúk sedí na štyroch alebo šiestich implantátoch, hotový mostík vyzerá a cíti sa rovnako vo vašich ústach. Jediný skutočný rozdiel je pod povrchom: ako sa rozkladá skusová sila a koľko bodov kotví oblúk k vašej čeľustnej kosti." },
    { h: "Ako sa rozhodnutie skutočne robí" },
    { p: "Riadny 3D sken (zvyčajne CBCT) ukáže vášmu stomatológovi presne, koľko kosti je k dispozícii v každej oblasti vašej čeľuste, a z toho vám môže poctivo povedať, či štyri implantáty vydržia dlhodobo, alebo či by piaty či šiesty výrazne zlepšil výsledok." },
    { h: "Stručne povedané" },
    { p: "All-on-4 je štandardný, dobre overený východiskový bod pre väčšinu pacientov. All-on-6 existuje pre ľudí, ktorých kostná hustota, skusová sila alebo vzorec úbytku kosti naozaj vyžadujú dodatočnú podporu." },
  ]
},
{
  slug: "zirkon-alebo-emax-vyber-spravneho-materialu",
  title: "Zirkón alebo E-max: Výber správneho materiálu pre váš úsmev",
  description: "Zirkón a E-max sú dva materiály stojace za väčšinou moderných koruniek a fazetiek. Tu je, čo ich skutočne odlišuje.",
  date: "2026-09-01",
  relatedTreatment: "monoliticky-zirkon-korunky-istanbul",
  body: [
    { h: "Dve rôzne úlohy, dva rôzne materiály" },
    { p: "Zirkón a E-max (lítium disilikát) sú vysoko kvalitné keramiky, ale nie sú zameniteľné. Zirkón sa vyberá predovšetkým pre pevnosť, E-max predovšetkým pre estetiku." },
    { h: "Kde vyhráva zirkón" },
    { p: "Zirkón je extrémne pevný a odolný voči odlomeniu alebo prasknutiu aj pri zadných zuboch nesúcich záťaž. Monolitický zirkón odstraňuje hlavnú slabinu starších zirkónových koruniek — odlupovanie porcelánového obkladu časom." },
    { h: "Kde vyhráva E-max" },
    { p: "E-max má sklenú priehľadnosť, ktorá napodobňuje prirodzenú zubnú sklovinu bližšie ako zirkón. Pre predné zuby to robí z E-max častejšiu voľbu pre fazetky." },
    { h: "Čo je teda skutočne vhodné pre vás?" },
    { p: "V praxi mnohí pacienti skončia s kombináciou: E-max vpredu pre najlepší kozmetický výsledok, zirkón vzadu pre pevnosť. Ak klinika ponúka iba jeden materiál bez ohľadu na to, ktorý zub liečite, stojí to za druhú otázku." },
  ]
},
{
  slug: "kolko-dni-je-potrebnych-v-istanbule-na-zubnu-liecbu",
  title: "Koľko dní je potrebných v Istanbule na zubnú liečbu?",
  description: "Odpoveď úplne závisí od liečby, ktorú podstupujete. Realistický rozpis podľa procedúry.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Neexistuje jedna odpoveď — záleží na liečbe" },
    { p: "Kozmetické práce nezahŕňajúce implantáty možno zvyčajne dokončiť počas jednej návštevy. Liečba implantátmi takmer vždy vyžaduje dve." },
    { h: "Liečby na jednu návštevu (3–7 dní)" },
    { p: "Fazetky, korunky, bielenie zubov a premeny Hollywood Smile sa zvyčajne dokončia počas jednej cesty." },
    { h: "Liečby implantátmi (dve návštevy, mesiace od seba)" },
    { p: "Zubné implantáty potrebujú čas, aby sa spojili s čeľustnou kosťou (osseointegrácia). Prípady implantátov sa preto delia do dvoch návštev." },
    { h: "All-on-4 / All-on-6 konkrétne" },
    { p: "Mnohí pacienti odchádzajú z prvej návštevy už s dočasným pevným mostíkom na mieste, takže medzitým nezostávajú bez zubov." },
    { h: "Plánovanie okolo tohto" },
    { p: "Ak kombinujete liečby, dodatočná kozmetická práca sa zvyčajne plánuje okolo harmonogramu implantátov." },
  ]
},
{
  slug: "fazetky-alebo-korunky-aky-je-rozdiel",
  title: "Fazetky alebo korunky: Aký je rozdiel a čo potrebujete?",
  description: "Fazetky a korunky riešia rôzne problémy. Tu je, ako zistiť, čo sa skutočne vzťahuje na vašu situáciu.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Základný rozdiel" },
    { p: "Fazetka pokrýva iba prednú, viditeľnú plochu zuba. Korunka pokrýva celý zub, zo všetkých strán." },
    { h: "Kedy je fazetka správny nástroj" },
    { p: "Fazetky sú navrhnuté pre zuby, ktoré sú kozmeticky poškodené, ale štrukturálne zdravé, a vyžadujú menšie odstránenie zuba než korunka." },
    { h: "Kedy je korunka správny nástroj" },
    { p: "Korunky sú pre štrukturálne oslabené zuby — veľkú výplň, ktorá zlyhala, prasknutý zub, alebo zub po liečbe koreňového kanálika." },
    { h: "Môžu sa miešať v jednom úsmeve?" },
    { p: "Áno, a to je bežné. Úplná premena úsmevu často kombinuje oboje, vybrané zub po zube." },
    { h: "Čo to znamená pre vašu konzultáciu" },
    { p: "Ak klinika navrhuje korunky na zuboch bez štrukturálneho poškodenia, je rozumné sa opýtať prečo." },
  ]
},
{
  slug: "co-sa-stane-ak-nemate-dostatok-kosti-na-implantaty",
  title: "Čo sa stane, ak nemáte dostatok kosti na implantáty?",
  description: "Úbytok kosti automaticky nevylučuje implantáty. Tu je, čo stomatológ skutočne kontroluje.",
  date: "2026-09-01",
  relatedTreatment: "zdvihnutie-celustnej-dutiny-istanbul",
  body: [
    { h: "Úbytok kosti je bežný, nie diskvalifikujúci" },
    { p: "Po tom, čo zub chýba nejaký čas, čeľustná kosť v tejto oblasti prirodzene ubúda. To samo osebe nevylučuje implantáty." },
    { h: "Ako stomatológ skutočne kontroluje" },
    { p: "3D sken (CBCT) ukazuje presnú výšku a šírku dostupnej kosti v mieste implantátu." },
    { h: "Možnosť 1 — Naklonené umiestnenie implantátu" },
    { p: "Techniky ako All-on-4 využívajú kosť, ktorá je stále prítomná smerom k prednej časti čeľuste." },
    { h: "Možnosť 2 — Kostná augmentácia" },
    { p: "Kostná augmentácia pridáva materiál na obnovenie miesta pred umiestnením implantátu." },
    { h: "Možnosť 3 — Zdvihnutie čeľustnej dutiny" },
    { p: "Pre horné zadné zuby zdvihnutie čeľustnej dutiny vytvára potrebnú výšku kosti." },
    { h: "Záver" },
    { p: "„Nemám dostatok kosti“ je zriedka koncom konverzácie — je to začiatok trochu iného liečebného plánu." },
  ]
},
{
  slug: "starostlivost-po-implantacii-co-sa-deje-po-navrate-domov",
  title: "Starostlivosť po implantácii: Čo sa deje po návrate domov?",
  description: "Získanie implantátov v zahraničí neznamená, že ste po pristátí doma sami.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Starostlivosť po liečbe by nemala končiť na letisku" },
    { p: "Správne riadený liečebný plán zahŕňa jasnú štruktúru pre následnú starostlivosť, bez ohľadu na to, v ktorej krajine sa nachádzate." },
    { h: "Ako vyzerá normálne hojenie" },
    { p: "Mierna bolesť, opuch a citlivosť v dňoch po chirurgii implantátu sú normálne a odznejú počas prvého až druhého týždňa." },
    { h: "Čo zahŕňa skutočný plán starostlivosti po liečbe" },
    { p: "Písomná záruka, priamy kontakt s vaším stomatológom a jasná cesta pre vzdialené konzultácie." },
    { h: "Čo sa opýtať pred záväzkom" },
    { p: "Čo sa stane, ak implantát nerastie, koho kontaktovať, a či je záruka písomná." },
    { h: "Realistický obrázok" },
    { p: "Väčšina hojenia implantátov prebieha bez komplikácií, ale vedieť, že záruka existuje, je dôležité." },
  ]
},
{
  slug: "vyzaduju-fazetky-emax-obrusenie-zubov",
  title: "Vyžadujú fazetky E-max obrúsenie zubov?",
  description: "Jedna z najčastejších obáv ohľadom fazetiek. Čo skutočne znamená „minimálna príprava“.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Poctivá odpoveď: záleží na vašom východiskovom bode" },
    { p: "Fazetky E-max sú často popisované ako „minimálna príprava“ — materiál je dostatočne pevný aj pri veľmi tenkom vyhotovení." },
    { h: "Kedy je potrebná veľmi malá alebo žiadna redukcia" },
    { p: "Ak sú vaše zuby už dobre zarovnané, tenká fazetka E-max sa často dá nalepiť s malým odstránením skloviny." },
    { h: "Kedy je skutočne nutná väčšia príprava" },
    { p: "Ak je zub výrazne nevyrovnaný alebo silne sfarbený, je nutná určitá redukcia skloviny." },
    { h: "Prečo by o tom malo byť rozhodnuté pred cestou" },
    { p: "Sken digitálneho návrhu úsmevu skutočne odpovedá na túto otázku pre vaše konkrétne zuby." },
    { h: "Čo sa opýtať" },
    { p: "Opýtajte sa priamo: „koľko z môjho prirodzeného zuba budete musieť odstrániť pre tento návrh?“" },
  ]
},
{
  slug: "ako-dlho-trva-vyroba-zirkonovej-korunky",
  title: "Ako dlho trvá výroba zirkónovej korunky?",
  description: "Od vašej prvej návštevy až po dokončenú korunku — realistický harmonogram pre zirkónové korunky.",
  date: "2026-09-02",
  relatedTreatment: "monoliticky-zirkon-korunky-istanbul",
  body: [
    { h: "Krátka verzia" },
    { p: "Jedna zirkónová korunka zvyčajne trvá pár dní na návrh, frézovanie a dokončenie — väčšina prípadov sa dokončí počas jednej cesty tri až päť dní." },
    { h: "Čo sa skutočne deje počas tohto času" },
    { p: "Súbor sa odošle na frézovanie, kde stroj vyreže korunku z pevného zirkónového bloku, potom sa farbí a glazuje." },
    { h: "Prečo záleží na internom frézovaní" },
    { p: "Kliniky s vlastným laboratóriom môžu dokončiť korunku za deň alebo dva, namiesto čakania na externé laboratórium." },
    { h: "Kedy to trvá dlhšie" },
    { p: "Viac koruniek alebo úplná premena úsmevu prirodzene zaberá viac času vašej návštevy." },
  ]
},
{
  slug: "co-skutocne-zahrna-liecba-navrhu-usmevu",
  title: "Čo skutočne zahŕňa liečba návrhu úsmevu?",
  description: "„Návrh úsmevu“ a „Digitálny dizajn úsmevu“ sa používajú voľne. Tu je, čo je skutočne súčasťou procesu.",
  date: "2026-09-02",
  relatedTreatment: "digitalny-dizajn-usmevu-istanbul",
  body: [
    { h: "Je to plánovací proces, nie jedna procedúra" },
    { p: "Digitálny dizajn úsmevu je plánovacia fáza, ktorá rozhoduje, aké liečby budú skutočne použité na dosiahnutie vášho cieľa." },
    { h: "Krok 1 — Analýza vašej tváre" },
    { p: "Fotografie a video vášho úsmevu, línie pier a proporcií tváre sa berú do úvahy." },
    { h: "Krok 2 — 3D skenovanie a digitálny náhľad" },
    { p: "Intraorálny sken vytvorí 3D model vašich zubov, na ktorý sa premietne navrhovaný nový úsmev." },
    { h: "Krok 3 — Určenie, aké liečby sú skutočne potrebné" },
    { p: "Toto sa rozhoduje zub po zube, nie ako jeden všeobecný balík." },
    { h: "Krok 4 — Fyzická makreta v ústach" },
    { p: "Mnohé kliniky vám môžu ukázať dočasnú verziu návrhu priamo na vašich zuboch." },
    { h: "Prečo to záleží" },
    { p: "Ak klinika ponúka „návrh úsmevu“ bez skenovania, pravdepodobne dostávate štandardný balík pod módnejším názvom." },
  ]
},
{
  slug: "hollywood-smile-verzus-fazetky-skutocny-rozdiel",
  title: "Hollywood Smile verzus fazetky: Aký je skutočný rozdiel?",
  description: "„Hollywood Smile“ nie je samostatný materiál ani procedúra odlišná od fazetiek.",
  date: "2026-09-02",
  relatedTreatment: "hollywood-smile-istanbul",
  body: [
    { h: "Hollywood Smile je výsledok, nie materiál" },
    { p: "„Fazetky“ opisujú konkrétnu náhradu. „Hollywood Smile“ opisuje širší kozmetický cieľ dosiahnutý kombináciou viacerých techník." },
    { h: "Takže Hollywood Smile môže používať fazetky, alebo nemusí" },
    { p: "Výsledok môže byť dosiahnutý fazetkami, korunkami, alebo kombináciou oboch, podľa stavu vašich zubov." },
    { h: "Prečo na tomto rozlíšení záleží" },
    { p: "Pri porovnávaní ponúk sa opýtajte konkrétne, aké materiály a koľko zubov je zahrnutých." },
    { h: "Čo skutočne určuje správnu voľbu" },
    { p: "Toto sa vracia k stavu konkrétneho zuba — potrebe štrukturálnej podpory alebo len kozmetickej úpravy." },
  ]
},
{
  slug: "invisalign-verzus-tradicne-zubne-rovnatka-co-zvolit",
  title: "Invisalign verzus tradičné zubné rovnátka: Čo zvoliť?",
  description: "Priehľadné dlahy a kovové rovnátka obe narovnávajú zuby, ale hodia sa pre rôzne situácie.",
  date: "2026-09-02",
  relatedTreatment: "invisalign-priehladne-rovnatka-istanbul",
  body: [
    { h: "Obe fungujú — otázkou je vhodnosť" },
    { p: "Priehľadné dlahy a tradičné rovnátka obe posúvajú zuby pomocou kontrolovaného tlaku." },
    { h: "Kde dobre fungujú priehľadné dlahy" },
    { p: "Mierne až stredne ťažké natesnanie a jednoduché problémy so skusom sú zvyčajne vhodné pre dlahy." },
    { h: "Kde sú tradičné rovnátka stále lepšie" },
    { p: "Zložitejšie pohyby sa lepšie riešia fixnými rovnátkami." },
    { h: "Faktor disciplíny" },
    { p: "Dlahy fungujú iba vtedy, ak sú nosené 20–22 hodín denne." },
    { h: "Ako sa rozhodnutie skutočne robí" },
    { p: "3D sken a vyhodnotenie skusu ukážu, aké pohyby váš prípad skutočne potrebuje." },
  ]
},
{
  slug: "zubny-mostik-alebo-implantat-ako-si-vybrat",
  title: "Zubný mostík alebo implantát: Ako si vybrať",
  description: "Oba nahrádzajú chýbajúci zub, ale fungujú veľmi odlišne.",
  date: "2026-09-02",
  relatedTreatment: "zubny-mostik-istanbul",
  body: [
    { h: "Základný rozdiel" },
    { p: "Implantát priamo nahrádza chýbajúci koreň zuba. Mostík nahrádza iba viditeľný zub, spolieha sa na susedné zuby." },
    { h: "Prečo je mostík často rýchlejší" },
    { p: "Mostík nevyžaduje chirurgický zákrok, takže sa zvyčajne dokončí počas jednej návštevy." },
    { h: "Prečo je implantát silnejšou dlhodobou voľbou" },
    { p: "Implantát nezávisí od susedných zubov a stimuluje čeľustnú kosť." },
    { h: "Rozhodujúci faktor: stav susedných zubov" },
    { p: "Ak zuby vedľa medzery už potrebujú korunky, mostík je efektívny." },
    { h: "Spravodlivá otázka" },
    { p: "Ak klinika odporúča mostík, opýtajte sa, či je to kvôli stavu susedných zubov, alebo len kvôli cene." },
  ]
},
{
  slug: "co-sa-deje-pocas-liecby-korenoveho-kanalika-krok-za-krokom",
  title: "Čo sa deje počas liečby koreňového kanálika, krok za krokom",
  description: "Jasný, krokový popis toho, čo sa skutočne deje počas liečby koreňového kanálika.",
  date: "2026-09-02",
  relatedTreatment: "liecba-korenoveho-kanalika-istanbul",
  body: [
    { h: "Prečo má táto procedúra horšiu povesť ako skúsenosť" },
    { p: "Nepohodlie zvyčajne pochádza zo samotnej infekcie, nie z procedúry, ktorá je porovnateľná s výplňou." },
    { h: "Krok 1 — Diagnóza a röntgen" },
    { p: "Röntgen potvrdzuje rozsah infekcie a koľko kanálikov má koreň zuba." },
    { h: "Krok 2 — Lokálna anestézia" },
    { p: "Zub a okolitá oblasť sú znecitlivené rovnakým spôsobom ako pri výplni." },
    { h: "Krok 3 — Odstránenie infikovaného tkaniva" },
    { p: "Infikovaná dreň je starostlivo odstránená z každého kanálika." },
    { h: "Krok 4 — Čistenie a dezinfekcia" },
    { p: "Kanálik je vyčistený, tvarovaný a dezinfikovaný." },
    { h: "Krok 5 — Uzavretie zuba" },
    { p: "Kanálik sa naplní biokompatibilným materiálom." },
    { h: "Krok 6 — Zvyčajne ochranná korunka" },
    { p: "Korunka chráni zub pred prasknutím po liečbe." },
    { h: "Ako sa skutočne cíti zotavenie" },
    { p: "Mierna bolesť je zvládateľná štandardnými analgetikami." },
  ]
},

{
  slug: "znamky-ze-mozno-potrebujete-gingivektomiu",
  title: "Znamky, že možno potrebujete gingivektómiu",
  description: "Gingivektómia nie je len pre „ďasnový úsmev“ — tu sú praktické znaky, že úprava ďasien skutočne stojí za prejednanie so stomatológom.",
  date: "2026-09-02",
  relatedTreatment: "gingivektomia-istanbul",
  body: [
    { h: "Ide o viac než len vzhľad" },
    { p: "Gingivektómia je často spomínaná iba v kozmetickom kontexte, ale nadmerné alebo nerovnomerné ďasnové tkanivo môže byť aj skutočným problémom ústneho zdravia." },
    { h: "Znak 1 — Pri úsmeve ukazujete znateľne viac ďasna než zuba" },
    { p: "„Ďasnový úsmev“, kedy je pri prirodzenom úsmeve viditeľný široký pruh ďasnového tkaniva nad zubami, je najčastejšie rozpoznaným dôvodom, prečo ľudia zvažujú gingivektómiu." },
    { h: "Znak 2 — Vaša línia ďasien je nerovnomerná" },
    { p: "Nerovnomerné úrovne od jedného predného zuba k druhému môžu spôsobiť, že inak dobre tvarované zuby vyzerajú nesúrodo." },
    { h: "Znak 3 — Nadmerné ďasnové tkanivo sťažuje čistenie zubov" },
    { p: "Tkanivo, ktoré sa prekrýva okolo zubov, môže zachytávať plak spôsobom, ktorý je ťažké efektívne čistiť." },
    { h: "Znak 4 — Plánujete fazetky a vaše úrovne ďasien sú nerovnomerné" },
    { p: "Hodnotenie ďasien je často súčasťou riadneho plánu digitálneho dizajnu úsmevu." },
    { h: "Čo skutočne robiť" },
    { p: "Ak vám niektorý z týchto znakov znie povedomo, je to rozumná vec, ktorú stojí za to nadniesť so svojím stomatológom." },
  ]
},
{
  slug: "otazky-pred-vyberom-kliniky-v-zahranici",
  title: "Otázky, ktoré je treba položiť pred výberom zubnej kliniky v zahraničí",
  description: "Praktický kontrolný zoznam toho, čo sa skutočne opýtať pred rezerváciou zubnej liečby v inej krajine.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Porovnávanie cien samo osebe vám veľa nepovie" },
    { p: "Dve kliniky môžu ponúkať rovnakú cenu za „All-on-4“ a myslieť tým naozaj rôzne veci — rôzne značky implantátov, rôzne záručné podmienky." },
    { h: "1. Akú konkrétnu značku implantátu používate?" },
    { p: "Skutočné, zavedené značky ako Straumann alebo Nobel Biocare majú za sebou sledovateľnú výrobnú históriu." },
    { h: "2. Je záruka písomná a čo presne kryje?" },
    { p: "„Doživotná záruka“ by mala špecifikovať, čo je zahrnuté a na ako dlho." },
    { h: "3. Kto vykonáva plánovanie prípadu?" },
    { p: "Váš liečebný plán by mal byť zostavený z vašich vlastných 3D skenov, preskúmaných stomatológom, ktorý vás bude liečiť." },
    { h: "4. Čo sa stane, ak niečo potrebuje pozornosť po návrate domov?" },
    { p: "Klinika by mala mať jasnú odpoveď ohľadom vzdialených konzultácií." },
    { h: "5. Je klinika oficiálne autorizovaná pre medzinárodných pacientov?" },
    { p: "Konkrétne v Turecku by kliniky mali mať platné oprávnenie pre medzinárodný zdravotný cestovný ruch." },
    { h: "6. Čo je skutočne zahrnuté v uvedenej cene?" },
    { p: "Opýtajte sa, či ponuka zahŕňa konzultáciu, skeny a následné návštevy." },
  ]
},
{
  slug: "ake-certifikacie-by-mala-mat-zubna-klinika-v-zahranici",
  title: "Aké certifikácie by mala skutočne mať zubná klinika v zahraničí?",
  description: "Certifikáty je ľahké vystaviť a ťažké overiť iba z webovej stránky.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Nie všetky certifikáty majú rovnakú váhu" },
    { p: "Webové stránky klinik často zobrazujú rôzne odznaky, ale tie sa pohybujú od skutočne významných autorizácií po obecné certifikáty." },
    { h: "Oprávnenie pre medzinárodný zdravotný cestovný ruch" },
    { p: "V Turecku by kliniky liečiace medzinárodných pacientov mali mať toto oprávnenie od ministerstva zdravotníctva." },
    { h: "ISO certifikácie" },
    { p: "Toto sú obecné štandardy riadenia kvality, nie špecifické pre stomatológiu." },
    { h: "Certifikácie výrobcov implantátov" },
    { p: "Niektoré kliniky zobrazujú certifikáty potvrdzujúce, že sú autorizovaným používateľom konkrétnej značky implantátu." },
    { h: "Čo s touto informáciou skutočne robiť" },
    { p: "Opýtajte sa kliniky priamo na autorizačné číslo a overte ho v príslušnom registri." },
  ]
},
{
  slug: "ako-dlho-skutocne-vydrzia-zirkonove-korunky",
  title: "Ako dlho skutočne vydržia zirkónové korunky?",
  description: "Realistický pohľad na životnosť zirkónových koruniek, čo ju skutočne skracuje.",
  date: "2026-09-02",
  relatedTreatment: "monoliticky-zirkon-korunky-istanbul",
  body: [
    { h: "Obecný rozsah" },
    { p: "Dobre vyrobené zirkónové korunky zvyčajne vydržia 10 až 15 rokov alebo dlhšie pri rozumnej starostlivosti." },
    { h: "Prečo monolitický zirkón vydrží dlhšie" },
    { p: "Staršie zirkónové korunky mali samostatnú vrstvu porcelánu, ktorá bola slabým miestom náchylným na odlupovanie." },
    { h: "Čo skutočne skracuje životnosť korunky" },
    { p: "Neliečené škrípanie zubami vyvíja nadmernú silu na korunku a okolité zuby." },
    { h: "Čo môžete urobiť, aby vydržala dlhšie" },
    { p: "Normálne kefovanie, nočný chránič a pravidelné zubné prehliadky sú hlavnými praktickými faktormi." },
    { h: "Keď „zlyhalo“ sa v skutočnosti netýka korunky" },
    { p: "Ak musí byť korunka po niekoľkých rokoch vymenená, často je to kaz pod zubom, nie zlyhanie samotného zirkónu." },
  ]
},
{
  slug: "monoliticky-verzus-vrstveny-zirkon-aky-je-rozdiel",
  title: "Monolitický verzus vrstvený zirkón: Aký je rozdiel?",
  description: "Obe sa nazývajú „zirkónové korunky“, ale konštrukcia je skutočne odlišná.",
  date: "2026-09-02",
  relatedTreatment: "monoliticky-zirkon-korunky-istanbul",
  body: [
    { h: "Rovnaký základný materiál, odlišná konštrukcia" },
    { p: "Oba typy používajú oxid zirkoničitý, ale spôsob ich konštrukcie je skutočne odlišný." },
    { h: "Vrstvený zirkón" },
    { p: "Vrstvená korunka má zirkónové jadro so samostatnou vrstvou porcelánu pre živší vzhľad." },
    { h: "Monolitický zirkón" },
    { p: "Monolitická korunka je celá frézovaná z jedného zirkónového bloku, bez samostatnej vrstvy porcelánu." },
    { h: "Kde sa každý typicky používa" },
    { p: "Monolitický zirkón je preferovaný pre zadné zuby, vrstvený sa niekedy volí pre predné zuby." },
    { h: "Záver" },
    { p: "Ak je odolnosť proti odlomeniu vašou hlavnou prioritou, monolitický zirkón je obecne bezpečnejšou voľbou." },
  ]
},
{
  slug: "mozno-kombinovat-implantaty-a-fazetky-v-jednej-ceste",
  title: "Možno kombinovať implantáty a fazetky v jednej ceste?",
  description: "Kombinácia liečeb je bežná, ale harmonogram hojenia implantátu mení, ako je to plánované.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Áno, ale harmonogram implantátu udáva tempo" },
    { p: "Implantáty potrebujú niekoľko mesiacov, aby sa spojili s čeľustnou kosťou, takže kombinovaný plán sa vystavia okolo tohto harmonogramu." },
    { h: "Ako sa to obvykle plánuje" },
    { p: "Počas prvej návštevy sú umiestnené implantáty a práca s fazetkami na nesúvisiacich zuboch môže prebehnúť súčasne." },
    { h: "Prečo je dôležité načasovanie bielenia" },
    { p: "Bielenie by malo prebehnúť pred výrobou fazetiek alebo koruniek, nie po." },
    { h: "Čo by vám mal povedať kombinovaný plán" },
    { p: "Riadny plán podrobne popisuje, čo sa deje v každý deň každej návštevy." },
    { h: "Praktická výhoda kombinovania" },
    { p: "Kombinácia liečeb skutočne znižuje celkové cestovanie." },
  ]
},
{
  slug: "zvladanie-strachu-zo-zubara-pocas-cesty-na-liecbu",
  title: "Zvládanie strachu zo zubára počas cesty na liečbu",
  description: "Strach zo zubára nezmizne len preto, že cestujete na liečbu.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Je to bežná obava, nie neobvyklá" },
    { p: "Strach zo zubára je extrémne rozšírený a cestovanie do zahraničia môže pridať ďalšiu vrstvu stresu." },
    { h: "Skutočne dostupné možnosti sedácie" },
    { p: "Väčšina kliník ponúka možnosti nad rámec lokálnej anestézie pre úzkostných pacientov." },
    { h: "Komunikácia záleží viac, než ľudia očakávajú" },
    { p: "Klinika s oddanými viacjazyčnými koordinátormi robí skutočný rozdiel." },
    { h: "Plánovanie pomáha viac, než si väčšina ľudí uvedomuje" },
    { p: "Znalosť harmonogramu vopred znižuje neistotu, ktorá živí úzkosť." },
    { h: "Je rozumné to povedať vopred" },
    { p: "Priame oznámenie koordinátorovi, že prežívate strach, im dáva šancu naplánovať okolo toho." },
  ]
},
{
  slug: "co-pripravit-pred-zubnou-liecbou-v-zahranici",
  title: "Čo pripraviť pred zubnou liečbou v zahraničí",
  description: "Praktický kontrolný zoznam pred cestou — čo mať pripravené, priniesť a potvrdiť pred letom.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Predtým, než čokoľvek rezervujete" },
    { p: "Získajte písomný liečebný plán založený na vašich vlastných fotografiách alebo skenoch." },
    { h: "Lekárske informácie, ktoré mať pripravené" },
    { p: "Zoznam liekov, alergií a relevantných zdravotných stavov by mal byť zdieľaný pred cestovaním." },
    { h: "Existujúce zubné záznamy" },
    { p: "Nedávne röntgeny alebo poznámky od vášho bežného stomatológa môžu urýchliť plánovanie." },
    { h: "Praktická logistika cestovania" },
    { p: "Konkrétne pre prípady implantátov potvrďte oba termíny návštev vopred." },
    { h: "Otázky, na ktoré by malo byť odpovedané pred letom" },
    { p: "Celkový počet potrebných návštev a písomné záručné podmienky by mali byť vyriešené vopred." },
    { h: "Čo skutočne zabaliť" },
    { p: "Zoznam liekov, pohodlné oblečenie a pre procedúry so sedáciou zabezpečenie sprievodu." },
  ]
},
{
  slug: "korunka-alebo-vyplna-aky-je-rozdiel",
  title: "Korunka alebo výplň: Aký je rozdiel a kedy potrebujete ktorú?",
  description: "Obe opravujú poškodený zub, ale na veľmi odlišných úrovniach poškodenia.",
  date: "2026-09-03",
  relatedTreatment: "monoliticky-zirkon-korunky-istanbul",
  body: [
    { h: "Všetko sa odvíja od toho, koľko zdravého zuba zostáva" },
    { p: "Výplň opravuje malú až stredne veľkú oblasť poškodenia, korunka pokrýva celý viditeľný zub." },
    { h: "Kedy výplň stačí" },
    { p: "Malé až stredné kazy, zachytené rozumne skoro, sú obvykle dobre riešené výplňou." },
    { h: "Kedy výplň nestačí" },
    { p: "Ak je kaz rozsiahly alebo je zub prasknutý, korunka poskytuje úplné pokrytie." },
    { h: "Prečo umiestnenie výplne tam, kde je potrebná korunka, nevydrží" },
    { p: "Príliš veľká výplň má väčšiu pravdepodobnosť prasknúť pod normálnym zaťažením." },
    { h: "Poctivá odpoveď od dobrého stomatológa" },
    { p: "Stomatológ, ktorý sa pozerá priamo na röntgen a samotný zub, vám povie, čo potrebujete." },
  ]
},
{
  slug: "cena-all-on-4-co-je-skutocne-zahrnute",
  title: "Cena All-on-4: Čo je skutočne zahrnuté v cene?",
  description: "Ponuky All-on-4 môžu vyzerať veľmi odlišne medzi klinikami z dôvodov, ktoré nemajú nič spoločné s kvalitou.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-implantaty-istanbul",
  body: [
    { h: "Prečo rovnaká procedúra dostáva veľmi odlišné ponuky" },
    { p: "Rozdiel sa často odvíja od toho, čo je skutočne zahrnuté, nie od toho, že jedna je lepšou ponukou." },
    { h: "Značka a kvalita implantátu" },
    { p: "Zavedené, klinicky overené značky implantátov obvykle stoja viac než menej známe alternatívy." },
    { h: "Čo je zahrnuté v uvedenej cene" },
    { p: "Opýtajte sa, či ponuka zahŕňa úvodnú konzultáciu, 3D sken, dočasný a finálny most." },
    { h: "Kostná augmentácia alebo zdvihnutie dutiny" },
    { p: "Ak váš prípad môže vyžadovať dodatočnú prácu s kosťou, získajte cenu založenú na vašom skutočnom sken." },
    { h: "Podmienky sledovania a záruky" },
    { p: "Skontrolujte, či sú kontroly po starostlivosti a záručná doba zahrnuté v cene." },
    { h: "Jedna otázka, ktorá objasní väčšinu" },
    { p: "Opýtajte sa priamo: „čo by zmenilo túto konečnú cenu?“" },
  ]
},
{
  slug: "mozno-zaviest-zubne-implantaty-ak-fajcite",
  title: "Možno zaviesť zubné implantáty, ak fajčíte?",
  description: "Fajčenie automaticky nevylučuje implantáty, ale je to skutočný faktor, ktorý stomatológovia berú vážne.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-implantaty-istanbul",
  body: [
    { h: "Fajčenie je rizikový faktor, nie automatická diskvalifikácia" },
    { p: "Mnohí fajčiari majú úspešné, dlhotrvajúce zubné implantáty. Ale fajčenie znižuje prietok krvi do ďasien a čeľustnej kosti." },
    { h: "Prečo záleží na dobe hojenia" },
    { p: "Osseointegrácia závisí od zdravého krvného zásobovania tejto oblasti." },
    { h: "Čo skutočne odporúča väčšina stomatológov" },
    { p: "Mnohé kliniky odporúčajú prestať fajčiť na dobu pred a po chirurgii implantátu." },
    { h: "Byť úprimný ohľadom toho záleží" },
    { p: "Oznámenie stomatológovi, že fajčíte, mu umožňuje správne plánovať." },
    { h: "Záver" },
    { p: "Fajčenie robí liečbu implantátmi trochu rizikovejšou, nie nemožnou." },
  ]
},
{
  slug: "co-je-osseointegracia-a-preco-zalezi-na-implantatoch",
  title: "Čo je osseointegrácia a prečo záleží na implantátoch?",
  description: "Termín stojaci za tým, prečo liečba implantátmi trvá mesiace, nie dni.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-implantaty-istanbul",
  body: [
    { h: "Slovo, ktoré vysvetľuje harmonogram implantátu na dve návštevy" },
    { p: "Osseointegrácia je proces, ktorým sa titánový implantát fyzicky spája s okolitou čeľustnou kosťou." },
    { h: "Prečo konkrétne titán" },
    { p: "Titán má neobvyklú vlastnosť: živé kostné bunky rastú priamo na jeho povrchu." },
    { h: "Ako dlho to trvá" },
    { p: "Osseointegrácia zvyčajne trvá tri až šesť mesiacov, v závislosti od čeľuste a kvality kosti." },
    { h: "Čo sa stane, ak je tento krok uponáhľaný" },
    { p: "Zaťaženie implantátu pred dokončením osseointegrácie riskuje, že sa nespojí správne." },
    { h: "Prečo na tom záleží pri porovnávaní kliník" },
    { p: "Klinika sľubujúca trvalú náhradu v jednej krátkej návšteve buď pracuje s jednoduchým prípadom, alebo preskakuje dôležitý krok." },
  ]
},
{
  slug: "kolko-stoja-zubne-implantaty-v-turecku",
  title: "Koľko stoja zubné implantáty v Turecku?",
  description: "Realistický prehľad nákladov na zubné implantáty v Turecku, prečo sa ceny líšia medzi klinikami a čo by ste mali skutočne porovnať pred rozhodnutím.",
  date: "2026-09-10",
  relatedTreatment: "zubne-implantaty-istanbul",
  body: [
    { h: "Neexistuje jedno číslo, a akákoľvek klinika, ktorá udáva cenu pred videním vášho prípadu, hádá" },
    { p: "Cena implantátu závisí od použitej značky implantátu, potreby kostného štepu a počtu potrebných implantátov." },
    { h: "Značka implantátu je najväčším faktorom ceny" },
    { p: "Kliniky zvyčajne ponúkajú viac ako jeden implantačný systém a cenový rozdiel medzi nimi je skutočný — často 30-40% medzi ekonomickým a prémiovým systémom." },
    { h: "Koľko obvykle stojí jeden implantát" },
    { p: "Za jeden zubný implantát (iba samotná skrutka, bez korunky navrchu) sa ceny v istanbulských klinikách zvyčajne pohybujú od ~300€ do 450€+ za prémiové systémy." },
    { h: "Prečo je korunka samostatnou položkou" },
    { p: "Implantát nahrádza koreň; korunka nahrádza viditeľný zub. Kompletná ponuka \"implantát + korunka\" by mala obe jasne uvádzať." },
    { h: "Čo skutočne mení celkovú sumu" },
    { p: "Kostný štep alebo zdvihnutie čeľustnej dutiny, ak to váš prípad vyžaduje, sa pridáva k celkovej sume." },
    { h: "Ako získať reálne číslo pre váš prípad" },
    { p: "Pošlite nedávny panoramatický röntgen, ak ho máte, alebo naplánujte 3D sken počas konzultácie." },
  ]
},
{
  slug: "cena-all-on-4-turecko-vs-uk-usa",
  title: "Cena All-on-4 v Turecku vs UK a USA: Čo skutočne porovnávate",
  description: "Prečo sa ponuky All-on-4 tak líšia medzi krajinami a čo skutočne spôsobuje rozdiel okrem nákladov na prácu.",
  date: "2026-09-10",
  relatedTreatment: "all-on-4-5-6-implantaty-istanbul",
  body: [
    { h: "Rozdiel je skutočný, ale nie je to len \"lacnejšia práca\"" },
    { p: "All-on-4 v Turecku sa zvyčajne ponúka za približne tretinu až polovicu typickej ceny v UK alebo USA." },
    { h: "Čo zvyčajne zahŕňa prípad plného oblúka v Turecku" },
    { p: "Kompletný pevný oblúk na štyroch implantátoch, vrátane operácie, stojí zvyčajne od ~2900€ za oblúk s dostupnejším systémom do 3400€ s prémiovým." },
    { h: "Prečo All-on-5 alebo All-on-6 stojí viac" },
    { p: "Pridanie piateho alebo šiesteho implantátu zvyšuje celkovú sumu o približne 300-450€ za ďalší implantát." },
    { h: "Čo môžu zahŕňať ceny v UK a USA, čo ponuka z Turecka nemá" },
    { p: "Porovnajte, čo je skutočne zahrnuté v každej ponuke: zahŕňa cena v UK kontrolnú návštevu?" },
    { h: "Skutočné zváženie nákladov, ktoré väčšina ľudí prehliada" },
    { p: "Aj so započítaním letov a ubytovania zostáva celková suma za prípad plného oblúka v zahraničí zvyčajne výrazne nižšia." },
    { h: "Čo sa opýtať pred porovnaním dvoch ponúk" },
    { p: "Opýtajte sa každej kliniky, aká značka implantátu sa používa a čo skutočne kryje záruka." },
  ]
},
{
  slug: "cena-fazetiek-laminatu-istanbul",
  title: "Cena fazetiek z laminátu v Istanbule: Čo je skutočne zahrnuté",
  description: "Jasný pohľad na to, čo určuje cenu laminátových fazetiek v Istanbule a čo by mala obsahovať správna ponuka.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Cena je zvyčajne uvedená za zub, nie za úsmev" },
    { p: "Cena laminátových fazetiek je takmer vždy za jednotlivý zub, takže celková suma závisí úplne od počtu zubov zahrnutých v dizajne vášho úsmevu." },
    { h: "Koľko obvykle stojí jedna fazetka" },
    { p: "Cena za zub pre laminátové fazetky v Istanbule sa zvyčajne pohybuje v rozmedzí približne 300-400€." },
    { h: "Prečo materiál ovplyvňuje cenu a výsledok" },
    { p: "Tenké porcelánové laminátky vyžadujú presnú, minimálnu prípravu zubu a skúseného keramika." },
    { h: "Čo by malo byť zahrnuté v ponúkanej cene" },
    { p: "Správna ponuka fazetiek by mala zahŕňať konzultáciu digitálneho dizajnu úsmevu a cementáciu." },
    { h: "Fáza dočasných fazetiek" },
    { p: "Medzi pripravenými zubami a nasadením finálnych fazetiek nosíte zvyčajne dočasné fazetky niekoľko dní." },
    { h: "Prečo najlacnejšia ponuka nie je automaticky najlepšou hodnotou" },
    { p: "Výrazne nižšia cena za zub ako všetko ostatné, čo vidíte, si zaslúži priamy dotaz." },
  ]
},
{
  slug: "cena-hollywood-smile-co-urcuje-cenu",
  title: "Cena Hollywood Smile: Čo určuje konečnú cenu",
  description: "Cena Hollywood Smile sa líši viac než takmer akákoľvek iná liečba, pretože nejde o jeden pevný postup.",
  date: "2026-09-10",
  relatedTreatment: "hollywood-smile-istanbul",
  body: [
    { h: "\"Hollywood Smile\" popisuje výsledok, nie pevný cenník" },
    { p: "Pretože Hollywood Smile možno dosiahnuť fazetkami, korunkami alebo kombináciou oboch, dve kliniky s veľmi odlišnými celkovými sumami môžu v skutočnosti oceňovať rôzne liečebné plány." },
    { h: "Počet zahrnutých zubov je najväčším jednotlivým faktorom" },
    { p: "Kompletná transformácia Hollywood Smile zvyčajne pokrýva horných viditeľných 16-20 zubov." },
    { h: "Fazetky vs korunky menia cenu za zub" },
    { p: "Laminátové fazetky a plné zirkónové korunky sú oceňované odlišne." },
    { h: "Čo pridáva kompletný digitálny dizajn úsmevu" },
    { p: "Správny plán Hollywood Smile začína 3D digitálnym dizajnom úsmevu." },
    { h: "Prečo sa dva \"balíčky Hollywood Smile\" môžu líšiť o tisíce eur" },
    { p: "Najväčšie výkyvy pochádzajú z počtu zahrnutých zubov a triedy materiálu." },
    { h: "Otázka, ktorú stojí za to položiť priamo" },
    { p: "Opýtajte sa presne, koľko zubov je zahrnutých v ponúkanej cene." },
  ]
},
{
  slug: "cena-zirkonovej-korunky-lacnejsie-neznamena-vzdy-lepsie",
  title: "Cena zirkónovej korunky: Lacnejšie neznamená vždy lepšie",
  description: "Čo skutočne ovplyvňuje cenu zirkónovej korunky a prečo najnižšia ponuka môže niekedy stáť viac v dlhodobom horizonte.",
  date: "2026-09-10",
  relatedTreatment: "monoliticky-zirkon-korunky-istanbul",
  body: [
    { h: "Základná cena je zvyčajne skromná — hromadia sa práve príplatky" },
    { p: "Jedna zirkónová korunka sama o sebe je jednou z dostupnejších reštauratívnych možností — zvyčajne 120-180€ za jednotku v Istanbule." },
    { h: "Monolitický vs vrstvený zirkón" },
    { p: "Monolitický zirkónium, frézovaný z jedného pevného bloku, má tendenciu byť odolnejší proti odštiepeniu." },
    { h: "Čo pridáva titánová základňa" },
    { p: "Špeciálne pre korunky na implantátoch pridáva titánová základňa významnú sumu k nákladom." },
    { h: "Prečo si oveľa lacnejšia ponuka zaslúži priamy dotaz" },
    { p: "Opýtajte sa konkrétne, či ide o monolitický alebo vrstvený zirkón, a aká záručná doba je zahrnutá." },
    { h: "Ako počet korunok rýchlo mení celkovú sumu" },
    { p: "Pretože oceňovanie je za jednotku, získajte cenu za jednotku a vynásobte si ju sami." },
    { h: "Čo skutočne špecifikuje spravodlivá ponuka" },
    { p: "Dôveryhodná ponuka uvádza cenu za korunku, konkrétny typ zirkónu a záručnú dobu." },
  ]
},
{
  slug: "cena-liecby-korenoveho-kanalika-turecko",
  title: "Cena liečby koreňového kanálika v Turecku: Čo očakávať",
  description: "Priamy pohľad na to, koľko obvykle stojí liečba koreňového kanálika v Turecku, a čo ďalšie by ste mohli potrebovať.",
  date: "2026-09-10",
  relatedTreatment: "liecba-korenoveho-kanalika-istanbul",
  body: [
    { h: "Samotná liečba koreňového kanálika je jednou z dostupnejších procedúr" },
    { p: "Samotná liečba koreňového kanálika v Istanbule stojí zvyčajne približne 130-170€ za zub." },
    { h: "Prečo môžu stoličky stáť viac ako predné zuby" },
    { p: "Zub s viacerými kanálikmi trvá dlhšie vyčistiť a naplniť dôkladne." },
    { h: "Dodatočné náklady, na ktoré ľudia nie vždy plánujú: korunka potom" },
    { p: "Zub po liečbe koreňového kanálika je náchylnejší na prasknutie časom." },
    { h: "Čo pridáva vláknitý čap" },
    { p: "Ak chýba veľká časť prirodzenej štruktúry zuba, niekedy sa pred korunkou umiestni malý vláknitý čap." },
    { h: "Porovnanie nákladov na liečbu koreňového kanálika s alternatívou" },
    { p: "Extrakcia zuba a jeho nahradenie implantátom je výrazne vyšší náklad." },
    { h: "Čo požadovať vo vašej ponuke" },
    { p: "Opýtajte sa, či je ponuka iba na liečbu kanálika alebo zahŕňa následnú korunku." },
  ]
},
{
  slug: "cena-plnej-zubnej-protezy-istanbul-moznosti",
  title: "Cena plnej zubnej protézy v Istanbule: Možnosti a ceny",
  description: "Koľko obvykle stojí plná zubná protéza v Istanbule, ako sa porovnáva s možnosťami na implantátoch.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Tradičná plná protéza je jednou z dostupnejších možností" },
    { p: "Plná snímateľná protéza pre jeden oblúk stojí zvyčajne približne 700-900€ v Istanbule." },
    { h: "Prečo stojí menej ako možnosti na implantátoch" },
    { p: "Tradičná protéza nezahŕňa implantačnú operáciu — je nasadená priamo na ďasná." },
    { h: "Kompromis, ktorý stojí za pochopenie pred rozhodnutím" },
    { p: "Snímateľná protéza vyžaduje časom viac úprav." },
    { h: "Nočný chránič je súvisiaca, samostatná cena" },
    { p: "Ak škrípete zubami, nočný chránič chráni vašu investíciu v každom prípade." },
    { h: "Ako sa to porovnáva s All-on-4" },
    { p: "All-on-4 stojí spočiatku výrazne viac, hlavne kvôli implantačnej operácii." },
    { h: "Čo zahŕňa správna ponuka protézy" },
    { p: "Kompletná ponuka by mala uvádzať, či ide o plnú alebo čiastočnú protézu." },
  ]
},
{
  slug: "cena-bielenia-zubov-jedno-sedenie-vs-balicek",
  title: "Cena bielenia zubov: Jedno sedenie vs balíček",
  description: "Koľko obvykle stojí profesionálne bielenie zubov a prečo sa často kombinuje s inými liečbami.",
  date: "2026-09-10",
  relatedTreatment: "bielenie-zubov-istanbul",
  body: [
    { h: "Bielenie je jednou z dostupnejších samostatných liečeb" },
    { p: "Jedno sedenie profesionálneho bielenia, vrátane predchádzajúceho čistenia, stojí zvyčajne približne 130-170€ v Istanbule." },
    { h: "Prečo je často zahrnuté spolu s inou prácou" },
    { p: "Ak tiež robíte fazetky, bielenie zvyšných prirodzených zubov sa zvyčajne vykonáva vopred." },
    { h: "Čistenie zubného kameňa, ktoré je zvyčajne zahrnuté" },
    { p: "Správne sedenie bielenia zvyčajne zahŕňa najprv odstránenie povrchového zubného kameňa." },
    { h: "Prečo sa výsledky líšia medzi pacientmi" },
    { p: "Ako veľmi sa vaše zuby zosvetlia, závisí od vášho východiskového odtieňa." },
    { h: "Jedno sedenie vs viac" },
    { p: "Väčšina pacientov vidí svoj plný výsledok po jednom sedení v klinike." },
    { h: "Čo potvrdiť pred rezerváciou" },
    { p: "Potvrďte, či ponúkaná cena zahŕňa čistenie pred bielením." },
  ]
},
{
  slug: "cena-zdvihnutia-celustnej-dutiny-kedy-je-potrebne",
  title: "Cena zdvihnutia čeľustnej dutiny: Kedy je potrebné a čo pridáva",
  description: "Jasné vysvetlenie, kedy je zdvihnutie čeľustnej dutiny skutočne nevyhnutné, a koľko obvykle stojí.",
  date: "2026-09-10",
  relatedTreatment: "zdvihnutie-celustnej-dutiny-istanbul",
  body: [
    { h: "Zdvihnutie čeľustnej dutiny sa pridáva iba vtedy, keď to sken skutočne ukáže" },
    { p: "Toto nie je liečba, ktorú by si niekto vybral vopred — pridáva sa k implantačnému plánu iba vtedy, keď 3D sken ukáže nedostatočnú výšku kosti." },
    { h: "Koľko obvykle stojí štandardné zdvihnutie čeľustnej dutiny" },
    { p: "Zdvihnutie čeľustnej dutiny, ak je potrebné, zvyčajne pridáva približne 350-450€ k plánu implantačnej liečby." },
    { h: "Prečo to niektoré prípady skutočne potrebujú a iné nie" },
    { p: "Potom, čo zub chýba nejaký čas, sa dutina môže postupne rozšíriť." },
    { h: "Rozdiel medzi \"uzavretým\" a \"otvoreným\" zdvihnutím" },
    { p: "Uzavreté zdvihnutie je menšia, menej invazívna technika používaná, keď je potrebná iba malá dodatočná výška." },
    { h: "Prečo to ovplyvňuje nielen cenu, ale aj váš liečebný harmonogram" },
    { p: "Ak je potrebné otvorené zdvihnutie, zvyčajne to pridáva niekoľko mesiacov k celkovému harmonogramu." },
    { h: "Poctivý záver" },
    { p: "Nebudete vedieť, či potrebujete zdvihnutie čeľustnej dutiny, kým nebude váš prípad skutočne vyšetrený 3D skenom." },
  ]
},
{
  slug: "znacky-zubnych-implantatov-preco-ovplyvnuju-cenu",
  title: "Značky zubných implantátov: Prečo tak silne ovplyvňujú cenu",
  description: "Prečo môže byť rovnaký implantačný postup ocenený veľmi odlišne v závislosti od použitého implantačného systému.",
  date: "2026-09-10",
  relatedTreatment: "zubne-implantaty-istanbul",
  body: [
    { h: "Nie všetky implantáty sú rovnaký produkt" },
    { p: "Implantát je titánová skrutka vyrobená konkrétnou spoločnosťou s vlastným výskumom." },
    { h: "Čo zvyčajne odlišuje prémiový systém od dostupnejšieho" },
    { p: "Prémiové implantačné systémy majú zvyčajne dlhšiu históriu publikovaných dlhodobých klinických štúdií." },
    { h: "Prečo na tom záleží, ak nakoniec navštívite iného zubára" },
    { p: "Široko uznávanú medzinárodnú značku je zvyčajne jednoduchšie nájsť v dieloch." },
    { h: "To neznamená, že dostupnejšia možnosť je zlá voľba" },
    { p: "Ako prémiové, tak dostupnejšie implantačné systémy sú legitímne zdravotnícke pomôcky s označením CE." },
    { h: "Cenový rozdiel v praxi" },
    { p: "Rozdiel je zvyčajne približne 30-40% za implantát." },
    { h: "Jediná otázka, na ktorej skutočne záleží" },
    { p: "Opýtajte sa akejkoľvek kliniky presne, akú značku implantátu ponúkajú." },
  ]
},
{
  slug: "preco-su-zubarske-ceny-v-turecku-tak-nizsie",
  title: "Prečo sú zubárske ceny v Turecku tak oveľa nižšie? Skutočné vysvetlenie",
  description: "Skutočné ekonomické dôvody, prečo zubná liečba stojí menej v Turecku.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Nie je to preto, že by zubné lekárstvo bolo nižšej kvality" },
    { p: "Cenový rozdiel medzi Tureckom a západnou Európou pochádza z niekoľkých kombinovaných faktorov." },
    { h: "Životné náklady a réžijné náklady kliniky" },
    { p: "Nájmy a mzdy personálu sú štrukturálne nižšie v Turecku ako v Londýne alebo Berlíne." },
    { h: "Výmenné kurzy fungujú v prospech medzinárodných pacientov" },
    { p: "Pretože náklady kliniky sú prevažne v tureckých lírách, výmenné kurzy zosilňujú cenovú výhodu." },
    { h: "Vládna podpora sektora zdravotnej turistiky" },
    { p: "Turecká vláda aktívne investovala do pozicovania krajiny ako destinácie zdravotnej turistiky." },
    { h: "Vyšší objem pacientov mení ekonomiku" },
    { p: "Kliniky s veľkým počtom medzinárodných pacientov môžu investovať do vlastných laboratórií." },
    { h: "Čo to neznamená" },
    { p: "Nižšia cena neznamená automaticky nižšie štandardy." },
  ]
},
{
  slug: "je-zubna-turistika-v-turecku-bezpecna",
  title: "Je zubná turistika v Turecku bezpečná? Čo skutočne ukazujú dáta",
  description: "Vecný pohľad na bezpečnosť zubnej turistiky v Turecku — regulácie za ňou, rozsah odvetvia a čo skutočne chráni pacientov.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Toto je prvá otázka, ktorú kladie takmer každý potenciálny pacient" },
    { p: "Krátka odpoveď je, že Turecko má pre to formálny, štátom regulovaný rámec." },
    { h: "Regulačný rámec bol posilnený v roku 2025" },
    { p: "Predpisy o zdravotnej turistike v Turecku boli posilnené v apríli 2025." },
    { h: "Rozsah odvetvia v reálnych číslach" },
    { p: "Podľa údajov Tureckej asociácie zdravotnej turistiky prijala krajina viac ako 1,39 milióna návštevníkov v roku 2025." },
    { h: "Konkrétne postavenie Turecka v zubnej turistike" },
    { p: "Podľa údajov Ministerstva zdravotníctva prijalo Turecko cez 400 000 zubných turistov len v roku 2023." },
    { h: "Na čom skutočne závisí \"bezpečnosť\"" },
    { p: "Bezpečnosť v tomto kontexte nie je vlastnosťou krajiny ako celku." },
    { h: "Čo si môžete sami overiť pred rezerváciou" },
    { p: "Požiadajte o certifikát USTYB kliniky, overte registráciu na portáli HealthTürkiye." },
  ]
},
{
  slug: "certifikat-medzinarodnej-zdravotnej-turistiky-vysvetlenie",
  title: "Turecký certifikát autorizácie medzinárodnej zdravotnej turistiky (USTYB) vysvetlený",
  description: "Čo skutočne je certifikát USTYB, prečo záleží a ako overiť, či ho klinika skutočne vlastní.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Certifikát, ktorý oddeľuje autorizovanú kliniku od neregulovanej" },
    { p: "Certifikát USTYB vydáva Ministerstvo zdravotníctva Turecka špeciálne zdravotníckym zariadeniam oprávneným liečiť medzinárodných pacientov." },
    { h: "Čo musí klinika skutočne preukázať, aby ho získala" },
    { p: "Kliniky usilujúce sa o túto autorizáciu musia spĺňať definované štandardy." },
    { h: "Prečo tento konkrétny certifikát záleží viac než všeobecné marketingové tvrdenia" },
    { p: "Certifikát USTYB je konkrétne viazaný na overiteľnú registráciu u Ministerstva zdravotníctva." },
    { h: "Spojenie s portálom HealthTürkiye" },
    { p: "Očakáva sa tiež, že autorizované kliniky budú uvedené na oficiálnom portáli." },
    { h: "Čo skutočne požadovať od kliniky pred rezerváciou" },
    { p: "Požiadajte o priame zobrazenie certifikátu, nie len logo na webovej stránke." },
    { h: "Prečo stojí za to overiť tento jeden detail" },
    { p: "Vyleštené webové stránky a atraktívne ceny nenahrádzajú regulačnú legitimitu." },
  ]
},
{
  slug: "ako-overit-legitimitu-zubnej-kliniky-v-zahranici",
  title: "Ako skutočne overiť, že zubná klinika v zahraničí je legitímna",
  description: "Praktický kontrolný zoznam na potvrdenie, že zubná klinika v zahraničí je riadne certifikovaná a bezpečná.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Overenie trvá desať minút" },
    { p: "Väčšina legitímnych kliník tieto otázky víta." },
    { h: "1. Požiadajte o certifikát USTYB" },
    { p: "Legitímna klinika vám tento dokument priamo ukáže." },
    { h: "2. Overte registráciu na portáli HealthTürkiye" },
    { p: "Toto je nezávislý spôsob overenia tvrdení kliniky." },
    { h: "3. Opýtajte sa, aké konkrétne značky implantátov sa používajú" },
    { p: "Konkrétna, pomenovaná značka s dokumentovanou výrobnou históriou je dobrým znamením." },
    { h: "4. Opýtajte sa, či je záruka písomná" },
    { p: "Ústna \"doživotná záruka\" znamená málo bez písomného dokumentu." },
    { h: "5. Hľadajte certifikácie ISO" },
    { p: "Tie naznačujú, že klinika investovala do formálnych procesov." },
    { h: "6. Opýtajte sa, kto skutočne plánuje váš prípad" },
    { p: "Váš liečebný plán by mal byť postavený z vašich vlastných skenov." },
  ]
},
{
  slug: "co-sa-stane-ak-nieco-nefunguje-po-navrate-domov",
  title: "Čo sa stane, ak niečo nefunguje po návrate domov?",
  description: "Priamy pohľad na následnú starostlivosť a záručnú ochranu pre pacientov cestujúcich do zahraničia za zubnou liečbou.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Toto je obava za takmer každým váhaním ohľadom liečby v zahraničí" },
    { p: "Klinika skutočne vybavená pre medzinárodných pacientov má na to skutočné odpovede." },
    { h: "Čo špecifikuje skutočný záručný dokument" },
    { p: "Správna písomná záruka špecifikuje presne, čo je pokryté a na ako dlho." },
    { h: "Vzdialené sledovanie predtým, ako sa niečo stane naliehavým" },
    { p: "Mnoho problémov možno najprv posúdiť vzdialene." },
    { h: "Kedy je skutočne potrebná návratová návšteva" },
    { p: "Pri skutočných záručných prípadoch by legitímna klinika mala pokryť samotnú liečbu." },
    { h: "S čím môžu a nemôžu pomôcť miestni zubári vo vašej krajine" },
    { p: "Zubár vo vašej domovskej krajine obvykle dokáže zvládnuť skutočné pohotovostné prípady." },
    { h: "Poctivá odpoveď" },
    { p: "Realistická väčšina hojenia implantátov prebieha bez incidentov." },
  ]
},
{
  slug: "preco-miliony-pacientov-volia-turecko-pre-zubnu-starostlivost",
  title: "Prečo milióny pacientov volia Turecko pre zubnú starostlivosť",
  description: "Skutočný rozsah zubnej turistiky do Turecka a faktory za voľbou toľkých medzinárodných pacientov.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Čísla za trendom sú väčšie, než väčšina ľudí očakáva" },
    { p: "Turecko prijalo cez 1,39 milióna návštevníkov zdravotnej turistiky v roku 2025." },
    { h: "Konkrétne postavenie Turecka v globálnej zubnej turistike" },
    { p: "Turecko prijalo cez 400 000 zubných turistov za jediný rok." },
    { h: "Globálny trh sa skutočne rozširuje" },
    { p: "Globálny trh zubnej turistiky bol ocenený na približne 7,2 miliardy dolárov v roku 2024." },
    { h: "Náklady sú najčastejšie zmieňovaným dôvodom, ale zriedka jediným" },
    { p: "Okrem cenového rozdielu pacienti často uvádzajú rýchlejšiu dostupnosť termínov." },
    { h: "Infraštruktúra dozrela spolu s dopytom" },
    { p: "Vládne investície urobili celkovú skúsenosť výrazne štruktúrovanejšou." },
    { h: "Čo tento trend znamená pre potenciálneho pacienta" },
    { p: "Veľký, zavedený priemysel znamená viac konkurencie a výberu." },
  ]
},
{
  slug: "nucleoss-implantaty-najekonomickejsia-spolahliva-volba",
  title: "Implantáty NucleOSS: Najekonomickejšia spoľahlivá voľba v Turecku",
  description: "Čo skutočne sú implantáty NucleOSS, prečo sú jednou z dostupnejších možností.",
  date: "2026-09-12",
  relatedTreatment: "zubne-implantaty-istanbul",
  body: [
    { h: "Domáca turecká značka, nie neznáma" },
    { p: "NucleOSS bola založená v roku 2001 v Izmire, Turecko — prvý domáci výrobca zubných implantátov v krajine." },
    { h: "Prečo je cenovo dostupnejší ako importované systémy" },
    { p: "Jedna skrutka implantátu NucleOSS je zvyčajne ocenená okolo 150-200€." },
    { h: "Z čoho je skutočne vyrobený" },
    { p: "Implantáty NucleOSS sú vyrobené z čistého titánu." },
    { h: "Kde sa používa mimo Turecka" },
    { p: "NucleOSS je distribuovaný vo viac ako 18 krajinách." },
    { h: "Čo tu \"ekonomický\" neznamená" },
    { p: "Nižšia cena neznamená, že implantát je neregulovaný — NucleOSS je certifikovaný CE." },
    { h: "Komu táto možnosť skutočne vyhovuje" },
    { p: "Pre pacientov uprednostňujúcich náklady je to legitímna stredná cesta." },
    { h: "Poctivý kompromis, o ktorom stojí za to vedieť" },
    { p: "V porovnaní so švajčiarskymi systémami má NucleOSS kratšiu históriu publikácií." },
  ]
},
{
  slug: "nucleoss-24-rokov-tureckej-vyroby",
  title: "Implantáty NucleOSS: Čo skutočne znamená 24 rokov tureckej výroby",
  description: "Pohľad na výrobnú históriu NucleOSS a čo dve desaťročia nepretržitej výroby hovoria o spoľahlivosti.",
  date: "2026-09-12",
  relatedTreatment: "zubne-implantaty-istanbul",
  body: [
    { h: "Dlhovekosť ako výrobcu je skutočný signál" },
    { p: "Spoločnosť nepretržite vyrábajúca od roku 2001 má 24+ rokov skutočnej klinickej spätnej väzby." },
    { h: "Rad produktov odráža skutočnú investíciu do výskumu a vývoja" },
    { p: "NucleOSS ponúka niekoľko radov implantátov navrhnutých pre rôzne klinické situácie." },
    { h: "Vyrábané v Turecku, nie len montované" },
    { p: "Implantáty NucleOSS sú vyrábané domácky v Izmire." },
    { h: "Čo znamenajú \"kónické\" vs \"rovné\" dizajny implantátov pre vás" },
    { p: "Rôzne tvary tela implantátu vyhovujú rôznym podmienkam kosti." },
    { h: "Otázka kompatibility komponentov" },
    { p: "Široký kompatibilný ekosystém komponentov znamená dostupné diely o roky neskôr." },
    { h: "Ako sa to prakticky porovnáva s voľbou novšej značky" },
    { p: "Značka s kratšou históriou jednoducho nemala toľko času preukázať dlhodobé výsledky." },
    { h: "Čo to znamená pre vaše rozhodnutie" },
    { p: "24-ročná nepretržitá história NucleOSS je legitímnym faktorom v jej prospech." },
  ]
},
{
  slug: "cena-porcelanovej-korunky-istanbul-rozpoctova-moznost",
  title: "Cena porcelánovej korunky v Istanbule: Tradičná, rozpočtová možnosť",
  description: "Koľko obvykle stojí kovokeramická korunka, ako sa líši od zirkónu.",
  date: "2026-09-12",
  relatedTreatment: null,
  body: [
    { h: "Starší, dobre zavedený typ korunky — nie úpadok, iná možnosť" },
    { p: "Kovokeramické (PFM) korunky sa v zubnom lekárstve používajú desiatky rokov." },
    { h: "Koľko obvykle stojí porcelánová korunka" },
    { p: "V Istanbule stojí PFM korunka zvyčajne približne 80-100€ za jednotku." },
    { h: "Ako je skutočne postavená" },
    { p: "PFM korunka má kovovú substruktúru pre pevnosť." },
    { h: "Jediný poctivý kompromis, o ktorom stojí za to vedieť" },
    { p: "Po mnohých rokoch sa kovový okraj pri ďasne môže stať mierne viditeľným." },
    { h: "Kde porcelánové korunky skutočne dávajú zmysel" },
    { p: "Pre zadné stoličky, kde je korunka zriedka viditeľná, je to rozumná voľba." },
    { h: "Kde sa zvyčajne preferuje zirkón" },
    { p: "Pre predné, viditeľné zuby sa väčšina teraz prikláňa k zirkónu." },
    { h: "Čo špecifikuje spravodlivá ponuka" },
    { p: "Správna ponuka by mala jasne uvádzať, či ide o PFM alebo zirkón." },
  ]
},
{
  slug: "porcelan-vs-zirkon-korunky-co-sa-hodi-k-vasmu-rozpoctu",
  title: "Porcelán vs zirkón korunky: Čo sa skutočne hodí k vášmu rozpočtu a prípadu",
  description: "Priame, praktické porovnanie medzi kovokeramickými a zirkónovými korunkami.",
  date: "2026-09-12",
  relatedTreatment: null,
  body: [
    { h: "Dve legitímne možnosti, nie voľba \"dobré vs zlé\"" },
    { p: "Ako kovokeramické, tak zirkónové korunky sú zavedené, spoľahlivé reštaurácie." },
    { h: "Cenový rozdiel v praxi" },
    { p: "PFM korunky stoja zvyčajne približne 80-100€, monolitický zirkón približne 120-180€." },
    { h: "Trvanlivosť: bližšie, než väčšina predpokladá" },
    { p: "Oba typy materiálu sú skutočne trvanlivé pri správnom nasadení." },
    { h: "Vzhľad: kde sa ukazuje skutočný rozdiel" },
    { p: "Najväčšou výhodou zirkónu je, že vôbec neobsahuje kov." },
    { h: "Rozumný spôsob, ako premýšľať o kombinácii oboch" },
    { p: "Mnoho pacientov rozumne volí zirkón pre viditeľné predné zuby." },
    { h: "Čo určuje, ktorú váš zubár odporučí" },
    { p: "Váš zubár zohľadní, koľko prirodzenej štruktúry zuba zostáva." },
    { h: "Otázka, ktorú si položiť pred rozhodnutím" },
    { p: "Opýtajte sa svojho zubára priamo, aký materiál by odporučil." },
  ]
}
];
