export const BLOG_SL = [
{
  slug: "all-on-4-ali-all-on-6-kaj-je-primerno-za-vas",
  title: "All-on-4 ali All-on-6: Kaj je primerno za vas?",
  description: "Tako All-on-4 kot All-on-6 vam zagotavljata popoln, fiksni zobni lok na vsadkih. Tukaj je resnična razlika med njima in kako zobozdravnik odloči, kaj ustreza vaši čeljusti.",
  date: "2026-09-01",
  relatedTreatment: "all-on-4-5-6-vsadki-istanbul",
  body: [
    { h: "Kratek odgovor" },
    { p: "All-on-4 in All-on-6 uporabljata isto osnovno idejo — popoln lok fiksnih zob, podprt z majhnim številom vsadkov, nameščenih v čeljust." },
    { h: "Zakaj bi morda potrebovali šest namesto štiri?" },
    { p: "Odločitev se običajno svede na kost. All-on-4 je bil posebej zasnovan za delo s kostjo, ki jo večina pacientov že ima." },
    { h: "Ali dodatni vsadek spremeni rezultat, ki ga čutite dan za dnem?" },
    { p: "Ne. Ne glede na to, ali vaš novi lok počiva na štirih ali šestih vsadkih, končni most izgleda in se počuti enako v vaših ustih." },
    { h: "Kako se odločitev dejansko sprejme" },
    { p: "Ustrezno 3D skeniranje pokaže vašemu zobozdravniku natančno, koliko kosti je na voljo v vsakem območju vaše čeljusti." },
    { h: "Skratka" },
    { p: "All-on-4 je standardna, dobro preizkušena izhodiščna točka za večino pacientov. All-on-6 obstaja za ljudi, katerih gostota kosti resnično zahteva dodatno podporo." },
  ]
},
{
  slug: "cirkonij-ali-emax-izbira-pravega-materiala",
  title: "Cirkonij ali E-max: Izbira pravega materiala za vaš nasmeh",
  description: "Cirkonij in E-max sta dva materiala, ki stojita za večino sodobnih kron in fasetk.",
  date: "2026-09-01",
  relatedTreatment: "monolitni-cirkonij-krone-istanbul",
  body: [
    { h: "Dve različni nalogi, dva različna materiala" },
    { p: "Cirkonij in E-max sta obe visokokakovostni keramiki, vendar nista zamenljivi." },
    { h: "Kje zmaga cirkonij" },
    { p: "Cirkonij je izjemno trden in odporen na lomljenje tudi na zadnjih zobeh, ki nosijo obremenitev." },
    { h: "Kje zmaga E-max" },
    { p: "E-max ima steklasto prosojnost, ki bolj posnema naravno zobno sklenino." },
    { h: "Kaj je torej resnično primerno za vas?" },
    { p: "V praksi mnogi pacienti dobijo mešanico: E-max spredaj za najboljši kozmetični rezultat." },
  ]
},
{
  slug: "koliko-dni-je-potrebnih-v-istanbulu-za-zobozdravstveno-zdravljenje",
  title: "Koliko dni je potrebnih v Istanbulu za zobozdravstveno zdravljenje?",
  description: "Odgovor je popolnoma odvisen od zdravljenja, ki ga prejemate.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Ni enega odgovora — odvisno je od zdravljenja" },
    { p: "To je eno najpogosteje zastavljenih vprašanj za vsakogar, ki načrtuje zobozdravstveno zdravljenje v tujini." },
    { h: "Zdravljenja v enem obisku (3–7 dni)" },
    { p: "Fasetke, krone, beljenje zob in preobrazbe Hollywood Smile brez vsadkov se običajno zaključijo v enem potovanju." },
    { h: "Zdravljenja z vsadki (dva obiska, meseci narazen)" },
    { p: "Zobni vsadki potrebujejo čas, da se zlijejo s čeljustno kostjo, preden je mogoče pritrditi trajno krono." },
    { h: "All-on-4 / All-on-6 konkretno" },
    { p: "Primeri vsadkov celotnega loka sledijo istemu vzorcu dveh obiskov." },
    { h: "Načrtovanje okoli tega" },
    { p: "Če kombinirate zdravljenja, se dodatno kozmetično delo običajno načrtuje okoli urnika vsadkov." },
  ]
},
{
  slug: "fasetke-ali-krone-kaksna-je-razlika",
  title: "Fasetke ali krone: Kakšna je razlika, in kaj potrebujete?",
  description: "Fasetke in krone rešujejo različne probleme.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Temeljna razlika" },
    { p: "Fasetka pokriva samo sprednjo, vidno površino zoba. Krona pokriva celoten zob, z vseh strani." },
    { h: "Kdaj je fasetka pravo orodje" },
    { p: "Fasetke so zasnovane za zobe, ki so kozmetično poškodovani, vendar strukturno zdravi." },
    { h: "Kdaj je krona pravo orodje" },
    { p: "Krone so za strukturno oslabljene zobe — veliko plombo, ki je odpovedala." },
    { h: "Ali se lahko mešajo v enem nasmehu?" },
    { p: "Da, in to je pogosto. Popolna preobrazba nasmeha pogosto združuje oboje." },
    { h: "Kaj to pomeni za vaše posvetovanje" },
    { p: "Če klinika predlaga krone na zobeh brez strukturne poškodbe, je razumno vprašati zakaj." },
  ]
},
{
  slug: "kaj-se-zgodi-ce-nimate-dovolj-kosti-za-vsadke",
  title: "Kaj se zgodi, če nimate dovolj kosti za vsadke?",
  description: "Izguba kosti samodejno ne izključuje vsadkov.",
  date: "2026-09-01",
  relatedTreatment: "dvig-sinusa-istanbul",
  body: [
    { h: "Izguba kosti je pogosta, ne diskvalificirajoča" },
    { p: "Potem ko zob manjka nekaj časa, se čeljustna kost na tem območju naravno skrči." },
    { h: "Kako zobozdravnik dejansko preveri" },
    { p: "3D skeniranje pokaže natančno višino in širino razpoložljive kosti na mestu vsadka." },
    { h: "Možnost 1 — Nagnjena namestitev vsadka" },
    { p: "Tehnike, kot je All-on-4, so bile delno zasnovane prav okoli tega problema." },
    { h: "Možnost 2 — Nadgradnja kosti" },
    { p: "Ko resnično ni dovolj obsega kosti, nadgradnja kosti doda material." },
    { h: "Možnost 3 — Dvig sinusa" },
    { p: "Zgornja zadnja čeljust se nahaja blizu sinusnih votlin." },
    { h: "Zaključek" },
    { p: "„Nimam dovolj kosti“ je redko konec pogovora." },
  ]
},
{
  slug: "nega-po-vsaditvi-kaj-se-zgodi-po-vrnitvi-domov",
  title: "Nega po vsaditvi: Kaj se zgodi po vrnitvi domov?",
  description: "Pridobitev vsadkov v tujini ne pomeni, da ste sami po pristanku doma.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Nega po zdravljenju se ne bi smela končati na letališču" },
    { p: "Pogosta skrb glede pridobitve vsadkov v tujini je, kaj se zgodi, če se nekaj zdi narobe po vrnitvi." },
    { h: "Kako se počuti normalno celjenje" },
    { p: "Blaga bolečina in nekaj oteklosti v dneh takoj po operaciji vsadka je normalno." },
    { h: "Kaj vključuje pravi načrt nege po zdravljenju" },
    { p: "Pisno jamstvo, ki določa, kaj je krito in za koliko časa." },
    { h: "Kaj vprašati pred zavezo" },
    { p: "Pred rezervacijo je razumno neposredno vprašati o neuspehu vsadka." },
    { h: "Realistična slika" },
    { p: "Večina celjenja vsadkov poteka brez incidentov." },
  ]
},
{
  slug: "ali-emax-fasetke-zahtevajo-brusenje-zob",
  title: "Ali E-max fasetke zahtevajo brušenje zob?",
  description: "Ena najpogostejših skrbi glede fasetk.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Iskren odgovor: odvisno je od vaše izhodiščne točke" },
    { p: "E-max fasetke so pogosto opisane kot „minimalna priprava“, in to iz dobrega razloga." },
    { h: "Kdaj je potrebno zelo malo ali nič zmanjšanja" },
    { p: "Če so vaši zobje že razumno dobro poravnani, se tanka fasetka pogosto lahko prilepi z malo odstranjevanja sklenine." },
    { h: "Kdaj je resnično potrebna več priprave" },
    { p: "Če je zob znatno neporavnan, je običajno potrebno določeno zmanjšanje sklenine." },
    { h: "Zakaj bi se to moralo odločiti pred potovanjem" },
    { p: "Skeniranje digitalnega oblikovanja nasmeha resnično odgovori na to vprašanje za vaše specifične zobe." },
    { h: "Kaj vprašati" },
    { p: "Vprašajte neposredno: „koliko mojega naravnega zoba boste morali odstraniti za ta dizajn?“" },
  ]
},
{
  slug: "koliko-casa-traja-izdelava-cirkonijeve-krone",
  title: "Koliko časa traja izdelava cirkonijeve krone?",
  description: "Od vašega prvega obiska do dokončane krone.",
  date: "2026-09-02",
  relatedTreatment: "monolitni-cirkonij-krone-istanbul",
  body: [
    { h: "Kratka različica" },
    { p: "Ena cirkonijeva krona običajno traja nekaj dni za oblikovanje, rezkanje in dokončanje." },
    { h: "Kaj se dejansko zgodi v tem času" },
    { p: "Datoteka se pošlje na rezkanje, kjer stroj izreže krono iz cirkonijevega bloka." },
    { h: "Zakaj je notranje rezkanje pomembno za vaš urnik" },
    { p: "Klinike z lastnim laboratorijem lahko dokončajo krono v enem ali dveh dneh." },
    { h: "Kdaj traja dlje" },
    { p: "Več kron naravno vzame več vašega časa obiska." },
  ]
},
{
  slug: "kaj-dejansko-vkljucuje-zdravljenje-oblikovanja-nasmeha",
  title: "Kaj dejansko vključuje zdravljenje oblikovanja nasmeha?",
  description: "„Oblikovanje nasmeha“ in „Digitalno oblikovanje nasmeha“ se uporabljata ohlapno.",
  date: "2026-09-02",
  relatedTreatment: "digitalno-oblikovanje-nasmeha-istanbul",
  body: [
    { h: "To je proces načrtovanja, ne en postopek" },
    { p: "Digitalno oblikovanje nasmeha samo po sebi ni zdravljenje — to je faza načrtovanja." },
    { h: "Korak 1 — Analiza vašega obraza, ne samo zob" },
    { p: "Posnamejo se fotografije in včasih video vašega nasmeha." },
    { h: "Korak 2 — 3D skeniranje in digitalni maket" },
    { p: "Intraoralno skeniranje zgradi 3D model vaših zob." },
    { h: "Korak 3 — Ugotavljanje, katera zdravljenja so resnično potrebna" },
    { p: "Vaš zobozdravnik določi kombinacijo zdravljenj, ki bo to doseglo." },
    { h: "Korak 4 — Fizični maket v ustih" },
    { p: "Mnoge klinike vam lahko pokažejo začasno različico dizajna neposredno na vaših zobeh." },
    { h: "Zakaj je to pomembno" },
    { p: "Brez digitalnega skeniranja verjetno dobite standarden kozmetični paket." },
  ]
},
{
  slug: "hollywood-smile-proti-fasetkam-resnicna-razlika",
  title: "Hollywood Smile proti fasetkam: Kakšna je resnična razlika?",
  description: "„Hollywood Smile“ ni ločen material od fasetk.",
  date: "2026-09-02",
  relatedTreatment: "hollywood-smile-istanbul",
  body: [
    { h: "Hollywood Smile je rezultat, ne material" },
    { p: "„Fasetke“ opisujejo specifično restavracijo. „Hollywood Smile“ opisuje širši kozmetični cilj." },
    { h: "Torej Hollywood Smile lahko uporablja fasetke, ali pa ne" },
    { p: "Rezultat je mogoče doseči s fasetkami, kronami ali kombinacijo." },
    { h: "Zakaj je ta razlika pomembna pri primerjavi ponudb" },
    { p: "Primerjajte konkretno, kateri materiali in koliko zob je vključenih." },
    { h: "Kaj dejansko določa, ali so fasetke pravi izbor" },
    { p: "To se vrne na stanje specifičnega zoba." },
  ]
},
{
  slug: "invisalign-proti-tradicionalnim-zobnim-aparatkom-kaj-izbrati",
  title: "Invisalign proti tradicionalnim zobnim aparatkom: Kaj izbrati?",
  description: "Prozorne opornice in kovinski aparatki oboji ravnajo zobe.",
  date: "2026-09-02",
  relatedTreatment: "invisalign-prozorne-opornice-istanbul",
  body: [
    { h: "Oboje deluje — vprašanje je primernost" },
    { p: "Prozorne opornice in tradicionalni aparatki premikajo zobe z nadzorovanim pritiskom." },
    { h: "Kje prozorne opornice dobro delujejo" },
    { p: "Blago do zmerno gnečo je običajno dobro primerno za opornice." },
    { h: "Kje so tradicionalni aparatki še vedno boljše orodje" },
    { p: "Kompleksnejši premiki se pogosto bolje rešujejo s fiksnimi aparatki." },
    { h: "Dejavnik discipline" },
    { p: "Opornice delujejo samo, če se nosijo 20-22 ur na dan." },
    { h: "Kako se odločitev dejansko sprejme" },
    { p: "3D skeniranje pokaže, katere premike vaš primer resnično potrebuje." },
  ]
},
{
  slug: "zobni-most-ali-vsadek-kako-izbrati",
  title: "Zobni most ali vsadek: Kako izbrati",
  description: "Oba nadomestita manjkajoči zob, vendar delujeta zelo različno.",
  date: "2026-09-02",
  relatedTreatment: "zobni-most-istanbul",
  body: [
    { h: "Temeljna razlika" },
    { p: "Vsadek neposredno nadomesti manjkajočo korenino zoba. Most nadomesti samo viden zob." },
    { h: "Zakaj je most pogosto hitrejši" },
    { p: "Most ne zahteva operacije ali obdobja celjenja." },
    { h: "Zakaj je vsadek pogosto močnejša dolgoročna izbira" },
    { p: "Vsadek ne zahteva priprave sicer zdravih zob." },
    { h: "Odločilni dejavnik" },
    { p: "Če sosednji zobje že potrebujejo krone, je most učinkovita izbira." },
    { h: "Pravično vprašanje, ki ga je vredno zastaviti" },
    { p: "Vprašajte kliniko neposredno, zakaj priporočajo most." },
  ]
},
{
  slug: "kaj-se-zgodi-med-zdravljenjem-korenskega-kanala-korak-za-korakom",
  title: "Kaj se zgodi med zdravljenjem korenskega kanala, korak za korakom",
  description: "Jasen, postopni pregled zdravljenja korenskega kanala.",
  date: "2026-09-02",
  relatedTreatment: "zdravljenje-korenskega-kanala-istanbul",
  body: [
    { h: "Zakaj ima ta postopek slabši ugled kot izkušnja" },
    { p: "Nelagodje običajno prihaja od same okužbe, ne od postopka." },
    { h: "Korak 1 — Diagnoza in rentgen" },
    { p: "Rentgen potrdi obseg okužbe." },
    { h: "Korak 2 — Lokalna anestezija" },
    { p: "Zob se anestezira pred vsem drugim." },
    { h: "Korak 3 — Odstranitev okužene tkiva" },
    { p: "Okužena pulpa se odstrani iz kanala." },
    { h: "Korak 4 — Čiščenje in dezinfekcija" },
    { p: "Prostor kanala se očisti in dezinficira." },
    { h: "Korak 5 — Zapiranje zoba" },
    { p: "Kanal se napolni z biokompatibilnim materialom." },
    { h: "Korak 6 — Običajno zaščitna krona" },
    { p: "Krona se običajno priporoča kasneje." },
    { h: "Kako se okrevanje dejansko počuti" },
    { p: "Blaga bolečina je običajno obvladljiva s standardnimi analgetiki." },
  ]
},

{
  slug: "znaki-da-bi-morda-potrebovali-gingivektomijo",
  title: "Znaki, da bi morda potrebovali gingivektomijo",
  description: "Gingivektomija ni namenjena samo „nasmehu z dlesnimi“.",
  date: "2026-09-02",
  relatedTreatment: "gingivektomija-istanbul",
  body: [
    { h: "Gre za več kot le videz" },
    { p: "Gingivektomija je pogosto omenjena samo v kozmetičnem kontekstu, vendar je lahko presežno tkivo dlesni tudi resnična težava ustnega zdravja." },
    { h: "Znak 1 — Pri nasmehu pokažete opazno več dlesni kot zoba" },
    { p: "„Nasmeh z dlesnimi“, kjer je širok pas tkiva dlesni viden nad zobmi, je najpogosteje prepoznan razlog." },
    { h: "Znak 2 — Vaša linija dlesni je neravna vzdolž sprednjih zob" },
    { p: "Neravni nivoji lahko naredijo sicer dobro oblikovane zobe neskladne." },
    { h: "Znak 3 — Presežno tkivo dlesni otežuje pravilno čiščenje zob" },
    { p: "Tkivo, ki se prekriva okoli zob, lahko zadržuje plak na način, ki ga je resnično težko učinkovito ščetkati." },
    { h: "Znak 4 — Načrtujete fasetke in vaši nivoji dlesni so neravni" },
    { p: "Ocena dlesni je pogosto del pravilnega načrta digitalnega oblikovanja nasmeha." },
    { h: "Kaj dejansko storiti" },
    { p: "Noben od teh znakov ne pomeni, da je gingivektomija samodejno pravi odgovor prav za vas." },
  ]
},
{
  slug: "vprasanja-pred-izbiro-klinike-v-tujini",
  title: "Vprašanja, ki jih je treba postaviti pred izbiro zobozdravstvene klinike v tujini",
  description: "Praktičen kontrolni seznam tega, kaj dejansko vprašati pred rezervacijo zobozdravstvenega zdravljenja v drugi državi.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Samo primerjava cen ne pove veliko" },
    { p: "Dve kliniki lahko ponudita isto ceno za „All-on-4“, vendar mislita na resnično različne stvari." },
    { h: "1. Katero konkretno znamko vsadka ali materiala uporabljate?" },
    { p: "Prave, uveljavljene znamke imajo sledljivo zgodovino proizvodnje." },
    { h: "2. Ali je garancija pisna, in kaj natančno pokriva?" },
    { p: "„Doživljenjska garancija“ bi morala določiti, kaj je vključeno." },
    { h: "3. Kdo izvaja načrtovanje primera, in ali temelji na mojih lastnih skeniranjih?" },
    { p: "Vaš načrt zdravljenja bi moral biti zgrajen iz vaših lastnih 3D skeniranj." },
    { h: "4. Kaj se zgodi, če nekaj potrebuje pozornost po tem, ko grem domov?" },
    { p: "Klinika, ki je prepričana v svoje delo, bi morala imeti jasen odgovor." },
    { h: "5. Ali je klinika uradno pooblaščena za mednarodne paciente?" },
    { p: "Konkretno v Turčiji bi morale klinike, ki zdravijo mednarodne paciente, imeti veljavno dovoljenje za mednarodni zdravstveni turizem." },
    { h: "6. Kaj je dejansko vključeno v navedeno ceno?" },
    { p: "Vprašajte konkretno, ali ponudba vključuje posvetovanje, vsa skeniranja in nadaljnje obiske." },
  ]
},
{
  slug: "katere-certifikate-bi-morala-imeti-zobozdravstvena-klinika-v-tujini",
  title: "Katere certifikate bi morala zobozdravstvena klinika v tujini dejansko imeti?",
  description: "Certifikate in znake akreditacije je enostavno pokazati in težko preveriti samo s spletne strani.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Vsi certifikati nimajo enake teže" },
    { p: "Spletne strani klinik pogosto prikazujejo vrsto znakov in pečatov." },
    { h: "Dovoljenje za mednarodni zdravstveni turizem (specifično za Turčijo)" },
    { p: "V Turčiji bi morale klinike, ki zakonito zdravijo mednarodne paciente, imeti to dovoljenje od Ministrstva za zdravje." },
    { h: "ISO certifikati" },
    { p: "To so splošni standardi upravljanja kakovosti, ki niso specifični za zobozdravstvo." },
    { h: "Certifikati proizvajalcev vsadkov" },
    { p: "Nekatere klinike prikazujejo certifikate, ki potrjujejo, da so pooblaščeni uporabniki določene znamke vsadka." },
    { h: "Kaj dejansko storiti s to informacijo" },
    { p: "Ne zanašajte se izključno na znake, prikazane na spletni strani." },
  ]
},
{
  slug: "kako-dolgo-dejansko-trajajo-cirkonijeve-krone",
  title: "Kako dolgo dejansko trajajo cirkonijeve krone?",
  description: "Realističen pogled na življenjsko dobo cirkonijevih kron.",
  date: "2026-09-02",
  relatedTreatment: "monolitni-cirkonij-krone-istanbul",
  body: [
    { h: "Splošno območje" },
    { p: "Dobro izdelane cirkonijeve krone običajno trajajo 10 do 15 let ali dlje z razumno nego." },
    { h: "Zakaj monolitni cirkonij običajno traja dlje kot starejše cirkonijeve krone" },
    { p: "Starejše cirkonijeve krone so uporabljale cirkonijevo jedro z ločeno plastjo porcelana." },
    { h: "Kaj dejansko skrajša življenjsko dobo krone" },
    { p: "Nezdravljeno škripanje z zobmi (bruksizem) izvaja ponavljajočo prekomerno silo na krono." },
    { h: "Kaj lahko storite, da traja dlje" },
    { p: "Normalno ščetkanje in uporaba zobne nitke, kot bi to storili z naravnimi zobmi." },
    { h: "Ko „napaka“ dejansko ni o kroni" },
    { p: "Če je treba krono zamenjati po nekaj letih, se splača razumeti zakaj." },
  ]
},
{
  slug: "monolitni-proti-slojevitemu-cirkoniju-kaksna-je-razlika",
  title: "Monolitni proti slojevitemu cirkoniju: Kakšna je razlika?",
  description: "Oboje se imenuje „cirkonijeve krone“, vendar je konstrukcija resnično drugačna.",
  date: "2026-09-02",
  relatedTreatment: "monolitni-cirkonij-krone-istanbul",
  body: [
    { h: "Isti osnovni material, drugačna konstrukcija" },
    { p: "Tako monolitni kot slojeviti cirkonij uporabljata cirkonijev oksid." },
    { h: "Slojeviti cirkonij" },
    { p: "Slojevita krona ima cirkonijevo jedro za trdnost, kronano z ločeno plastjo porcelana." },
    { h: "Monolitni cirkonij" },
    { p: "Monolitna krona je v celoti rezkana iz enega cirkonijevega bloka." },
    { h: "Kje se vsak tipično uporablja" },
    { p: "Monolitni cirkonij je na splošno prednosten za zadnje zobe." },
    { h: "Zaključek" },
    { p: "Če je vzdržljivost proti lomljenju vaša glavna prioriteta, je monolitni cirkonij na splošno varnejša izbira." },
  ]
},
{
  slug: "ali-je-mogoce-kombinirati-vsadke-in-fasetke-v-enem-potovanju",
  title: "Ali je mogoče kombinirati vsadke in fasetke v enem potovanju?",
  description: "Kombiniranje zdravljenj je pogosto, vendar urnik celjenja vsadka spremeni način načrtovanja.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Da, vendar urnik vsadka določa tempo" },
    { p: "Kombiniranje vsadkov s fasetkami je pogosta zahteva." },
    { h: "Kako se to običajno načrtuje" },
    { p: "Med vašim prvim obiskom se namestijo vsadki." },
    { h: "Zakaj je čas beljenja tukaj posebej pomemben" },
    { p: "Če dobite tudi fasetke, bi moralo beljenje potekati pred njihovo izdelavo." },
    { h: "Kaj bi vam moral povedati kombiniran načrt zdravljenja" },
    { p: "Pravilen načrt podrobno opiše, kaj se zgodi vsak dan." },
    { h: "Praktična prednost kombiniranja" },
    { p: "Kombiniranje zdravljenj resnično zmanjša skupno potovanje." },
  ]
},
{
  slug: "obvladovanje-strahu-pred-zobozdravnikom-med-potovanjem-na-zdravljenje",
  title: "Obvladovanje strahu pred zobozdravnikom med potovanjem na zdravljenje",
  description: "Strah pred zobozdravnikom ne izgine samo zato, ker potujete na zdravljenje.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "To je pogosta skrb, ne nenavadna" },
    { p: "Strah pred zobozdravnikom je izjemno pogost, potovanje v tujino pa lahko doda dodatno plast stresa." },
    { h: "Dejansko razpoložljive možnosti sedacije" },
    { p: "Večina klinik ponuja možnosti poleg same lokalne anestezije." },
    { h: "Komunikacija je pomembnejša, kot ljudje pričakujejo" },
    { p: "Tesnoba je pogosto hujša, ko ne razumete v celoti, kaj se dogaja." },
    { h: "Načrtovanje pomaga bolj, kot se zavedajo večina ljudi" },
    { p: "Poznavanje vašega urnika vnaprej zmanjša negotovost." },
    { h: "Razumno je to povedati vnaprej" },
    { p: "Neposredno povedati koordinatorju o strahu mu da priložnost, da načrtuje okoli tega." },
  ]
},
{
  slug: "kaj-pripraviti-pred-zobozdravstvenim-zdravljenjem-v-tujini",
  title: "Kaj pripraviti pred zobozdravstvenim zdravljenjem v tujini",
  description: "Praktičen kontrolni seznam pred potovanjem.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Preden karkoli rezervirate" },
    { p: "Pridobite pisni načrt zdravljenja na podlagi vaših lastnih fotografij ali skeniranj." },
    { h: "Zdravstvene informacije, ki jih je treba imeti pripravljene" },
    { p: "Seznam zdravil, alergij in relevantnih zdravstvenih stanj bi morali deliti pred potovanjem." },
    { h: "Obstoječi zobozdravstveni zapisi" },
    { p: "Nedavne rentgenske slike lahko pospešijo načrtovanje." },
    { h: "Praktična logistika potovanja" },
    { p: "Potrdite oba datuma obiska vnaprej za primere vsadkov." },
    { h: "Vprašanja, na katera bi morali dobiti odgovor pred letom" },
    { p: "Skupno število potrebnih obiskov." },
    { h: "Kaj dejansko spakirati" },
    { p: "Seznam zdravil, udobna oblačila." },
  ]
},
{
  slug: "krona-ali-plomba-kaksna-je-razlika",
  title: "Krona ali plomba: Kakšna je razlika, in kdaj potrebujete katero?",
  description: "Oboje popravi poškodovan zob, vendar na zelo različnih ravneh poškodbe.",
  date: "2026-09-03",
  relatedTreatment: "monolitni-cirkonij-krone-istanbul",
  body: [
    { h: "Vse se vrti okoli tega, koliko zdravega zoba ostane" },
    { p: "Plomba popravi majhno do zmerno poškodovano območje, običajno od kariesa." },
    { h: "Kdaj plomba zadostuje" },
    { p: "Majhni do srednji kariesi, ujeti razumno zgodaj, se običajno dobro rešijo s plombo." },
    { h: "Kdaj plomba ne zadostuje" },
    { p: "Če je karies obsežen ali je zob počil, krona namesto tega zagotavlja polno pokritje." },
    { h: "Zakaj namestitev plombe, kjer je potrebna krona, ne zdrži" },
    { p: "Prevelika plomba glede na preostalo strukturo zoba bo bolj verjetno počila." },
    { h: "Iskren odgovor dobrega zobozdravnika" },
    { p: "Zobozdravnik, ki neposredno pogleda rentgen in sam zob, vam lahko pove, kaj potrebujete." },
  ]
},
{
  slug: "cena-all-on-4-kaj-je-dejansko-vkljuceno",
  title: "Cena All-on-4: Kaj je dejansko vključeno v ceno?",
  description: "Ponudbe All-on-4 lahko izgledajo zelo različno med klinikami iz razlogov, ki nimajo nič s kakovostjo.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-vsadki-istanbul",
  body: [
    { h: "Zakaj isti postopek dobi zelo različne ponudbe" },
    { p: "Dve kliniki lahko obe ponudita „All-on-4“ po zelo različnih cenah." },
    { h: "Znamka in kakovost vsadka" },
    { p: "Uveljavljene, klinično dokazane znamke vsadkov običajno stanejo več." },
    { h: "Kaj je vključeno v navedeno ceno" },
    { p: "Vprašajte konkretno, ali ponudba vključuje začetno posvetovanje in 3D skeniranje." },
    { h: "Ali je nadgradnja kosti ali dvig sinusa verjeten, in ali je vključen" },
    { p: "Če vaš primer morda potrebuje dodatno delo s kostjo, ponudba pred pregledom skeniranja tega ne more upoštevati." },
    { h: "Pogoji spremljanja in garancije" },
    { p: "Preverite, ali so nadaljnji pregledi in garancijsko obdobje vključeni v ceno." },
    { h: "Eno vprašanje, ki razjasni večino tega" },
    { p: "Vprašajte neposredno: „kaj bi spremenilo to končno ceno?“" },
  ]
},
{
  slug: "ali-lahko-namestite-zobne-vsadke-ce-kadite",
  title: "Ali lahko namestite zobne vsadke, če kadite?",
  description: "Kajenje samodejno ne izključuje vsadkov, vendar je resničen dejavnik, ki ga zobozdravniki jemljejo resno.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-vsadki-istanbul",
  body: [
    { h: "Kajenje je dejavnik tveganja, ne samodejna diskvalifikacija" },
    { p: "Mnogi kadilci dobijo uspešne, dolgotrajne zobne vsadke." },
    { h: "Zakaj je obdobje celjenja tukaj tako pomembno" },
    { p: "Osteointegracija je odvisna od zdrave preskrbe s krvjo tega območja." },
    { h: "Kaj dejansko priporočajo večina zobozdravnikov" },
    { p: "Mnoge klinike priporočajo prenehanje kajenja ali vsaj znatno zmanjšanje." },
    { h: "Iskrenost o tem je pomembna" },
    { p: "Povedati svojemu zobozdravniku, da kadite, mu omogoča, da pravilno načrtuje okoli tega." },
    { h: "Zaključek" },
    { p: "Kajenje naredi zdravljenje z vsadki nekoliko bolj tvegano, ne nemogoče." },
  ]
},
{
  slug: "kaj-je-osteointegracija-in-zakaj-je-pomembna-za-vsadke",
  title: "Kaj je osteointegracija, in zakaj je pomembna za vsadke?",
  description: "Izraz za tem, zakaj zdravljenje z vsadki traja mesece, ne dni.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-vsadki-istanbul",
  body: [
    { h: "Beseda, ki pojasni urnik vsadka z dvema obiskoma" },
    { p: "Osteointegracija je proces, pri katerem se titanov vsadek fizično zlije z okoliško čeljustno kostjo." },
    { h: "Zakaj konkretno titan" },
    { p: "Titan ima resnično nenavadno lastnost: žive kostne celice rastejo neposredno na njegovi površini." },
    { h: "Koliko časa traja" },
    { p: "Osteointegracija tipično traja nekaj mesecev, pogosto navedena kot približno tri do šest mesecev." },
    { h: "Kaj se zgodi, če se ta korak pohiti" },
    { p: "Obremenitev vsadka s končno restavracijo pred zaključkom osteointegracije tvega." },
    { h: "Zakaj je to pomembno pri primerjavi klinik" },
    { p: "Klinika, ki obljublja popolnoma trajno restavracijo vsadka v enem kratkem obisku, dela z nenavadno preprostim primerom ali preskoči korak." },
  ]
},
{
  slug: "koliko-stanejo-zobni-vsadki-v-turciji",
  title: "Koliko stanejo zobni vsadki v Turčiji?",
  description: "Realističen pregled stroškov zobnih vsadkov v Turčiji, zakaj se cene razlikujejo med klinikami in kaj bi dejansko morali primerjati pred odločitvijo.",
  date: "2026-09-10",
  relatedTreatment: "zobni-vsadki-istanbul",
  body: [
    { h: "Ni ene same številke, in vsaka klinika, ki poda ceno pred ogledom vašega primera, ugiba" },
    { p: "Cena vsadka je odvisna od blagovne znamke uporabljenega vsadka, potrebe po kostnem presadku in števila potrebnih vsadkov." },
    { h: "Blagovna znamka vsadka je največji posamezni dejavnik cene" },
    { p: "Klinike običajno ponujajo več kot en sistem vsadkov, razlika v ceni med njimi pa je resnična — pogosto 30-40% med ekonomičnim in premium sistemom." },
    { h: "Koliko običajno stane en vsadek" },
    { p: "Za en zobni vsadek (samo vijak, brez krone na vrhu) se cene v klinikah v Istanbulu običajno gibljejo od ~300€ do 450€+ za premium sisteme." },
    { h: "Zakaj je krona ločena postavka" },
    { p: "Vsadek nadomesti korenino; krona nadomesti viden zob. Popolna ponudba za \"vsadek + krono\" mora jasno prikazati oboje." },
    { h: "Kaj dejansko spremeni skupni znesek" },
    { p: "Kostni presadek ali dvig sinusa, če vaš primer to zahteva, se doda skupnemu znesku — to je resnično odvisno od stanja vaše čeljustne kosti." },
    { h: "Kako dobiti resnično številko za vaš primer" },
    { p: "Pošljite nedaven panoramski rentgen, če ga imate, ali načrtujte 3D skeniranje med posvetom." },
  ]
},
{
  slug: "cena-all-on-4-turcija-vs-uk-zda",
  title: "Cena All-on-4 v Turčiji vs UK in ZDA: Kaj dejansko primerjate",
  description: "Zakaj se ponudbe All-on-4 tako razlikujejo med državami in kaj dejansko povzroča razliko poleg stroškov dela.",
  date: "2026-09-10",
  relatedTreatment: "all-on-4-5-6-vsadki-istanbul",
  body: [
    { h: "Razlika je resnična, vendar ni le \"cenejša delovna sila\"" },
    { p: "All-on-4 v Turčiji je običajno ponujen za približno tretjino do polovico tipične cene v UK ali ZDA." },
    { h: "Kaj običajno vključuje primer polnega loka v Turčiji" },
    { p: "Popoln fiksni lok na štirih vsadkih, vključno z operacijo, običajno stane od ~2900€ na lok z dostopnejšim sistemom do 3400€ s premium sistemom." },
    { h: "Zakaj All-on-5 ali All-on-6 stane več" },
    { p: "Dodajanje petega ali šestega vsadka poveča skupni znesek za približno 300-450€ na dodaten vsadek." },
    { h: "Kaj lahko cene UK in ZDA vključujejo, česar ponudba iz Turčije nima" },
    { p: "Primerjajte, kaj je dejansko vključeno v vsako ponudbo: ali cena UK vključuje kontrolni obisk?" },
    { h: "Resnično razmislek o stroških, ki ga večina spregleda" },
    { p: "Tudi z vštetimi leti in nastanitvijo skupni znesek za primer polnega loka v tujini običajno ostane precej nižji." },
    { h: "Kaj vprašati pred primerjavo dveh ponudb" },
    { p: "Vprašajte vsako kliniko, katera blagovna znamka vsadka se uporablja in kaj dejansko krije garancija." },
  ]
},
{
  slug: "cena-laminatnih-fasetk-istanbul",
  title: "Cena laminatnih fasetk v Istanbulu: Kaj je dejansko vključeno",
  description: "Jasen pregled tega, kaj določa ceno laminatnih fasetk v Istanbulu, in kaj bi morala vsebovati pravilna ponudba.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Cena je običajno navedena na zob, ne na nasmeh" },
    { p: "Cena laminatnih fasetk je skoraj vedno na posamezen zob, zato je skupni znesek popolnoma odvisen od tega, koliko zob je vključenih v vaš dizajn nasmeha." },
    { h: "Koliko običajno stane ena fasetka" },
    { p: "Cena na zob za laminatne fasetke v Istanbulu je običajno v razponu približno 300-400€." },
    { h: "Zakaj material vpliva na ceno in rezultat" },
    { p: "Tanki porcelanski laminati zahtevajo natančno, minimalno pripravo zoba in spretnega keramika." },
    { h: "Kaj bi moralo biti vključeno v predlagano ceno" },
    { p: "Pravilna ponudba za fasetke bi morala vključevati posvet o digitalnem oblikovanju nasmeha in cementiranje." },
    { h: "Faza začasnih fasetk" },
    { p: "Med pripravljenimi zobmi in namestitvijo končnih fasetk običajno nekaj dni nosite začasne fasetke." },
    { h: "Zakaj najcenejša ponudba ni samodejno najboljša vrednost" },
    { p: "Bistveno nižja cena na zob kot vse ostalo, kar vidite, si zasluži neposredno vprašanje." },
  ]
},
{
  slug: "strosek-hollywood-smile-kaj-doloca-ceno",
  title: "Strošek Hollywood Smile: Kaj določa končno ceno",
  description: "Cena Hollywood Smile se razlikuje bolj kot skoraj vsako drugo zdravljenje, ker ni en sam fiksni postopek.",
  date: "2026-09-10",
  relatedTreatment: "hollywood-smile-istanbul",
  body: [
    { h: "\"Hollywood Smile\" opisuje rezultat, ne fiksnega cenika" },
    { p: "Ker je Hollywood Smile mogoče doseči s fasetkami, kronami ali mešanico obojega, lahko dve kliniki z zelo različnimi skupnimi zneski dejansko oblikujeta ceno različnih načrtov zdravljenja." },
    { h: "Število vključenih zob je največji posamezni dejavnik" },
    { p: "Popolna preobrazba Hollywood Smile običajno pokriva zgornjih vidnih 16-20 zob." },
    { h: "Fasetke vs krone spreminjajo ceno na zob" },
    { p: "Laminatne fasetke in polne cirkonijeve krone se cenovno oblikujejo različno." },
    { h: "Kaj doda popolno digitalno oblikovanje nasmeha" },
    { p: "Pravilen načrt Hollywood Smile se začne s 3D digitalnim oblikovanjem nasmeha." },
    { h: "Zakaj se lahko dva \"paketa Hollywood Smile\" razlikujeta za tisoče evrov" },
    { p: "Največja nihanja izvirajo iz števila vključenih zob in razreda materiala." },
    { h: "Vprašanje, ki ga je vredno postaviti neposredno" },
    { p: "Vprašajte natančno, koliko zob je vključenih v predlagano ceno." },
  ]
},
{
  slug: "cena-cirkonijeve-krone-cenejse-ni-vedno-boljse",
  title: "Cena cirkonijeve krone: Cenejše ni vedno boljše",
  description: "Kaj dejansko vpliva na ceno cirkonijeve krone in zakaj lahko najnižja ponudba včasih dolgoročno stane več.",
  date: "2026-09-10",
  relatedTreatment: "monolitni-cirkonij-krone-istanbul",
  body: [
    { h: "Osnovna cena je običajno skromna — kopičijo se prav dodatki" },
    { p: "Ena cirkonijeva krona sama po sebi je ena od dostopnejših restavrativnih možnosti — običajno 120-180€ na enoto v Istanbulu." },
    { h: "Monolitni vs slojeviti cirkonij" },
    { p: "Monolitni cirkonij, izrezan iz enega trdnega bloka, je ponavadi bolj odporen na odkruševanje." },
    { h: "Kaj doda titanova osnova" },
    { p: "Posebej za krone na vsadkih titanova osnova doda znaten znesek stroškom." },
    { h: "Zakaj si veliko cenejša ponudba zasluži neposredno vprašanje" },
    { p: "Vprašajte konkretno, ali gre za monolitni ali slojeviti cirkonij, in katero garancijsko obdobje je vključeno." },
    { h: "Kako število kron hitro spremeni skupni znesek" },
    { p: "Ker je cena na enoto, pridobite ceno enote in jo pomnožite sami." },
    { h: "Kaj dejansko določa poštena ponudba" },
    { p: "Zanesljiva ponudba navaja ceno na krono, specifičen tip cirkonija in garancijsko obdobje." },
  ]
},
{
  slug: "strosek-zdravljenja-korenskega-kanala-turcija",
  title: "Strošek zdravljenja korenskega kanala v Turčiji: Kaj pričakovati",
  description: "Neposreden pregled tega, koliko običajno stane zdravljenje korenskega kanala v Turčiji, in kaj bi še lahko potrebovali.",
  date: "2026-09-10",
  relatedTreatment: "zdravljenje-korenskega-kanala-istanbul",
  body: [
    { h: "Samo zdravljenje korenskega kanala je ena od dostopnejših postopkov" },
    { p: "Samo po sebi zdravljenje korenskega kanala v Istanbulu običajno stane približno 130-170€ na zob." },
    { h: "Zakaj lahko kočniki stanejo več kot sprednji zobje" },
    { p: "Zob z več kanali potrebuje več časa za temeljito čiščenje in polnjenje." },
    { h: "Dodaten strošek, na katerega ljudje ne vedno računajo: krona po tem" },
    { p: "Zob, ki je bil zdravljen s korenskim kanalom, je sčasoma bolj nagnjen k zlomu." },
    { h: "Kaj doda vlaknasti čep" },
    { p: "Če manjka velik del naravne strukture zoba, se včasih pred krono v kanal namesti majhen vlaknasti čep." },
    { h: "Primerjava stroškov zdravljenja korenskega kanala z alternativo" },
    { p: "Izdrtje zoba in zamenjava z vsadkom je bistveno večji strošek." },
    { h: "Kaj zahtevati v svoji ponudbi" },
    { p: "Vprašajte, ali je ponudba samo za zdravljenje korenskega kanala ali vključuje naslednjo krono." },
  ]
},
{
  slug: "strosek-polne-proteze-istanbul-moznosti",
  title: "Strošek polne proteze v Istanbulu: Možnosti in cene",
  description: "Koliko običajno stane polna proteza v Istanbulu, kako se primerja z možnostmi na vsadkih.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Tradicionalna polna proteza je ena od dostopnejših možnosti" },
    { p: "Polna snemna proteza za en lok običajno stane približno 700-900€ v Istanbulu." },
    { h: "Zakaj stane manj kot možnosti na vsadkih" },
    { p: "Tradicionalna proteza ne vključuje operacije vsadka — namesti se neposredno na dlesni." },
    { h: "Kompromis, ki ga je vredno razumeti pred odločitvijo" },
    { p: "Snemna proteza sčasoma zahteva več prilagoditev." },
    { h: "Nočna opornica je povezan, ločen strošek" },
    { p: "Če stiskate zobe, nočna opornica v vsakem primeru ščiti vašo investicijo." },
    { h: "Kako se to primerja z All-on-4" },
    { p: "All-on-4 vnaprej stane precej več, predvsem zaradi operacije vsadka." },
    { h: "Kaj vključuje pravilna ponudba proteze" },
    { p: "Popolna ponudba bi morala navesti, ali gre za polno ali delno protezo." },
  ]
},
{
  slug: "cena-beljenja-zob-ena-seansa-vs-paket",
  title: "Cena beljenja zob: Ena seansa vs paket",
  description: "Koliko običajno stane profesionalno beljenje zob in zakaj se pogosto združuje z drugimi zdravljenji.",
  date: "2026-09-10",
  relatedTreatment: "beljenje-zob-istanbul",
  body: [
    { h: "Beljenje je ena od dostopnejših samostojnih zdravljenj" },
    { p: "Ena profesionalna seansa beljenja, vključno s predhodnim čiščenjem, običajno stane približno 130-170€ v Istanbulu." },
    { h: "Zakaj je pogosto vključeno skupaj z drugim delom" },
    { p: "Če delate tudi fasetke, se beljenje preostalih naravnih zob običajno opravi vnaprej." },
    { h: "Čiščenje zobnega kamna, ki je običajno vključeno" },
    { p: "Pravilna seansa beljenja običajno najprej vključuje odstranitev površinskega zobnega kamna." },
    { h: "Zakaj se rezultati razlikujejo med pacienti" },
    { p: "Koliko svetlejši postanejo vaši zobje, je odvisno od vaše začetne barve." },
    { h: "Ena seansa vs več" },
    { p: "Večina pacientov vidi svoj popoln rezultat po eni seansi v kliniki." },
    { h: "Kaj potrditi pred rezervacijo" },
    { p: "Potrdite, ali predlagana cena vključuje čiščenje pred beljenjem." },
  ]
},
{
  slug: "strosek-dviga-sinusa-kdaj-je-potreben",
  title: "Strošek dviga sinusa: Kdaj je potreben in kaj doda",
  description: "Jasna razlaga, kdaj je dvig sinusa resnično potreben, in koliko običajno stane.",
  date: "2026-09-10",
  relatedTreatment: "dvig-sinusa-istanbul",
  body: [
    { h: "Dvig sinusa se doda le, ko vaše skeniranje to resnično pokaže" },
    { p: "To ni zdravljenje, ki bi ga nekdo izbral vnaprej — doda se k načrtu vsadkov le, ko 3D skeniranje pokaže nezadostno višino kosti." },
    { h: "Koliko običajno stane standarden dvig sinusa" },
    { p: "Dvig sinusa, ko je potreben, običajno doda približno 350-450€ k načrtu zdravljenja z vsadki." },
    { h: "Zakaj nekateri primeri to resnično potrebujejo, drugi pa ne" },
    { p: "Po tem, ko zob nekaj časa manjka, se lahko votlina sinusa postopoma razširi." },
    { h: "Razlika med \"zaprtim\" in \"odprtim\" dvigom sinusa" },
    { p: "Zaprt dvig sinusa je manjša, manj invazivna tehnika, ki se uporablja, ko je potrebna le majhna dodatna višina." },
    { h: "Zakaj to vpliva ne le na ceno, ampak tudi na vaš časovni okvir zdravljenja" },
    { p: "Če je potreben odprt dvig sinusa, to običajno doda nekaj mesecev celotnemu časovnemu okviru." },
    { h: "Iskren zaključek" },
    { p: "Ne boste vedeli, ali potrebujete dvig sinusa, dokler vaš primer resnično ni pregledan s 3D skeniranjem." },
  ]
},
{
  slug: "znamke-zobnih-vsadkov-zakaj-vplivajo-na-ceno",
  title: "Znamke zobnih vsadkov: Zakaj tako močno vplivajo na ceno",
  description: "Zakaj je lahko isti postopek vsadka zelo različno ovrednoten glede na uporabljen sistem vsadkov.",
  date: "2026-09-10",
  relatedTreatment: "zobni-vsadki-istanbul",
  body: [
    { h: "Vsi vsadki niso isti izdelek" },
    { p: "Vsadek je titanov vijak, ki ga izdeluje določeno podjetje z lastnimi raziskavami." },
    { h: "Kaj običajno loči premium sistem od dostopnejšega" },
    { p: "Premium sistemi vsadkov imajo običajno daljšo zgodovino objavljenih dolgoročnih kliničnih študij." },
    { h: "Zakaj je to pomembno, če na koncu obiščete drugega zobozdravnika" },
    { p: "Široko priznano mednarodno znamko je za drugo kliniko običajno lažje najti v delih." },
    { h: "To ne pomeni, da je dostopnejša možnost slaba izbira" },
    { p: "Tako premium kot dostopnejši sistemi vsadkov so legitimne medicinske naprave z oznako CE." },
    { h: "Cenovna razlika v praksi" },
    { p: "Razlika je običajno okoli 30-40% na vsadek." },
    { h: "Edino vprašanje, ki je resnično pomembno" },
    { p: "Vprašajte katero koli kliniko natančno, katero znamko vsadka ponuja." },
  ]
},
{
  slug: "zakaj-so-zobozdravstvene-cene-v-turciji-tako-nizje",
  title: "Zakaj so zobozdravstvene cene v Turčiji tako veliko nižje? Resnična razlaga",
  description: "Resnični ekonomski razlogi, zakaj zobozdravstveno zdravljenje v Turčiji stane manj.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Ne gre za to, da bi bila zobozdravstvena oskrba nižje kakovosti" },
    { p: "Cenovna razlika med Turčijo in Zahodno Evropo izhaja iz več kombiniranih dejavnikov." },
    { h: "Življenjski stroški in splošni stroški klinike" },
    { p: "Najemnine in plače osebja so strukturno nižje v Turčiji kot v Londonu ali Berlinu." },
    { h: "Menjalni tečaji delujejo v korist mednarodnih pacientov" },
    { p: "Ker so stroški klinike večinoma v turških lirah, menjalni tečaji ojačajo cenovno prednost." },
    { h: "Vladna podpora sektorju zdravstvenega turizma" },
    { p: "Turška vlada je aktivno vlagala v pozicioniranje države kot destinacije zdravstvenega turizma." },
    { h: "Večji obseg pacientov spreminja ekonomijo" },
    { p: "Klinike, ki vidijo veliko mednarodnih pacientov, lahko vlagajo v lastne laboratorije." },
    { h: "Kaj to ne pomeni" },
    { p: "Nižja cena ne pomeni samodejno nižjih standardov." },
  ]
},
{
  slug: "je-zobozdravstveni-turizem-v-turciji-varen",
  title: "Je zobozdravstveni turizem v Turčiji varen? Kaj dejansko kažejo podatki",
  description: "Dejanski pregled varnosti zobozdravstvenega turizma v Turčiji — regulacija za njim, obseg industrije in kaj dejansko ščiti paciente.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "To je prvo vprašanje, ki ga postavi skoraj vsak potencialni pacient" },
    { p: "Kratek odgovor je, da ima Turčija za to formalen, državno reguliran okvir." },
    { h: "Regulativni okvir je bil okrepljen leta 2025" },
    { p: "Predpisi o zdravstvenem turizmu v Turčiji so bili okrepljeni aprila 2025." },
    { h: "Obseg industrije v resničnih številkah" },
    { p: "Po podatkih turškega Združenja za zdravstveni turizem je država leta 2025 sprejela več kot 1,39 milijona obiskovalcev." },
    { h: "Specifičen položaj Turčije v zobozdravstvenem turizmu" },
    { p: "Po podatkih Ministrstva za zdravje je Turčija samo leta 2023 sprejela več kot 400.000 zobozdravstvenih turistov." },
    { h: "Od česa je dejansko odvisna \"varnost\"" },
    { p: "Varnost v tem kontekstu ni lastnost države kot celote." },
    { h: "Kaj lahko sami preverite pred rezervacijo" },
    { p: "Zahtevajte USTYB certifikat klinike, preverite registracijo na portalu HealthTürkiye." },
  ]
},
{
  slug: "certifikat-mednarodnega-zdravstvenega-turizma-razlaga",
  title: "Turški certifikat pooblastila za mednarodni zdravstveni turizem (USTYB) razložen",
  description: "Kaj je USTYB certifikat dejansko, zakaj je pomemben, in kako preveriti, ali ga klinika resnično ima.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Certifikat, ki ločuje pooblaščeno kliniko od neregulirane" },
    { p: "USTYB certifikat izda turško Ministrstvo za zdravje posebej zdravstvenim ustanovam, pooblaščenim za zdravljenje mednarodnih pacientov." },
    { h: "Kaj mora klinika dejansko dokazati, da ga pridobi" },
    { p: "Klinike, ki iščejo to pooblastilo, morajo izpolnjevati opredeljene standarde." },
    { h: "Zakaj je ta specifičen certifikat pomembnejši od splošnih tržnih trditev" },
    { p: "USTYB certifikat je posebej povezan s preverljivo registracijo pri Ministrstvu za zdravje." },
    { h: "Povezava s portalom HealthTürkiye" },
    { p: "Pričakuje se tudi, da so pooblaščene klinike navedene na uradnem portalu." },
    { h: "Kaj dejansko vprašati kliniko pred rezervacijo" },
    { p: "Zahtevajte neposreden vpogled v certifikat, ne le logotip na spletni strani." },
    { h: "Zakaj je vredno preveriti to eno podrobnost" },
    { p: "Uglajena spletna stran in privlačne cene ne nadomestijo regulativne legitimnosti." },
  ]
},
{
  slug: "kako-preveriti-legitimnost-tuje-zobozdravstvene-klinike",
  title: "Kako dejansko preveriti, da je tuja zobozdravstvena klinika legitimna",
  description: "Praktičen kontrolni seznam za potrditev, da je tuja zobozdravstvena klinika pravilno certificirana in varna.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Preverjanje traja deset minut" },
    { p: "Večina legitimnih klinik pozdravlja ta vprašanja." },
    { h: "1. Zahtevajte USTYB certifikat" },
    { p: "Legitimna klinika vam bo neposredno pokazala ta dokument." },
    { h: "2. Preverite registracijo na portalu HealthTürkiye" },
    { p: "To je neodvisen način preverjanja trditev klinike." },
    { h: "3. Vprašajte, katere specifične znamke vsadkov se uporabljajo" },
    { p: "Specifična, imenovana znamka z dokumentirano proizvodno zgodovino je dober znak." },
    { h: "4. Vprašajte, ali je garancija pisna" },
    { p: "Ustna \"dosmrtna garancija\" pomeni malo brez pisnega dokumenta." },
    { h: "5. Iščite ISO certifikate" },
    { p: "Ti kažejo, da je klinika vložila v formalne procese." },
    { h: "6. Vprašajte, kdo dejansko načrtuje vaš primer" },
    { p: "Vaš načrt zdravljenja bi moral biti zgrajen iz vaših lastnih skeniranj." },
  ]
},
{
  slug: "kaj-se-zgodi-ce-gre-kaj-narobe-po-vrnitvi-domov",
  title: "Kaj se zgodi, če gre kaj narobe po vrnitvi domov?",
  description: "Neposreden pregled poooperativne nege in garancijske zaščite za paciente, ki potujejo v tujino na zobozdravstveno zdravljenje.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "To je skrb, ki stoji za skoraj vsakim obotavljanjem glede zdravljenja v tujini" },
    { p: "Klinika, ki je resnično pripravljena za mednarodne paciente, ima resnične odgovore na to." },
    { h: "Kaj določa pravi garancijski dokument" },
    { p: "Pravilna pisna garancija natančno določa, kaj je krito in za koliko časa." },
    { h: "Oddaljeno spremljanje, preden nekaj postane nujno" },
    { p: "Mnoge težave je mogoče najprej oceniti na daljavo." },
    { h: "Kdaj je dejansko potreben povratni obisk" },
    { p: "Za prave garancijske primere bi morala legitimna klinika kriti samo zdravljenje." },
    { h: "S čim lahko in ne morejo pomagati lokalni zobozdravniki v vaši državi" },
    { p: "Zobozdravnik v vaši domovini se običajno lahko spopade s pravimi nujnimi primeri." },
    { h: "Iskren odgovor" },
    { p: "Realistična večina celjenja vsadkov poteka brez zapletov." },
  ]
},
{
  slug: "zakaj-milijoni-pacientov-izbirajo-turcijo-za-zobozdravstveno-nego",
  title: "Zakaj milijoni pacientov izbirajo Turčijo za zobozdravstveno nego",
  description: "Resnični obseg zobozdravstvenega turizma v Turčijo in dejavniki, zaradi katerih se toliko mednarodnih pacientov odloči potovati tja.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Številke za trendom so večje, kot večina pričakuje" },
    { p: "Turčija je leta 2025 sprejela več kot 1,39 milijona obiskovalcev zdravstvenega turizma." },
    { h: "Specifičen položaj Turčije v svetovnem zobozdravstvenem turizmu" },
    { p: "Turčija je v enem letu sprejela več kot 400.000 zobozdravstvenih turistov." },
    { h: "Svetovni trg se dejansko širi" },
    { p: "Svetovni trg zobozdravstvenega turizma je bil leta 2024 ocenjen na približno 7,2 milijarde dolarjev." },
    { h: "Strošek je najpogosteje naveden razlog, redko pa edini" },
    { p: "Poleg cenovne razlike pacienti pogosto navajajo hitrejšo dostopnost terminov." },
    { h: "Infrastruktura je dozorela skupaj s povpraševanjem" },
    { p: "Vladne naložbe so celotno izkušnjo naredile precej bolj strukturirano." },
    { h: "Kaj ta trend pomeni za potencialnega pacienta" },
    { p: "Velika, uveljavljena industrija pomeni več konkurence in izbire." },
  ]
},
{
  slug: "nucleoss-vsadki-najbolj-ekonomicna-zanesljiva-izbira",
  title: "NucleOSS zobni vsadki: Najbolj ekonomična zanesljiva izbira v Turčiji",
  description: "Kaj so NucleOSS vsadki dejansko, zakaj so ena od dostopnejših izbir.",
  date: "2026-09-12",
  relatedTreatment: "zobni-vsadki-istanbul",
  body: [
    { h: "Domača turška znamka, ne neznana" },
    { p: "NucleOSS je bil ustanovljen leta 2001 v Izmirju, Turčija — prvi domači proizvajalec zobnih vsadkov v državi." },
    { h: "Zakaj je cenovno dostopnejši od uvoženih sistemov" },
    { p: "En vijak vsadka NucleOSS je običajno ovrednoten okoli 150-200€." },
    { h: "Iz česa je dejansko izdelan" },
    { p: "Vsadki NucleOSS so izdelani iz čistega titana." },
    { h: "Kje se uporablja izven Turčije" },
    { p: "NucleOSS je distribuiran v več kot 18 državah." },
    { h: "Kaj tukaj ne pomeni \"ekonomično\"" },
    { p: "Nižja cena ne pomeni, da vsadek ni reguliran — NucleOSS ima certifikat CE." },
    { h: "Komu ta izbira dejansko ustreza" },
    { p: "Za paciente, ki dajejo prednost stroškom, je to legitimna srednja pot." },
    { h: "Iskren kompromis, ki ga je vredno poznati" },
    { p: "V primerjavi s švicarskimi sistemi ima NucleOSS krajšo zgodovino publikacij." },
  ]
},
{
  slug: "nucleoss-24-let-turske-proizvodnje",
  title: "NucleOSS vsadki: Kaj dejansko pomeni 24 let turške proizvodnje",
  description: "Pregled proizvodne zgodovine NucleOSS in kaj dve desetletji neprekinjene proizvodnje povesta o zanesljivosti.",
  date: "2026-09-12",
  relatedTreatment: "zobni-vsadki-istanbul",
  body: [
    { h: "Dolgoživost kot proizvajalec je resničen signal" },
    { p: "Podjetje, ki neprekinjeno proizvaja od leta 2001, ima 24+ let resničnih kliničnih povratnih informacij." },
    { h: "Nabor izdelkov odraža resnično naložbo v raziskave in razvoj" },
    { p: "NucleOSS ponuja več linij vsadkov, zasnovanih za različne klinične situacije." },
    { h: "Izdelano v Turčiji, ne le sestavljeno" },
    { p: "Vsadki NucleOSS se proizvajajo domače v Izmirju." },
    { h: "Kaj \"stožčaste\" vs \"ravne\" zasnove vsadkov pomenijo za vas" },
    { p: "Različne oblike telesa vsadka ustrezajo različnim kostnim pogojem." },
    { h: "Vprašanje združljivosti komponent" },
    { p: "Širok združljiv ekosistem komponent pomeni dele, ki so na voljo leta pozneje." },
    { h: "Kako se to praktično primerja z izbiro novejše znamke" },
    { p: "Znamka s krajšo zgodovino preprosto ni imela toliko časa za dokazovanje dolgoročnih rezultatov." },
    { h: "Kaj to pomeni za vašo odločitev" },
    { p: "24-letna neprekinjena zgodovina NucleOSS je legitimen dejavnik v njeno korist." },
  ]
},
{
  slug: "cena-porcelanske-krone-istanbul-proracunska-izbira",
  title: "Cena porcelanske krone v Istanbulu: Tradicionalna, proračunska izbira",
  description: "Koliko običajno stane kovinsko-keramična krona, kako se razlikuje od cirkonija.",
  date: "2026-09-12",
  relatedTreatment: null,
  body: [
    { h: "Starejši, dobro uveljavljen tip krone — ne nazadovanje, drugačna izbira" },
    { p: "Kovinsko-keramične (PFM) krone se v zobozdravstvu uporabljajo že desetletja." },
    { h: "Koliko običajno stane porcelanska krona" },
    { p: "V Istanbulu PFM krona običajno stane približno 80-100€ na enoto." },
    { h: "Kako je dejansko zgrajena" },
    { p: "PFM krona ima kovinsko podstrukturo za trdnost." },
    { h: "Edini iskren kompromis, ki ga je vredno poznati" },
    { p: "Po mnogih letih lahko kovinski rob ob dlesni postane rahlo viden." },
    { h: "Kje porcelanske krone dejansko smiselne" },
    { p: "Za zadnje kočnike, kjer je krona redko vidna, je to razumna izbira." },
    { h: "Kje se cirkonij običajno raje uporablja" },
    { p: "Za sprednje, vidne zobe se večina zdaj nagiba k cirkoniju." },
    { h: "Kaj določa poštena ponudba" },
    { p: "Pravilna ponudba bi morala jasno navesti, ali gre za PFM ali cirkonij." },
  ]
},
{
  slug: "porcelan-vs-cirkonij-krone-katera-ustreza-vasemu-proracunu",
  title: "Porcelan vs cirkonij krone: Katera dejansko ustreza vašemu proračunu in primeru",
  description: "Neposredna, praktična primerjava med kovinsko-keramičnimi in cirkonijevimi kronami.",
  date: "2026-09-12",
  relatedTreatment: null,
  body: [
    { h: "Dve legitimni izbiri, ne izbira \"dobro vs slabo\"" },
    { p: "Tako kovinsko-keramične kot cirkonijeve krone so uveljavljene, zanesljive restavracije." },
    { h: "Cenovna razlika v praksi" },
    { p: "PFM krone stanejo običajno približno 80-100€, monolitni cirkonij približno 120-180€." },
    { h: "Trajnost: bližje kot večina domneva" },
    { p: "Oba tipa materiala sta resnično trajna, ko sta pravilno prilagojena." },
    { h: "Videz: kje se pokaže resnična razlika" },
    { p: "Največja prednost cirkonija je, da sploh ne vsebuje kovine." },
    { h: "Smiseln način razmišljanja o mešanju obojega" },
    { p: "Mnogi pacienti razumno izberejo cirkonij za svoje vidne sprednje zobe." },
    { h: "Kaj določa, katero bo priporočil vaš zobozdravnik" },
    { p: "Vaš zobozdravnik bo upošteval, koliko naravne strukture zoba ostane." },
    { h: "Vprašanje, ki ga je treba postaviti pred odločitvijo" },
    { p: "Vprašajte svojega zobozdravnika neposredno, kateri material bi priporočil." },
  ]
}
];
