export const BLOG_HR = [

{
  slug: "all-on-4-ili-all-on-6-sto-vam-odgovara",
  title: "All-on-4 ili All-on-6: Što vam odgovara?",
  description: "I All-on-4 i All-on-6 daju vam potpun, fiksni zubni luk na implantatima. Evo stvarne razlike između njih i kako stomatolog odlučuje što odgovara vašoj čeljusti.",
  date: "2026-09-01",
  relatedTreatment: "all-on-4-5-6-implantati-istanbul",
  body: [
    { h: "Kratki odgovor" },
    { p: "All-on-4 i All-on-6 koriste istu osnovnu ideju — potpun luk fiksnih zuba podržan malim brojem implantata postavljenih u čeljust." },
    { h: "Zašto biste mogli trebati šest umjesto četiri?" },
    { p: "Odluka se obično svodi na kost. All-on-4 je posebno dizajniran za rad s kosti koju većina pacijenata već ima." },
    { h: "Mijenja li dodatni implantat rezultat koji osjećate svakodnevno?" },
    { p: "Ne. Bez obzira sjedi li vaš novi luk na četiri ili šest implantata, gotov most izgleda i osjeća se isto u vašim ustima." },
    { h: "Kako se odluka zapravo donosi" },
    { p: "Ispravno 3D skeniranje pokazuje vašem stomatologu točno koliko je kosti dostupno u svakom području vaše čeljusti." },
    { h: "Ukratko" },
    { p: "All-on-4 je standardna, dobro provjerena polazna točka za većinu pacijenata. All-on-6 postoji za ljude čija gustoća kosti stvarno zahtijeva dodatnu podršku." },
  ]
},
{
  slug: "cirkonij-ili-emax-odabir-pravog-materijala",
  title: "Cirkonij ili E-max: Odabir pravog materijala za vaš osmijeh",
  description: "Cirkonij i E-max su dva materijala iza većine modernih krunica i ljuski.",
  date: "2026-09-01",
  relatedTreatment: "monolitni-cirkonij-krunice-istanbul",
  body: [
    { h: "Dva različita zadatka, dva različita materijala" },
    { p: "Cirkonij i E-max su obje visokokvalitetne keramike, ali nisu zamjenjive." },
    { h: "Gdje cirkonij pobjeđuje" },
    { p: "Cirkonij je izuzetno čvrst i otporan na krhotine čak i na stražnjim zubima koji nose opterećenje." },
    { h: "Gdje E-max pobjeđuje" },
    { p: "E-max ima staklastu prozirnost koja bliže oponaša prirodnu caklinu." },
    { h: "Pa što je zapravo prikladno za vas?" },
    { p: "U praksi mnogi pacijenti dobiju mješavinu: E-max sprijeda za najbolji kozmetički rezultat." },
  ]
},
{
  slug: "koliko-dana-je-potrebno-u-istanbulu-za-stomatolosko-lijecenje",
  title: "Koliko dana je potrebno u Istanbulu za stomatološko liječenje?",
  description: "Odgovor u potpunosti ovisi o liječenju koje primate.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Ne postoji jedan odgovor — ovisi o liječenju" },
    { p: "Ovo je jedno od najčešće postavljanih pitanja za svakoga tko planira stomatološko liječenje u inozemstvu." },
    { h: "Liječenja u jednom posjetu (3–7 dana)" },
    { p: "Ljuske, krunice, izbjeljivanje zubi i Hollywood Smile transformacije bez implantata obično se dovrše u jednom putovanju." },
    { h: "Liječenja implantatima (dva posjeta, mjesecima razdvojena)" },
    { p: "Zubni implantati trebaju vremena da se spoje s čeljusnom kosti prije nego što se može pričvrstiti trajna krunica." },
    { h: "All-on-4 / All-on-6 konkretno" },
    { p: "Slučajevi implantata cijelog luka slijede isti obrazac dva posjeta." },
    { h: "Planiranje oko toga" },
    { p: "Ako kombinirate liječenja, dodatni kozmetički rad obično se planira oko rasporeda implantata." },
  ]
},
{
  slug: "ljuske-ili-krunice-koja-je-razlika",
  title: "Ljuske ili krunice: Koja je razlika, i što vam treba?",
  description: "Ljuske i krunice rješavaju različite probleme.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Temeljna razlika" },
    { p: "Ljuska pokriva samo prednju, vidljivu površinu zuba. Krunica pokriva cijeli zub, sa svih strana." },
    { h: "Kada je ljuska pravi alat" },
    { p: "Ljuske su dizajnirane za zube koji su kozmetički kompromitirani, ali strukturno zdravi." },
    { h: "Kada je krunica pravi alat" },
    { p: "Krunice su za strukturno oslabljene zube — veliku plombu koja je zakazala." },
    { h: "Mogu li se miješati u jednom osmijehu?" },
    { p: "Da, i to je uobičajeno. Potpuna transformacija osmijeha često kombinira oboje." },
    { h: "Što to znači za vašu konzultaciju" },
    { p: "Ako klinika predlaže krunice na zubima bez strukturnog oštećenja, razumno je pitati zašto." },
  ]
},
{
  slug: "sto-se-dogada-ako-nemate-dovoljno-kosti-za-implantate",
  title: "Što se događa ako nemate dovoljno kosti za implantate?",
  description: "Gubitak kosti automatski ne isključuje implantate.",
  date: "2026-09-01",
  relatedTreatment: "podizanje-sinusa-istanbul",
  body: [
    { h: "Gubitak kosti je uobičajen, ne diskvalificirajuć" },
    { p: "Nakon što zub nedostaje neko vrijeme, čeljusna kost u tom području prirodno se smanjuje." },
    { h: "Kako stomatolog zapravo provjerava" },
    { p: "3D skeniranje pokazuje točnu visinu i širinu dostupne kosti na mjestu implantata." },
    { h: "Opcija 1 — Kosi položaj implantata" },
    { p: "Tehnike poput All-on-4 djelomično su dizajnirane upravo oko ovog problema." },
    { h: "Opcija 2 — Koštani nadomjestak" },
    { p: "Kada stvarno nema dovoljno koštanog volumena, koštani nadomjestak dodaje materijal." },
    { h: "Opcija 3 — Podizanje sinusa" },
    { p: "Gornja stražnja čeljust nalazi se blizu sinusnih šupljina." },
    { h: "Zaključak" },
    { p: "„Nemam dovoljno kosti“ rijetko je kraj razgovora." },
  ]
},
{
  slug: "njega-nakon-implantacije-sto-se-dogada-nakon-povratka-kuci",
  title: "Njega nakon implantacije: Što se događa nakon povratka kući?",
  description: "Dobivanje implantata u inozemstvu ne znači da ste sami nakon slijetanja kući.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Njega nakon liječenja ne bi trebala prestati na aerodromu" },
    { p: "Uobičajena briga oko dobivanja implantata u inozemstvu je što se događa ako se nešto čini pogrešno nakon povratka." },
    { h: "Kako izgleda normalno cijeljenje" },
    { p: "Blaga bol i određeno oticanje u danima neposredno nakon operacije implantata su normalni." },
    { h: "Što uključuje pravi plan njege nakon liječenja" },
    { p: "Pisano jamstvo koje precizira što je pokriveno i koliko dugo." },
    { h: "Što pitati prije obvezivanja" },
    { p: "Prije rezervacije razumno je izravno pitati o neuspjehu implantata." },
    { h: "Realistična slika" },
    { p: "Većina cijeljenja implantata prolazi bez incidenata." },
  ]
},
{
  slug: "zahtijevaju-li-emax-ljuske-brusenje-zubi",
  title: "Zahtijevaju li E-max ljuske brušenje zubi?",
  description: "Jedna od najčešćih briga o ljuskama.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Iskren odgovor: ovisi o vašoj polaznoj točki" },
    { p: "E-max ljuske često se opisuju kao „minimalna priprema“, i to s dobrim razlogom." },
    { h: "Kada je potrebno vrlo malo ili nikakvo smanjenje" },
    { p: "Ako su vaši zubi već razumno dobro poravnati, tanka ljuska često se može zalijepiti uz malo uklanjanja cakline." },
    { h: "Kada je stvarno potrebna više pripreme" },
    { p: "Ako je zub značajno neporavnan, obično je potrebno određeno smanjenje cakline." },
    { h: "Zašto se ovo mora odlučiti prije putovanja" },
    { p: "Skeniranje digitalnog dizajna osmijeha stvarno odgovara na ovo pitanje za vaše specifične zube." },
    { h: "Što pitati" },
    { p: "Pitajte izravno: „koliko mog prirodnog zuba trebate ukloniti za ovaj dizajn?“" },
  ]
},
{
  slug: "koliko-vremena-treba-za-izradu-cirkonijske-krunice",
  title: "Koliko vremena treba za izradu cirkonijske krunice?",
  description: "Od vašeg prvog pregleda do gotove krunice.",
  date: "2026-09-02",
  relatedTreatment: "monolitni-cirkonij-krunice-istanbul",
  body: [
    { h: "Kratka verzija" },
    { p: "Jedna cirkonijska krunica obično traje nekoliko dana za dizajn, glodanje i završnu obradu." },
    { h: "Što se zapravo događa u to vrijeme" },
    { p: "Datoteka se šalje na glodanje gdje stroj izrezuje krunicu iz cirkonijskog bloka." },
    { h: "Zašto je interno glodanje važno za vaš raspored" },
    { p: "Klinike s vlastitim laboratorijem mogu dovršiti krunicu za dan ili dva." },
    { h: "Kada traje duže" },
    { p: "Više krunica prirodno oduzima više vremena vašeg posjeta." },
  ]
},
{
  slug: "sto-zapravo-ukljucuje-lijecenje-dizajna-osmijeha",
  title: "Što zapravo uključuje liječenje dizajna osmijeha?",
  description: "„Dizajn osmijeha“ i „Digitalni dizajn osmijeha“ koriste se slobodno.",
  date: "2026-09-02",
  relatedTreatment: "digitalni-dizajn-osmijeha-istanbul",
  body: [
    { h: "To je proces planiranja, ne jedna procedura" },
    { p: "Digitalni dizajn osmijeha sam po sebi nije liječenje — to je faza planiranja." },
    { h: "Korak 1 — Analiza vašeg lica, ne samo zubi" },
    { p: "Snimaju se fotografije i ponekad video vašeg osmijeha." },
    { h: "Korak 2 — 3D skeniranje i digitalni maket" },
    { p: "Intraoralno skeniranje gradi 3D model vaših zubi." },
    { h: "Korak 3 — Utvrđivanje koja su liječenja stvarno potrebna" },
    { p: "Vaš stomatolog određuje kombinaciju liječenja koja će to postići." },
    { h: "Korak 4 — Fizički maket u ustima" },
    { p: "Mnoge klinike mogu vam pokazati privremenu verziju dizajna izravno na vašim zubima." },
    { h: "Zašto je ovo važno" },
    { p: "Bez digitalnog skeniranja vjerojatno dobivate standardni kozmetički paket." },
  ]
},
{
  slug: "hollywood-smile-nasuprot-ljuskama-stvarna-razlika",
  title: "Hollywood Smile nasuprot ljuskama: Koja je stvarna razlika?",
  description: "„Hollywood Smile“ nije zaseban materijal od ljuski.",
  date: "2026-09-02",
  relatedTreatment: "hollywood-smile-istanbul",
  body: [
    { h: "Hollywood Smile je rezultat, ne materijal" },
    { p: "„Ljuske“ opisuju specifičnu restauraciju. „Hollywood Smile“ opisuje širi kozmetički cilj." },
    { h: "Dakle Hollywood Smile može koristiti ljuske, ili možda ne" },
    { p: "Rezultat se može postići ljuskama, krunicama ili kombinacijom." },
    { h: "Zašto ova razlika ima značaj pri usporedbi ponuda" },
    { p: "Usporedite konkretno koji materijali i koliko zubi je uključeno." },
    { h: "Što zapravo određuje jesu li ljuske pravi izbor" },
    { p: "Ovo se vraća na stanje specifičnog zuba." },
  ]
},
{
  slug: "invisalign-nasuprot-tradicionalnim-aparaticima-sto-odabrati",
  title: "Invisalign nasuprot tradicionalnim aparatićima: Što odabrati?",
  description: "Prozirne udlage i metalni aparatići oboje ravnaju zube.",
  date: "2026-09-02",
  relatedTreatment: "invisalign-prozirne-udlage-istanbul",
  body: [
    { h: "Oboje funkcionira — pitanje je prikladnost" },
    { p: "Prozirne udlage i tradicionalni aparatići pomiču zube kontroliranim pritiskom." },
    { h: "Gdje prozirne udlage dobro funkcioniraju" },
    { p: "Blaga do umjerena zbijenost obično je dobro prikladna za udlage." },
    { h: "Gdje su tradicionalni aparatići i dalje bolji alat" },
    { p: "Složeniji pokreti bolje se rješavaju fiksnim aparatićima." },
    { h: "Faktor discipline" },
    { p: "Udlage funkcioniraju samo ako se nose 20-22 sata dnevno." },
    { h: "Kako se odluka zapravo donosi" },
    { p: "3D skeniranje pokazuje koji pokreti su vam stvarno potrebni." },
  ]
},
{
  slug: "zubni-most-ili-implantat-kako-odabrati",
  title: "Zubni most ili implantat: Kako odabrati",
  description: "Oba zamjenjuju nedostajući zub, ali funkcioniraju vrlo različito.",
  date: "2026-09-02",
  relatedTreatment: "zubni-most-istanbul",
  body: [
    { h: "Temeljna razlika" },
    { p: "Implantat izravno zamjenjuje nedostajući korijen zuba. Most zamjenjuje samo vidljivi zub." },
    { h: "Zašto je most često brži" },
    { p: "Most ne zahtijeva operaciju ili razdoblje cijeljenja." },
    { h: "Zašto je implantat često jači dugoročni izbor" },
    { p: "Implantat ne zahtijeva pripremu inače zdravih zubi." },
    { h: "Odlučujući faktor" },
    { p: "Ako susjedni zubi već trebaju krunice, most je učinkovit izbor." },
    { h: "Pošteno pitanje vrijedno postavljanja" },
    { p: "Pitajte kliniku izravno zašto preporučuju most." },
  ]
},
{
  slug: "sto-se-dogada-tijekom-lijecenja-korijenskog-kanala-korak-po-korak",
  title: "Što se događa tijekom liječenja korijenskog kanala, korak po korak",
  description: "Jasan, postupni prikaz liječenja korijenskog kanala.",
  date: "2026-09-02",
  relatedTreatment: "lijecenje-korijenskog-kanala-istanbul",
  body: [
    { h: "Zašto ova procedura ima lošiju reputaciju od iskustva" },
    { p: "Nelagoda obično dolazi od same infekcije, ne od procedure." },
    { h: "Korak 1 — Dijagnoza i rendgen" },
    { p: "Rendgen potvrđuje opseg infekcije." },
    { h: "Korak 2 — Lokalna anestezija" },
    { p: "Zub se anestezira prije bilo čega drugog." },
    { h: "Korak 3 — Uklanjanje inficiranog tkiva" },
    { p: "Inficirana pulpa uklanja se iz kanala." },
    { h: "Korak 4 — Čišćenje i dezinfekcija" },
    { p: "Prostor kanala se čisti i dezinficira." },
    { h: "Korak 5 — Zatvaranje zuba" },
    { p: "Kanal se puni biokompatibilnim materijalom." },
    { h: "Korak 6 — Obično zaštitna krunica" },
    { p: "Krunica se obično preporučuje nakon toga." },
    { h: "Kako se oporavak zapravo osjeća" },
    { p: "Blaga bol obično se kontrolira standardnim analgeticima." },
  ]
},

{
  slug: "znakovi-da-vam-mozda-treba-gingivektomija",
  title: "Znakovi da vam možda treba gingivektomija",
  description: "Gingivektomija nije namijenjena samo za „osmijeh s previše desni“.",
  date: "2026-09-02",
  relatedTreatment: "gingivektomija-istanbul",
  body: [
    { h: "Radi se o više od izgleda" },
    { p: "Gingivektomija se često spominje samo u kozmetičkom kontekstu, ali višak tkiva desni može biti i pravi problem oralnog zdravlja." },
    { h: "Znak 1 — Pri osmijehu pokazujete primjetno više desni nego zuba" },
    { p: "„Osmijeh s previše desni“, gdje je široka traka tkiva desni vidljiva iznad zubi, najčešće je prepoznat razlog." },
    { h: "Znak 2 — Vaša linija desni je neravna duž prednjih zubi" },
    { p: "Neravne razine mogu učiniti inače dobro oblikovane zube nesuglasnim." },
    { h: "Znak 3 — Višak tkiva desni otežava pravilno čišćenje zubi" },
    { p: "Tkivo koje se preklapa oko zubi može zadržavati plak na način koji je stvarno teško učinkovito četkati." },
    { h: "Znak 4 — Planirate ljuske i vaše razine desni su neravne" },
    { p: "Procjena desni često je dio ispravnog plana digitalnog dizajna osmijeha." },
    { h: "Što zapravo učiniti" },
    { p: "Nijedan od ovih znakova ne znači da je gingivektomija automatski ispravan odgovor upravo za vas." },
  ]
},
{
  slug: "pitanja-prije-odabira-klinike-u-inozemstvu",
  title: "Pitanja koja treba postaviti prije odabira stomatološke klinike u inozemstvu",
  description: "Praktičan kontrolni popis onoga što stvarno pitati prije rezervacije stomatološkog liječenja u drugoj zemlji.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Sama usporedba cijena ne govori puno" },
    { p: "Dvije klinike mogu ponuditi istu cijenu za „All-on-4“, a misliti na stvarno različite stvari." },
    { h: "1. Koju konkretnu marku implantata ili materijala koristite?" },
    { p: "Prave, etablirane marke imaju povijest proizvodnje koja se može pratiti." },
    { h: "2. Je li jamstvo pisano, i što točno pokriva?" },
    { p: "„Doživotno jamstvo“ trebalo bi precizirati što je uključeno." },
    { h: "3. Tko radi planiranje slučaja, i temelji li se na mojim vlastitim skeniranjima?" },
    { p: "Vaš plan liječenja trebao bi biti izgrađen iz vaših vlastitih 3D skeniranja." },
    { h: "4. Što se događa ako nešto treba pažnju nakon što odem kući?" },
    { p: "Klinika sigurna u vlastiti rad trebala bi imati jasan odgovor." },
    { h: "5. Je li klinika službeno ovlaštena za međunarodne pacijente?" },
    { p: "Konkretno u Turskoj, klinike koje liječe međunarodne pacijente trebale bi imati važeću dozvolu za međunarodni zdravstveni turizam." },
    { h: "6. Što je zapravo uključeno u navedenu cijenu?" },
    { p: "Pitajte konkretno uključuje li ponuda konzultaciju, sva skeniranja i kontrolne posjete." },
  ]
},
{
  slug: "koje-certifikate-bi-trebala-imati-stomatoloska-klinika-u-inozemstvu",
  title: "Koje certifikate bi stomatološka klinika u inozemstvu zapravo trebala imati?",
  description: "Certifikate i akreditacijske značke lako je pokazati i teško provjeriti samo s web stranice.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Nemaju svi certifikati istu težinu" },
    { p: "Web stranice klinika često prikazuju niz značaka i pečata." },
    { h: "Dozvola za međunarodni zdravstveni turizam (specifična za Tursku)" },
    { p: "U Turskoj klinike koje zakonito liječe međunarodne pacijente trebale bi imati ovu dozvolu od Ministarstva zdravstva." },
    { h: "ISO certifikati" },
    { p: "Ovo su opći standardi upravljanja kvalitetom, ne specifični za stomatologiju." },
    { h: "Certifikati proizvođača implantata" },
    { p: "Neke klinike pokazuju certifikate koji potvrđuju da su ovlašteni korisnici određene marke implantata." },
    { h: "Što zapravo učiniti s ovom informacijom" },
    { p: "Ne oslanjajte se isključivo na značke prikazane na web stranici." },
  ]
},
{
  slug: "koliko-zapravo-traju-cirkonijske-krunice",
  title: "Koliko zapravo traju cirkonijske krunice?",
  description: "Realistični pogled na vijek trajanja cirkonijskih krunica.",
  date: "2026-09-02",
  relatedTreatment: "monolitni-cirkonij-krunice-istanbul",
  body: [
    { h: "Opći raspon" },
    { p: "Dobro izrađene cirkonijske krunice obično traju 10 do 15 godina ili duže uz razumnu njegu." },
    { h: "Zašto monolitni cirkonij obično traje duže od starijih cirkonijskih krunica" },
    { p: "Starije cirkonijske krunice koristile su cirkonijsku jezgru s odvojenim slojem porculana." },
    { h: "Što zapravo skraćuje vijek trajanja krunice" },
    { p: "Neliječeno škripanje zubima nanosi ponavljanu prekomjernu silu na krunicu." },
    { h: "Što možete učiniti da traje duže" },
    { p: "Normalno četkanje i korištenje zubnog konca baš kao s prirodnim zubima." },
    { h: "Kada „neuspjeh“ zapravo nije o krunici" },
    { p: "Ako krunica treba biti zamijenjena nakon nekoliko godina, vrijedi razumjeti zašto." },
  ]
},
{
  slug: "monolitni-nasuprot-slojevitom-cirkoniju-koja-je-razlika",
  title: "Monolitni nasuprot slojevitom cirkoniju: Koja je razlika?",
  description: "Oboje se zove „cirkonijske krunice“, ali konstrukcija je stvarno drugačija.",
  date: "2026-09-02",
  relatedTreatment: "monolitni-cirkonij-krunice-istanbul",
  body: [
    { h: "Isti osnovni materijal, drugačija konstrukcija" },
    { p: "I monolitni i slojeviti cirkonij koriste cirkonijev oksid." },
    { h: "Slojeviti cirkonij" },
    { p: "Slojevita krunica ima cirkonijsku jezgru za čvrstoću, okrunjenu odvojenim slojem porculana." },
    { h: "Monolitni cirkonij" },
    { p: "Monolitna krunica se u potpunosti glodav iz jednog cirkonijskog bloka." },
    { h: "Gdje se svaki tipično koristi" },
    { p: "Monolitni cirkonij općenito se preferira za stražnje zube." },
    { h: "Zaključak" },
    { p: "Ako je izdržljivost protiv krhotina vaš glavni prioritet, monolitni cirkonij je općenito sigurniji izbor." },
  ]
},
{
  slug: "mogu-li-se-implantati-i-ljuske-kombinirati-u-jednom-putovanju",
  title: "Mogu li se implantati i ljuske kombinirati u jednom putovanju?",
  description: "Kombiniranje liječenja je uobičajeno, ali raspored cijeljenja implantata mijenja način planiranja.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Da, ali raspored implantata određuje tempo" },
    { p: "Kombiniranje implantata s ljuskama uobičajen je zahtjev." },
    { h: "Kako se to obično planira" },
    { p: "Tijekom prvog posjeta postavljaju se implantati." },
    { h: "Zašto je vrijeme izbjeljivanja ovdje posebno važno" },
    { p: "Ako također dobivate ljuske, izbjeljivanje bi trebalo biti prije njihove izrade." },
    { h: "Što bi vam trebao reći kombinirani plan liječenja" },
    { p: "Ispravan plan detaljno opisuje što se događa svaki dan." },
    { h: "Praktična prednost kombiniranja" },
    { p: "Kombiniranje liječenja stvarno smanjuje ukupno putovanje." },
  ]
},
{
  slug: "upravljanje-strahom-od-stomatologa-tijekom-putovanja-na-lijecenje",
  title: "Upravljanje strahom od stomatologa tijekom putovanja na liječenje",
  description: "Strah od stomatologa ne nestaje samo zato što putujete na liječenje.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "To je uobičajena briga, ne neuobičajena" },
    { p: "Strah od stomatologa izuzetno je čest, a putovanje u inozemstvo može dodati dodatni sloj stresa." },
    { h: "Stvarno dostupne opcije sedacije" },
    { p: "Većina klinika nudi opcije osim samo lokalne anestezije." },
    { h: "Komunikacija je važnija nego što ljudi očekuju" },
    { p: "Tjeskoba je često gora kada u potpunosti ne razumijete što se događa." },
    { h: "Planiranje pomaže više nego što većina ljudi shvaća" },
    { p: "Poznavanje vašeg rasporeda unaprijed smanjuje neizvjesnost." },
    { h: "Razumno je reći ovo unaprijed" },
    { p: "Izravno reći koordinatoru o strahu daje im priliku planirati oko toga." },
  ]
},
{
  slug: "sto-pripremiti-prije-stomatoloskog-lijecenja-u-inozemstvu",
  title: "Što pripremiti prije stomatološkog liječenja u inozemstvu",
  description: "Praktičan kontrolni popis prije putovanja.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Prije nego što bilo što rezervirate" },
    { p: "Nabavite pisani plan liječenja na temelju vlastitih fotografija ili skeniranja." },
    { h: "Medicinske informacije koje treba imati spremne" },
    { p: "Popis lijekova, alergija i relevantnih zdravstvenih stanja treba podijeliti prije putovanja." },
    { h: "Postojeći stomatološki zapisi" },
    { p: "Nedavne rendgenske snimke mogu ubrzati planiranje." },
    { h: "Praktična logistika putovanja" },
    { p: "Potvrdite oba datuma posjeta unaprijed za slučajeve implantata." },
    { h: "Pitanja na koja treba dobiti odgovor prije leta" },
    { p: "Ukupan broj potrebnih posjeta." },
    { h: "Što zapravo spakirati" },
    { p: "Popis lijekova, udobnu odjeću." },
  ]
},
{
  slug: "krunica-ili-plomba-koja-je-razlika",
  title: "Krunica ili plomba: Koja je razlika, i kada vam treba koja?",
  description: "Oboje popravlja oštećeni zub, ali na vrlo različitim razinama oštećenja.",
  date: "2026-09-03",
  relatedTreatment: "monolitni-cirkonij-krunice-istanbul",
  body: [
    { h: "Sve se svodi na to koliko zdravog zuba ostaje" },
    { p: "Plomba popravlja malo do umjereno oštećeno područje, obično od karijesa." },
    { h: "Kada je plomba dovoljna" },
    { p: "Mali do srednji karijesi, uhvaćeni razumno rano, obično se dobro rješavaju plombom." },
    { h: "Kada plomba nije dovoljna" },
    { p: "Ako je karijes opsežan, ili je zub napukao, krunica umjesto toga pruža puno pokriće." },
    { h: "Zašto postavljanje plombe gdje je potrebna krunica ne traje" },
    { p: "Prevelika plomba u odnosu na preostalu strukturu zuba vjerojatnije će napuknuti." },
    { h: "Iskren odgovor dobrog stomatologa" },
    { p: "Stomatolog koji izravno gleda rendgen i sam zub može reći što vam treba." },
  ]
},
{
  slug: "cijena-all-on-4-sto-je-zapravo-ukljuceno",
  title: "Cijena All-on-4: Što je zapravo uključeno u cijenu?",
  description: "All-on-4 ponude mogu izgledati vrlo različito između klinika iz razloga koji nemaju veze s kvalitetom.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-implantati-istanbul",
  body: [
    { h: "Zašto ista procedura dobiva vrlo različite ponude" },
    { p: "Dvije klinike mogu obje ponuditi „All-on-4“ po vrlo različitim cijenama." },
    { h: "Marka i kvaliteta implantata" },
    { p: "Etablirane, klinički dokazane marke implantata obično koštaju više." },
    { h: "Što je uključeno u navedenu cijenu" },
    { p: "Pitajte konkretno uključuje li ponuda početnu konzultaciju i 3D skeniranje." },
    { h: "Je li koštani nadomjestak ili podizanje sinusa vjerojatno, i je li uključeno" },
    { p: "Ako vaš slučaj možda treba dodatni koštani rad, ponuda prije pregleda skeniranja to ne može uzeti u obzir." },
    { h: "Uvjeti praćenja i jamstva" },
    { p: "Provjerite jesu li kontrole nakon njege i jamstveni period uključeni u cijenu." },
    { h: "Jedno pitanje koje razjašnjava većinu ovoga" },
    { p: "Pitajte izravno: „što bi promijenilo ovu konačnu cijenu?“" },
  ]
},
{
  slug: "mogu-li-se-postaviti-zubni-implantati-ako-pusite",
  title: "Mogu li se postaviti zubni implantati ako pušite?",
  description: "Pušenje automatski ne isključuje implantate, ali je pravi faktor koji stomatolozi shvaćaju ozbiljno.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-implantati-istanbul",
  body: [
    { h: "Pušenje je faktor rizika, ne automatska diskvalifikacija" },
    { p: "Mnogi pušači dobiju uspješne, dugotrajne zubne implantate." },
    { h: "Zašto je razdoblje cijeljenja ovdje toliko važno" },
    { p: "Osteointegracija ovisi o zdravoj opskrbi krvlju tog područja." },
    { h: "Što stomatolozi zapravo preporučuju" },
    { p: "Mnoge klinike preporučuju prestanak pušenja, ili barem značajno smanjenje." },
    { h: "Iskrenost o tome je važna" },
    { p: "Reći svom stomatologu da pušite omogućuje mu da pravilno planira oko toga." },
    { h: "Zaključak" },
    { p: "Pušenje čini liječenje implantatima nešto rizičnijim, ne nemogućim." },
  ]
},
{
  slug: "sto-je-osteointegracija-i-zasto-je-vazna-za-implantate",
  title: "Što je osteointegracija, i zašto je važna za implantate?",
  description: "Pojam iza toga zašto liječenje implantatima traje mjesecima, ne danima.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-implantati-istanbul",
  body: [
    { h: "Riječ koja objašnjava raspored implantata s dva posjeta" },
    { p: "Osteointegracija je proces kojim se titanski implantat fizički spaja s okolnom čeljusnom kosti." },
    { h: "Zašto konkretno titan" },
    { p: "Titan ima stvarno neobično svojstvo: žive koštane stanice rastu izravno na njegovoj površini." },
    { h: "Koliko vremena traje" },
    { p: "Osteointegracija tipično traje nekoliko mjeseci, često se navodi kao otprilike tri do šest mjeseci." },
    { h: "Što se događa ako se ovaj korak požuri" },
    { p: "Opterećivanje implantata konačnom restauracijom prije završetka osteointegracije riskira." },
    { h: "Zašto je ovo važno pri usporedbi klinika" },
    { p: "Klinika koja obećava potpuno trajnu implantatnu restauraciju u jednom kratkom posjetu radi s neobično jednostavnim slučajem ili preskače korak." },
  ]
},
{
  slug: "koliko-koste-zubni-implantati-u-turskoj",
  title: "Koliko koštaju zubni implantati u Turskoj?",
  description: "Realističan pregled troškova zubnih implantata u Turskoj, zašto se cijene razlikuju među klinikama i što biste zapravo trebali usporediti prije odluke.",
  date: "2026-09-10",
  relatedTreatment: "zubni-implantati-istanbul",
  body: [
    { h: "Ne postoji jedan broj, a svaka klinika koja daje cijenu prije nego što vidi vaš slučaj nagađa" },
    { p: "Cijena implantata ovisi o marki korištenog implantata, potrebi za koštanim presatkom i broju potrebnih implantata." },
    { h: "Marka implantata najveći je pojedinačni faktor cijene" },
    { p: "Klinike obično nude više od jednog implantacijskog sustava, a razlika u cijeni između njih je stvarna — često 30-40% između ekonomičnog i premium sustava." },
    { h: "Koliko obično košta jedan implantat" },
    { p: "Za jedan zubni implantat (samo sam vijak, bez krunice koja dolazi iznad), cijene u klinikama u Istanbulu obično se kreću od oko 300€ na pristupačnijem kraju do 450€+ za premium sustave." },
    { h: "Zašto je krunica zasebna stavka" },
    { p: "Implantat zamjenjuje korijen; krunica zamjenjuje vidljivi zub. Potpuna ponuda za \"implantat + krunicu\" trebala bi jasno prikazati oboje." },
    { h: "Što zapravo mijenja ukupan iznos" },
    { p: "Koštani presadak ili podizanje sinusa, ako to vaš slučaj zahtijeva, dodaje se ukupnom iznosu — to zaista ovisi o stanju vaše čeljusne kosti." },
    { h: "Kako dobiti stvaran broj za vaš slučaj" },
    { p: "Pošaljite nedavni panoramski rendgen ako ga imate, ili planirajte 3D skeniranje tijekom konzultacija." },
  ]
},
{
  slug: "cijena-all-on-4-turska-vs-uk-sad",
  title: "Cijena All-on-4 u Turskoj vs UK i SAD: Što zapravo uspoređujete",
  description: "Zašto se ponude All-on-4 toliko razlikuju među zemljama, i što zapravo uzrokuje razliku osim troška rada.",
  date: "2026-09-10",
  relatedTreatment: "all-on-4-5-6-implantati-istanbul",
  body: [
    { h: "Razlika je stvarna, ali nije samo \"jeftinija radna snaga\"" },
    { p: "All-on-4 u Turskoj obično se nudi za otprilike trećinu do pola tipične cijene u UK-u ili SAD-u." },
    { h: "Što obično uključuje slučaj potpunog luka u Turskoj" },
    { p: "Potpuni fiksni luk na četiri implantata, uključujući operaciju, obično košta od ~2900€ po luku s pristupačnijim sustavom do 3400€ s premium sustavom." },
    { h: "Zašto All-on-5 ili All-on-6 košta više" },
    { p: "Dodavanje petog ili šestog implantata povećava ukupan iznos za otprilike 300-450€ po dodatnom implantatu." },
    { h: "Što UK i SAD cijene mogu uključivati, a što ponuda iz Turske nema" },
    { p: "Usporedite što je zapravo uključeno u svaku ponudu: uključuje li UK cijena kontrolni posjet?" },
    { h: "Stvarno razmatranje troška koje većina propušta" },
    { p: "Čak i uz uračunate letove i smještaj, ukupan iznos za slučaj potpunog luka u inozemstvu obično ostaje znatno niži." },
    { h: "Što pitati prije usporedbe dviju ponuda" },
    { p: "Pitajte svaku kliniku koja marka implantata se koristi i što zapravo pokriva jamstvo." },
  ]
},
{
  slug: "cijena-laminiranih-ljuski-istanbul",
  title: "Cijena laminiranih ljuski u Istanbulu: Što je zapravo uključeno",
  description: "Jasan pregled onoga što određuje cijenu laminiranih ljuski u Istanbulu, i što bi trebala uključivati ispravna ponuda.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Cijena se obično navodi po zubu, ne po osmijehu" },
    { p: "Cijena laminiranih ljuski gotovo je uvijek po pojedinačnom zubu, tako da ukupan iznos u potpunosti ovisi o tome koliko zuba je uključeno u dizajn vašeg osmijeha." },
    { h: "Koliko obično košta jedna ljuska" },
    { p: "Cijena po zubu za laminirane ljuske u Istanbulu obično se kreće u rasponu od otprilike 300-400€." },
    { h: "Zašto materijal utječe na cijenu i rezultat" },
    { p: "Tanki porculanski laminati zahtijevaju precizno, minimalno pripremanje zuba i vještog keramičara." },
    { h: "Što bi trebalo biti uključeno u ponuđenu cijenu" },
    { p: "Ispravna ponuda za ljuske trebala bi uključivati konzultaciju digitalnog dizajna osmijeha i cementiranje." },
    { h: "Faza privremenih ljuski" },
    { p: "Između pripremljenih zuba i postavljanja konačnih ljuski obično nosite privremene ljuske nekoliko dana." },
    { h: "Zašto najjeftinija ponuda nije automatski najbolja vrijednost" },
    { p: "Znatno niža cijena po zubu od svega ostalog što vidite zaslužuje izravno pitanje." },
  ]
},
{
  slug: "trosak-hollywood-smile-sto-odredjuje-cijenu",
  title: "Trošak Hollywood Smile-a: Što određuje konačnu cijenu",
  description: "Cijena Hollywood Smile-a varira više nego gotovo bilo koji drugi tretman jer nije jedan fiksni postupak.",
  date: "2026-09-10",
  relatedTreatment: "hollywood-smile-istanbul",
  body: [
    { h: "\"Hollywood Smile\" opisuje rezultat, a ne fiksni cjenik" },
    { p: "Budući da se Hollywood Smile može postići ljuskama, krunicama ili mješavinom oboje, dvije klinike s vrlo različitim ukupnim iznosima mogu zapravo određivati cijenu različitih planova liječenja." },
    { h: "Broj uključenih zuba najveći je pojedinačni faktor" },
    { p: "Potpuna transformacija Hollywood Smile obično pokriva gornjih vidljivih 16-20 zuba." },
    { h: "Ljuske vs krunice mijenjaju cijenu po zubu" },
    { p: "Laminirane ljuske i potpune cirkonijeve krunice određuju se cijenom drugačije." },
    { h: "Što dodaje potpuni digitalni dizajn osmijeha" },
    { p: "Ispravan plan Hollywood Smile počinje s 3D digitalnim dizajnom osmijeha." },
    { h: "Zašto se dva \"paketa Hollywood Smile\" mogu razlikovati za tisuće eura" },
    { p: "Najveće varijacije dolaze od broja uključenih zuba i klase materijala." },
    { h: "Pitanje koje vrijedi postaviti izravno" },
    { p: "Pitajte točno koliko zuba je uključeno u ponuđenu cijenu." },
  ]
},
{
  slug: "cijena-cirkonijeve-krunice-jeftinije-ne-znaci-uvijek-bolje",
  title: "Cijena cirkonijeve krunice: Jeftinije ne znači uvijek bolje",
  description: "Što zapravo utječe na cijenu cirkonijeve krunice, i zašto najniža ponuda ponekad može koštati više dugoročno.",
  date: "2026-09-10",
  relatedTreatment: "monolitni-cirkonij-krunice-istanbul",
  body: [
    { h: "Osnovna cijena obično je skromna — nakupljaju se upravo dodaci" },
    { p: "Jedna cirkonijeva krunica sama po sebi jedna je od pristupačnijih restorativnih opcija — obično 120-180€ po jedinici u Istanbulu." },
    { h: "Monolitni vs slojeviti cirkonij" },
    { p: "Monolitni cirkonij, glodan iz jednog čvrstog bloka, sklon je otpornijem na lomljenje." },
    { h: "Što dodaje titanska baza" },
    { p: "Posebno za krunice na implantatima, titanska baza dodaje značajan iznos trošku." },
    { h: "Zašto puno jeftinija ponuda zaslužuje izravno pitanje" },
    { p: "Pitajte konkretno je li riječ o monolitnom ili slojevitom cirkoniju, i koje jamstveno razdoblje je uključeno." },
    { h: "Kako broj krunica brzo mijenja ukupan iznos" },
    { p: "Budući da je cijena po jedinici, uzmite jediničnu cijenu i pomnožite je sami." },
    { h: "Što zapravo određuje poštena ponuda" },
    { p: "Pouzdana ponuda navodi cijenu po krunici, specifičnu vrstu cirkonija i jamstveno razdoblje." },
  ]
},
{
  slug: "trosak-lijecenja-korijenskog-kanala-turska",
  title: "Trošak liječenja korijenskog kanala u Turskoj: Što očekivati",
  description: "Izravan pregled onoga koliko obično košta liječenje korijenskog kanala u Turskoj, i što vam još može trebati.",
  date: "2026-09-10",
  relatedTreatment: "lijecenje-korijenskog-kanala-istanbul",
  body: [
    { h: "Samo liječenje korijenskog kanala jedna je od pristupačnijih procedura" },
    { p: "Samostalno, liječenje korijenskog kanala u Istanbulu obično košta otprilike 130-170€ po zubu." },
    { h: "Zašto kutnjaci mogu koštati više od prednjih zuba" },
    { p: "Zub s više kanala treba dulje vrijeme za temeljito čišćenje i punjenje." },
    { h: "Dodatni trošak koji ljudi ne planiraju uvijek: krunica nakon toga" },
    { p: "Zub koji je prošao liječenje korijenskog kanala skloniji je pucanju tijekom vremena." },
    { h: "Što dodaje vlaknasti klin" },
    { p: "Ako nedostaje velik dio prirodne strukture zuba, ponekad se prije krunice u kanal postavlja mali vlaknasti klin." },
    { h: "Usporedba troška liječenja korijenskog kanala s alternativom" },
    { p: "Vađenje zuba i zamjena implantatom znatno je veći trošak." },
    { h: "Što tražiti u svojoj ponudi" },
    { p: "Pitajte je li ponuda samo za liječenje korijenskog kanala ili uključuje sljedeću krunicu." },
  ]
},
{
  slug: "trosak-potpune-proteze-istanbul-opcije",
  title: "Trošak potpune proteze u Istanbulu: Opcije i cijene",
  description: "Koliko obično košta potpuna proteza u Istanbulu, kako se uspoređuje s opcijama na implantatima.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Tradicionalna potpuna proteza jedna je od pristupačnijih opcija" },
    { p: "Potpuna mobilna proteza za jedan luk obično košta otprilike 700-900€ u Istanbulu." },
    { h: "Zašto košta manje od opcija na implantatima" },
    { p: "Tradicionalna proteza ne uključuje operaciju implantata — postavlja se izravno na desni." },
    { h: "Kompromis koji vrijedi razumjeti prije odluke" },
    { p: "Mobilna proteza zahtijeva više prilagodbi tijekom vremena." },
    { h: "Noćna udlaga povezan je, zaseban trošak" },
    { p: "Ako škripite zubima, noćna udlaga u svakom slučaju štiti vašu investiciju." },
    { h: "Kako se ovo uspoređuje s All-on-4" },
    { p: "All-on-4 iznimno više košta unaprijed, uglavnom zbog operacije implantata." },
    { h: "Što uključuje ispravna ponuda proteze" },
    { p: "Potpuna ponuda trebala bi navesti je li riječ o potpunoj ili djelomičnoj protezi." },
  ]
},
{
  slug: "cijena-izbjeljivanja-zuba-jedan-tretman-vs-paket",
  title: "Cijena izbjeljivanja zuba: Jedan tretman vs paket",
  description: "Koliko obično košta profesionalno izbjeljivanje zuba, i zašto se često kombinira s drugim tretmanima.",
  date: "2026-09-10",
  relatedTreatment: "izbjeljivanje-zuba-istanbul",
  body: [
    { h: "Izbjeljivanje je jedan od pristupačnijih samostalnih tretmana" },
    { p: "Jedan profesionalni tretman izbjeljivanja, uključujući prethodno čišćenje, obično košta otprilike 130-170€ u Istanbulu." },
    { h: "Zašto se često uključuje zajedno s drugim radom" },
    { p: "Ako također radite ljuske, izbjeljivanje preostalih prirodnih zuba obično se radi unaprijed." },
    { h: "Čišćenje zubnog kamenca koje je obično uključeno" },
    { p: "Ispravan tretman izbjeljivanja obično prvo uključuje uklanjanje površinskog zubnog kamenca i plaka." },
    { h: "Zašto se rezultati razlikuju među pacijentima" },
    { p: "Koliko svjetliji postaju vaši zubi ovisi o vašoj početnoj nijansi." },
    { h: "Jedan tretman vs više" },
    { p: "Većina pacijenata vidi svoj potpuni rezultat nakon jednog tretmana u klinici." },
    { h: "Što potvrditi prije rezervacije" },
    { p: "Potvrdite uključuje li ponuđena cijena čišćenje prije izbjeljivanja." },
  ]
},
{
  slug: "trosak-podizanja-sinusa-kada-je-potrebno",
  title: "Trošak podizanja sinusa: Kada je potrebno i što dodaje",
  description: "Jasno objašnjenje kada je podizanje sinusa zaista potrebno, i koliko obično košta.",
  date: "2026-09-10",
  relatedTreatment: "podizanje-sinusa-istanbul",
  body: [
    { h: "Podizanje sinusa dodaje se samo kada vaš sken to zaista pokaže" },
    { p: "Ovo nije tretman koji netko bira unaprijed — dodaje se planu implantata samo kada 3D sken pokaže nedostatnu visinu kosti." },
    { h: "Koliko obično košta standardno podizanje sinusa" },
    { p: "Podizanje sinusa, kada je potrebno, obično dodaje otprilike 350-450€ planu liječenja implantatima." },
    { h: "Zašto neki slučajevi to zaista trebaju, a drugi ne" },
    { p: "Nakon što je zub nedostajao neko vrijeme, šupljina sinusa može se postupno proširiti." },
    { h: "Razlika između \"zatvorenog\" i \"otvorenog\" podizanja sinusa" },
    { p: "Zatvoreno podizanje sinusa manja je, manje invazivna tehnika koja se koristi kada je potrebna samo mala dodatna visina." },
    { h: "Zašto ovo utječe ne samo na cijenu, već i na vaš raspored liječenja" },
    { p: "Ako je potrebno otvoreno podizanje sinusa, to obično dodaje nekoliko mjeseci ukupnom rasporedu." },
    { h: "Iskren zaključak" },
    { p: "Nećete znati trebate li podizanje sinusa dok se vaš slučaj zaista ne pregleda 3D skeniranjem." },
  ]
},
{
  slug: "marke-zubnih-implantata-zasto-utjecu-na-cijenu",
  title: "Marke zubnih implantata: Zašto toliko utječu na cijenu",
  description: "Zašto ista implantacijska procedura može biti vrlo različito naplaćena ovisno o korištenom implantacijskom sustavu.",
  date: "2026-09-10",
  relatedTreatment: "zubni-implantati-istanbul",
  body: [
    { h: "Nisu svi implantati isti proizvod" },
    { p: "Implantat je titanski vijak, proizveden od strane određene tvrtke, s vlastitim istraživanjem." },
    { h: "Što obično razlikuje premium sustav od pristupačnijeg" },
    { p: "Premium implantacijski sustavi obično imaju dulju povijest objavljenih dugoročnih kliničkih studija." },
    { h: "Zašto je to važno ako u konačnici posjetite drugog stomatologa" },
    { p: "Široko priznatu međunarodnu marku obično je lakše pronaći u dijelovima." },
    { h: "Ovo ne znači da je pristupačnija opcija loš izbor" },
    { p: "I premium i pristupačniji implantacijski sustavi legitimni su medicinski uređaji s CE oznakom." },
    { h: "Razlika u cijeni u praksi" },
    { p: "Razlika je obično oko 30-40% po implantatu." },
    { h: "Jedino pitanje koje zaista ima važnost" },
    { p: "Pitajte bilo koju kliniku točno koju marku implantata nude." },
  ]
},
{
  slug: "zasto-su-stomatoloske-cijene-u-turskoj-toliko-nize",
  title: "Zašto su stomatološke cijene u Turskoj toliko niže? Stvarno objašnjenje",
  description: "Stvarni ekonomski razlozi zašto stomatološko liječenje u Turskoj košta manje.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Nije zato što je stomatologija niže kvalitete" },
    { p: "Razlika u cijeni između Turske i Zapadne Europe proizlazi iz nekoliko kombiniranih faktora." },
    { h: "Troškovi života i opći troškovi klinike" },
    { p: "Najamnine i plaće osoblja strukturno su niže u Turskoj nego u Londonu ili Berlinu." },
    { h: "Tečajevi valuta djeluju u korist međunarodnih pacijenata" },
    { p: "Budući da su troškovi klinike uglavnom u turskim lirama, tečajevi valuta pojačavaju cjenovnu prednost." },
    { h: "Vladina potpora sektoru zdravstvenog turizma" },
    { p: "Turska vlada aktivno je ulagala u pozicioniranje zemlje kao odredišta zdravstvenog turizma." },
    { h: "Veći volumen pacijenata mijenja ekonomiju" },
    { p: "Klinike koje vide mnogo međunarodnih pacijenata mogu ulagati u vlastite laboratorije." },
    { h: "Što ovo ne znači" },
    { p: "Niža cijena ne znači automatski niže standarde." },
  ]
},
{
  slug: "je-li-stomatoloski-turizam-u-turskoj-siguran",
  title: "Je li stomatološki turizam u Turskoj siguran? Što podaci zapravo pokazuju",
  description: "Činjenični pregled sigurnosti stomatološkog turizma u Turskoj — propisi iza njega, opseg industrije i što zapravo štiti pacijente.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Ovo je prvo pitanje koje postavlja gotovo svaki potencijalni pacijent" },
    { p: "Kratak odgovor je da Turska ima formalan, državno reguliran okvir za to." },
    { h: "Regulatorni okvir ojačan je 2025. godine" },
    { p: "Propisi o zdravstvenom turizmu u Turskoj ojačani su u travnju 2025. godine." },
    { h: "Opseg industrije u stvarnim brojkama" },
    { p: "Prema podacima Turskog udruženja zdravstvenog turizma, zemlja je 2025. godine primila više od 1,39 milijuna posjetitelja." },
    { h: "Specifičan položaj Turske u stomatološkom turizmu" },
    { p: "Prema brojkama Ministarstva zdravstva, Turska je samo 2023. godine primila više od 400.000 stomatoloških turista." },
    { h: "O čemu zapravo ovisi \"sigurnost\"" },
    { p: "Sigurnost u ovom kontekstu nije svojstvo zemlje u cjelini." },
    { h: "Što možete sami provjeriti prije rezervacije" },
    { p: "Zatražite USTYB certifikat klinike, provjerite registraciju na HealthTürkiye portalu." },
  ]
},
{
  slug: "certifikat-medjunarodnog-zdravstvenog-turizma-objasnjenje",
  title: "Turski certifikat ovlaštenja za međunarodni zdravstveni turizam (USTYB) objašnjen",
  description: "Što je USTYB certifikat zapravo, zašto je važan, i kako provjeriti posjeduje li ga klinika zaista.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Certifikat koji odvaja ovlaštenu kliniku od neregulirane" },
    { p: "USTYB certifikat izdaje Ministarstvo zdravstva Turske posebno zdravstvenim ustanovama ovlaštenim za liječenje međunarodnih pacijenata." },
    { h: "Što klinika zapravo mora dokazati da bi ga dobila" },
    { p: "Klinike koje traže ovo ovlaštenje moraju ispuniti definirane standarde." },
    { h: "Zašto je ovaj specifičan certifikat važniji od općih marketinških tvrdnji" },
    { p: "USTYB certifikat posebno je povezan s provjerljivom registracijom u Ministarstvu zdravstva." },
    { h: "Povezanost s HealthTürkiye portalom" },
    { p: "Također se očekuje da su ovlaštene klinike navedene na službenom portalu." },
    { h: "Što zapravo pitati kliniku prije rezervacije" },
    { p: "Zatražite izravan uvid u certifikat, ne samo logotip na web stranici." },
    { h: "Zašto vrijedi provjeriti ovaj jedan detalj" },
    { p: "Uglađena web stranica i privlačne cijene ne zamjenjuju regulatornu legitimnost." },
  ]
},
{
  slug: "kako-provjeriti-legitimnost-strane-stomatoloske-klinike",
  title: "Kako zapravo provjeriti da je strana stomatološka klinika legitimna",
  description: "Praktičan kontrolni popis za potvrdu da je strana stomatološka klinika ispravno certificirana i sigurna.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Provjera traje deset minuta" },
    { p: "Većina legitimnih klinika pozdravlja ova pitanja." },
    { h: "1. Zatražite USTYB certifikat" },
    { p: "Legitimna klinika izravno će vam pokazati ovaj dokument." },
    { h: "2. Provjerite registraciju na HealthTürkiye portalu" },
    { p: "Ovo je neovisan način provjere tvrdnji klinike." },
    { h: "3. Pitajte koje specifične marke implantata se koriste" },
    { p: "Specifična, imenovana marka s dokumentiranom poviješću proizvodnje dobar je znak." },
    { h: "4. Pitajte je li jamstvo pisano" },
    { p: "Usmeno \"doživotno jamstvo\" znači malo bez pisanog dokumenta." },
    { h: "5. Potražite ISO certifikate" },
    { p: "Oni ukazuju da je klinika uložila u formalne procese." },
    { h: "6. Pitajte tko zapravo planira vaš slučaj" },
    { p: "Vaš plan liječenja trebao bi biti izgrađen iz vaših vlastitih skeniranja." },
  ]
},
{
  slug: "sto-se-dogadja-ako-nesto-posao-po-zlu-nakon-povratka-kuci",
  title: "Što se događa ako nešto pođe po zlu nakon povratka kući?",
  description: "Izravan pregled naknadne skrbi i zaštite jamstva za pacijente koji putuju u inozemstvo na stomatološko liječenje.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Ovo je briga koja stoji iza gotovo svakog oklijevanja oko liječenja u inozemstvu" },
    { p: "Klinika koja je zaista postavljena za međunarodne pacijente ima stvarne odgovore na ovo." },
    { h: "Što određuje pravi dokument jamstva" },
    { p: "Ispravno pisano jamstvo točno određuje što je pokriveno i koliko dugo." },
    { h: "Udaljeno praćenje prije nego nešto postane hitno" },
    { p: "Mnogi problemi mogu se prvo procijeniti na daljinu." },
    { h: "Kada je zapravo potreban povratni posjet" },
    { p: "Za stvarne slučajeve jamstva, legitimna klinika trebala bi pokriti samo liječenje." },
    { h: "S čime mogu i ne mogu pomoći lokalni stomatolozi u vašoj zemlji" },
    { p: "Stomatolog u vašoj domovini obično se može nositi sa stvarnim hitnim slučajevima." },
    { h: "Iskren odgovor" },
    { p: "Realistična većina cijeljenja implantata prolazi bez incidenata." },
  ]
},
{
  slug: "zasto-milijuni-pacijenata-biraju-tursku-za-stomatolosku-njegu",
  title: "Zašto milijuni pacijenata biraju Tursku za stomatološku njegu",
  description: "Stvarni opseg stomatološkog turizma u Tursku, i faktori zašto toliko međunarodnih pacijenata bira putovanje tamo.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Brojke iza trenda veće su nego što većina očekuje" },
    { p: "Turska je 2025. godine primila više od 1,39 milijuna posjetitelja zdravstvenog turizma." },
    { h: "Specifičan položaj Turske u globalnom stomatološkom turizmu" },
    { p: "Turska je unutar jedne godine primila više od 400.000 stomatoloških turista." },
    { h: "Globalno tržište zaista se širi" },
    { p: "Globalno tržište stomatološkog turizma procijenjeno je na oko 7,2 milijarde dolara 2024. godine." },
    { h: "Trošak je najčešće spomenut razlog, ali rijetko jedini" },
    { p: "Osim cjenovne razlike, pacijenti često navode bržu dostupnost termina." },
    { h: "Infrastruktura je sazrela zajedno s potražnjom" },
    { p: "Vladina ulaganja učinila su ukupno iskustvo znatno strukturiranijim." },
    { h: "Što ovaj trend znači za potencijalnog pacijenta" },
    { p: "Velika, ustaljena industrija znači više konkurencije i izbora." },
  ]
},
{
  slug: "nucleoss-implantati-najekonomicnija-pouzdana-opcija",
  title: "NucleOSS zubni implantati: Najekonomičnija pouzdana opcija u Turskoj",
  description: "Što su NucleOSS implantati zapravo, zašto su jedan od pristupačnijih izbora.",
  date: "2026-09-12",
  relatedTreatment: "zubni-implantati-istanbul",
  body: [
    { h: "Domaća turska marka, ne nepoznata" },
    { p: "NucleOSS je osnovan 2001. godine u Izmiru, Turska — prvi domaći proizvođač zubnih implantata u zemlji." },
    { h: "Zašto je pristupačnije naplaćen od uvoznih sustava" },
    { p: "Jedan vijak NucleOSS implantata obično se naplaćuje oko 150-200€." },
    { h: "Od čega je zapravo napravljen" },
    { p: "NucleOSS implantati proizvedeni su od čistog titana." },
    { h: "Gdje se koristi izvan Turske" },
    { p: "NucleOSS je distribuiran u više od 18 zemalja." },
    { h: "Što \"ekonomično\" ovdje ne znači" },
    { p: "Niža cijena ne znači da implantat nije reguliran — NucleOSS je CE certificiran." },
    { h: "Kome ova opcija zapravo odgovara" },
    { p: "Za pacijente koji stavljaju prioritet na trošak, ovo je legitiman srednji put." },
    { h: "Iskren kompromis koji vrijedi znati" },
    { p: "U usporedbi sa švicarskim sustavima, NucleOSS ima kraću povijest publikacija." },
  ]
},
{
  slug: "nucleoss-24-godine-turske-proizvodnje",
  title: "NucleOSS implantati: Što zapravo znači 24 godine turske proizvodnje",
  description: "Pregled povijesti proizvodnje NucleOSS-a i što dva desetljeća kontinuirane proizvodnje govore o pouzdanosti.",
  date: "2026-09-12",
  relatedTreatment: "zubni-implantati-istanbul",
  body: [
    { h: "Dugovječnost kao proizvođača stvaran je signal" },
    { p: "Tvrtka koja kontinuirano proizvodi od 2001. godine ima 24+ godina stvarne kliničke povratne informacije." },
    { h: "Raspon proizvoda odražava stvarno ulaganje u istraživanje i razvoj" },
    { p: "NucleOSS nudi nekoliko linija implantata dizajniranih za različite kliničke situacije." },
    { h: "Proizvedeno u Turskoj, ne samo sastavljeno" },
    { p: "NucleOSS implantati proizvode se domaće u Izmiru." },
    { h: "Što \"konusni\" vs \"ravni\" dizajni implantata znače za vas" },
    { p: "Različiti oblici tijela implantata odgovaraju različitim stanjima kostiju." },
    { h: "Pitanje kompatibilnosti komponenti" },
    { p: "Široki kompatibilni ekosustav komponenti znači dijelove dostupne godinama kasnije." },
    { h: "Kako se ovo praktično uspoređuje s odabirom novije marke" },
    { p: "Marka s kraćom poviješću jednostavno nije imala toliko vremena za dokazivanje dugoročnih rezultata." },
    { h: "Što ovo znači za vašu odluku" },
    { p: "24-godišnja kontinuirana povijest NucleOSS-a legitiman je faktor u njegovu korist." },
  ]
},
{
  slug: "cijena-porculanske-krunice-istanbul-budzetna-opcija",
  title: "Cijena porculanske krunice u Istanbulu: Tradicionalna, budžetna opcija",
  description: "Koliko obično košta metalokeramička krunica, kako se razlikuje od cirkonija.",
  date: "2026-09-12",
  relatedTreatment: null,
  body: [
    { h: "Stariji, dobro ustaljeni tip krunice — nije nazadovanje, drugačija opcija" },
    { p: "Metalokeramičke (PFM) krunice koriste se u stomatologiji desetljećima." },
    { h: "Koliko obično košta porculanska krunica" },
    { p: "U Istanbulu, PFM krunica obično košta otprilike 80-100€ po jedinici." },
    { h: "Kako je zapravo izgrađena" },
    { p: "PFM krunica ima metalnu podstrukturu za čvrstoću." },
    { h: "Jedini iskren kompromis koji vrijedi znati" },
    { p: "Nakon mnogo godina, metalni rub na liniji desni može postati blago vidljiv." },
    { h: "Gdje porculanske krunice zapravo imaju smisla" },
    { p: "Za stražnje kutnjake gdje je krunica rijetko vidljiva, ovo je razuman izbor." },
    { h: "Gdje se cirkonij obično preferira umjesto toga" },
    { p: "Za prednje, vidljive zube, većina se sada naginje cirkoniju." },
    { h: "Što određuje poštena ponuda" },
    { p: "Ispravna ponuda trebala bi jasno navesti je li riječ o PFM-u ili cirkoniju." },
  ]
},
{
  slug: "porculan-vs-cirkonij-krunice-koja-odgovara-vasem-budzetu",
  title: "Porculan vs cirkonij krunice: Koja zapravo odgovara vašem budžetu i slučaju",
  description: "Izravna, praktična usporedba između metalokeramičkih i cirkonijevih krunica.",
  date: "2026-09-12",
  relatedTreatment: null,
  body: [
    { h: "Dvije legitimne opcije, ne izbor \"dobro vs loše\"" },
    { p: "I metalokeramičke i cirkonijeve krunice ustaljene su, pouzdane restauracije." },
    { h: "Razlika u cijeni u praksi" },
    { p: "PFM krunice obično koštaju otprilike 80-100€, monolitni cirkonij otprilike 120-180€." },
    { h: "Trajnost: bliže nego što većina pretpostavlja" },
    { p: "Oba tipa materijala zaista su trajna kada su ispravno postavljena." },
    { h: "Izgled: gdje se pokazuje stvarna razlika" },
    { p: "Najveća prednost cirkonija je što uopće ne sadrži metal." },
    { h: "Razuman način razmišljanja o miješanju oboje" },
    { p: "Mnogi pacijenti razumno biraju cirkonij za svoje vidljive prednje zube." },
    { h: "Što određuje koju će vaš stomatolog preporučiti" },
    { p: "Vaš stomatolog uzet će u obzir koliko prirodne strukture zuba ostaje." },
    { h: "Pitanje koje treba postaviti prije odluke" },
    { p: "Pitajte svog stomatologa izravno koji bi materijal preporučio." },
  ]
}
];
