export const BLOG_SR = [
{
  slug: "all-on-4-ili-all-on-6-sta-vam-odgovara",
  title: "All-on-4 ili All-on-6: Šta vam odgovara?",
  description: "I All-on-4 i All-on-6 daju vam potpun, fiksni zubni luk na implantima. Evo stvarne razlike između njih i kako stomatolog odlučuje šta odgovara vašoj vilici.",
  date: "2026-09-01",
  relatedTreatment: "all-on-4-5-6-implantati-istanbul",
  body: [
    { h: "Kratak odgovor" },
    { p: "All-on-4 i All-on-6 koriste istu osnovnu ideju — potpun luk fiksnih zuba podržan malim brojem implanata postavljenih u vilicu." },
    { h: "Zašto biste mogli trebati šest umesto četiri?" },
    { p: "Odluka se obično svodi na kost. All-on-4 je posebno dizajniran za rad sa kosti koju većina pacijenata već ima." },
    { h: "Da li dodatni implant menja rezultat koji osećate svakodnevno?" },
    { p: "Ne. Bez obzira da li vaš novi luk sedi na četiri ili šest implanata, gotov most izgleda i oseća se isto u vašim ustima." },
    { h: "Kako se odluka zapravo donosi" },
    { p: "Ispravno 3D skeniranje pokazuje vašem stomatologu tačno koliko je kosti dostupno u svakom području vaše vilice." },
    { h: "Ukratko" },
    { p: "All-on-4 je standardna, dobro proverena polazna tačka za većinu pacijenata. All-on-6 postoji za ljude čija gustina kosti stvarno zahteva dodatnu podršku." },
  ]
},
{
  slug: "cirkonijum-ili-emax-izbor-pravog-materijala",
  title: "Cirkonijum ili E-max: Izbor pravog materijala za vaš osmeh",
  description: "Cirkonijum i E-max su dva materijala iza većine modernih krunica i ljuspica.",
  date: "2026-09-01",
  relatedTreatment: "monolitni-cirkonijum-krunice-istanbul",
  body: [
    { h: "Dva različita zadatka, dva različita materijala" },
    { p: "Cirkonijum i E-max su obe visokokvalitetne keramike, ali nisu zamenjive." },
    { h: "Gde cirkonijum pobeđuje" },
    { p: "Cirkonijum je izuzetno čvrst i otporan na krhotine čak i na zadnjim zubima koji nose opterećenje." },
    { h: "Gde E-max pobeđuje" },
    { p: "E-max ima staklastu providnost koja bliže oponaša prirodnu caklinu." },
    { h: "Pa šta je zapravo prikladno za vas?" },
    { p: "U praksi mnogi pacijenti dobiju mešavinu: E-max spreda za najbolji kozmetički rezultat." },
  ]
},
{
  slug: "koliko-dana-je-potrebno-u-istanbulu-za-stomatolosko-lecenje",
  title: "Koliko dana je potrebno u Istanbulu za stomatološko lečenje?",
  description: "Odgovor u potpunosti zavisi od lečenja koje primate.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Ne postoji jedan odgovor — zavisi od lečenja" },
    { p: "Ovo je jedno od najčešće postavljanih pitanja za svakoga ko planira stomatološko lečenje u inostranstvu." },
    { h: "Lečenja u jednoj poseti (3–7 dana)" },
    { p: "Ljuspice, krunice, izbeljivanje zuba i Hollywood Smile transformacije bez implanata obično se dovrše u jednom putovanju." },
    { h: "Lečenja implantima (dve posete, mesecima razdvojena)" },
    { p: "Zubni implanti trebaju vremena da se spoje sa vilicom pre nego što se može pričvrstiti trajna krunica." },
    { h: "All-on-4 / All-on-6 konkretno" },
    { p: "Slučajevi implanata celog luka slede isti obrazac dve posete." },
    { h: "Planiranje oko toga" },
    { p: "Ako kombinujete lečenja, dodatni kozmetički rad obično se planira oko rasporeda implanata." },
  ]
},
{
  slug: "ljuspice-ili-krunice-koja-je-razlika",
  title: "Ljuspice ili krunice: Koja je razlika, i šta vam treba?",
  description: "Ljuspice i krunice rešavaju različite probleme.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Temeljna razlika" },
    { p: "Ljuspica pokriva samo prednju, vidljivu površinu zuba. Krunica pokriva ceo zub, sa svih strana." },
    { h: "Kada je ljuspica pravi alat" },
    { p: "Ljuspice su dizajnirane za zube koji su kozmetički kompromitovani, ali strukturno zdravi." },
    { h: "Kada je krunica pravi alat" },
    { p: "Krunice su za strukturno oslabljene zube — veliku plombu koja je zakazala." },
    { h: "Mogu li se mešati u jednom osmehu?" },
    { p: "Da, i to je uobičajeno. Potpuna transformacija osmeha često kombinuje oboje." },
    { h: "Šta to znači za vašu konsultaciju" },
    { p: "Ako klinika predlaže krunice na zubima bez strukturnog oštećenja, razumno je pitati zašto." },
  ]
},
{
  slug: "sta-se-desava-ako-nemate-dovoljno-kosti-za-implante",
  title: "Šta se dešava ako nemate dovoljno kosti za implante?",
  description: "Gubitak kosti automatski ne isključuje implante.",
  date: "2026-09-01",
  relatedTreatment: "podizanje-sinusa-istanbul-sr",
  body: [
    { h: "Gubitak kosti je uobičajen, ne diskvalifikujuć" },
    { p: "Nakon što zub nedostaje neko vreme, vilica u tom području prirodno se smanjuje." },
    { h: "Kako stomatolog zapravo proverava" },
    { p: "3D skeniranje pokazuje tačnu visinu i širinu dostupne kosti na mestu implanta." },
    { h: "Opcija 1 — Kosi položaj implanta" },
    { p: "Tehnike poput All-on-4 delimično su dizajnirane upravo oko ovog problema." },
    { h: "Opcija 2 — Koštani nadomestak" },
    { p: "Kada stvarno nema dovoljno koštanog volumena, koštani nadomestak dodaje materijal." },
    { h: "Opcija 3 — Podizanje sinusa" },
    { p: "Gornja zadnja vilica nalazi se blizu sinusnih šupljina." },
    { h: "Zaključak" },
    { p: "„Nemam dovoljno kosti“ retko je kraj razgovora." },
  ]
},
{
  slug: "nega-nakon-implantacije-sta-se-desava-nakon-povratka-kuci",
  title: "Nega nakon implantacije: Šta se dešava nakon povratka kući?",
  description: "Dobijanje implanata u inostranstvu ne znači da ste sami nakon sletanja kući.",
  date: "2026-09-01",
  relatedTreatment: null,
  body: [
    { h: "Nega nakon lečenja ne bi trebalo da prestane na aerodromu" },
    { p: "Uobičajena briga oko dobijanja implanata u inostranstvu je šta se dešava ako se nešto čini pogrešno nakon povratka." },
    { h: "Kako izgleda normalno zarastanje" },
    { p: "Blaga bol i određeno oticanje u danima neposredno nakon operacije implanta su normalni." },
    { h: "Šta uključuje pravi plan nege nakon lečenja" },
    { p: "Pisana garancija koja precizira šta je pokriveno i koliko dugo." },
    { h: "Šta pitati pre obavezivanja" },
    { p: "Pre rezervacije razumno je direktno pitati o neuspehu implanta." },
    { h: "Realistična slika" },
    { p: "Većina zarastanja implanata prolazi bez incidenata." },
  ]
},
{
  slug: "da-li-emax-ljuspice-zahtevaju-brusenje-zuba",
  title: "Da li E-max ljuspice zahtevaju brušenje zuba?",
  description: "Jedna od najčešćih briga o ljuspicama.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Iskren odgovor: zavisi od vaše polazne tačke" },
    { p: "E-max ljuspice se često opisuju kao „minimalna priprema“, i to sa dobrim razlogom." },
    { h: "Kada je potrebno vrlo malo ili nikakvo smanjenje" },
    { p: "Ako su vaši zubi već razumno dobro poravnati, tanka ljuspica se često može zalepiti uz malo uklanjanja cakline." },
    { h: "Kada je stvarno potrebna više pripreme" },
    { p: "Ako je zub značajno neporavnat, obično je potrebno određeno smanjenje cakline." },
    { h: "Zašto ovo treba odlučiti pre putovanja" },
    { p: "Skeniranje digitalnog dizajna osmeha stvarno odgovara na ovo pitanje za vaše specifične zube." },
    { h: "Šta pitati" },
    { p: "Pitajte direktno: „koliko mog prirodnog zuba trebate ukloniti za ovaj dizajn?“" },
  ]
},
{
  slug: "koliko-vremena-treba-za-izradu-cirkonijumske-krunice",
  title: "Koliko vremena treba za izradu cirkonijumske krunice?",
  description: "Od vašeg prvog pregleda do gotove krunice.",
  date: "2026-09-02",
  relatedTreatment: "monolitni-cirkonijum-krunice-istanbul",
  body: [
    { h: "Kratka verzija" },
    { p: "Jedna cirkonijumska krunica obično traje nekoliko dana za dizajn, glodanje i završnu obradu." },
    { h: "Šta se zapravo dešava u to vreme" },
    { p: "Datoteka se šalje na glodanje gde mašina izrezuje krunicu iz cirkonijumskog bloka." },
    { h: "Zašto je interno glodanje važno za vaš raspored" },
    { p: "Klinike sa vlastitim laboratorijem mogu dovršiti krunicu za dan ili dva." },
    { h: "Kada traje duže" },
    { p: "Više krunica prirodno oduzima više vremena vaše posete." },
  ]
},
{
  slug: "sta-zapravo-ukljucuje-lecenje-dizajna-osmeha",
  title: "Šta zapravo uključuje lečenje dizajna osmeha?",
  description: "„Dizajn osmeha“ i „Digitalni dizajn osmeha“ koriste se slobodno.",
  date: "2026-09-02",
  relatedTreatment: "digitalni-dizajn-osmeha-istanbul",
  body: [
    { h: "To je proces planiranja, ne jedna procedura" },
    { p: "Digitalni dizajn osmeha sam po sebi nije lečenje — to je faza planiranja." },
    { h: "Korak 1 — Analiza vašeg lica, ne samo zuba" },
    { p: "Snimaju se fotografije i ponekad video vašeg osmeha." },
    { h: "Korak 2 — 3D skeniranje i digitalni maket" },
    { p: "Intraoralno skeniranje gradi 3D model vaših zuba." },
    { h: "Korak 3 — Utvrđivanje koja su lečenja stvarno potrebna" },
    { p: "Vaš stomatolog određuje kombinaciju lečenja koja će to postići." },
    { h: "Korak 4 — Fizički maket u ustima" },
    { p: "Mnoge klinike mogu vam pokazati privremenu verziju dizajna direktno na vašim zubima." },
    { h: "Zašto je ovo važno" },
    { p: "Bez digitalnog skeniranja verovatno dobijate standardni kozmetički paket." },
  ]
},
{
  slug: "hollywood-smile-nasuprot-ljuspicama-stvarna-razlika",
  title: "Hollywood Smile nasuprot ljuspicama: Koja je stvarna razlika?",
  description: "„Hollywood Smile“ nije zaseban materijal od ljuspica.",
  date: "2026-09-02",
  relatedTreatment: "hollywood-smile-istanbul-sr",
  body: [
    { h: "Hollywood Smile je rezultat, ne materijal" },
    { p: "„Ljuspice“ opisuju specifičnu restauraciju. „Hollywood Smile“ opisuje širi kozmetički cilj." },
    { h: "Dakle Hollywood Smile može koristiti ljuspice, ili možda ne" },
    { p: "Rezultat se može postići ljuspicama, krunicama ili kombinacijom." },
    { h: "Zašto ova razlika ima značaj pri poređenju ponuda" },
    { p: "Uporedite konkretno koji materijali i koliko zuba je uključeno." },
    { h: "Šta zapravo određuje da li su ljuspice pravi izbor" },
    { p: "Ovo se vraća na stanje specifičnog zuba." },
  ]
},
{
  slug: "invisalign-nasuprot-tradicionalnim-aparaticima-sta-odabrati",
  title: "Invisalign nasuprot tradicionalnim aparatićima: Šta odabrati?",
  description: "Providne udlage i metalni aparatići oboje ravnaju zube.",
  date: "2026-09-02",
  relatedTreatment: "invisalign-providne-udlage-istanbul",
  body: [
    { h: "Oboje funkcioniše — pitanje je prikladnost" },
    { p: "Providne udlage i tradicionalni aparatići pomeraju zube kontrolisanim pritiskom." },
    { h: "Gde providne udlage dobro funkcionišu" },
    { p: "Blaga do umerena zbijenost obično je dobro prikladna za udlage." },
    { h: "Gde su tradicionalni aparatići i dalje bolji alat" },
    { p: "Složeniji pokreti bolje se rešavaju fiksnim aparatićima." },
    { h: "Faktor discipline" },
    { p: "Udlage funkcionišu samo ako se nose 20-22 sata dnevno." },
    { h: "Kako se odluka zapravo donosi" },
    { p: "3D skeniranje pokazuje koji pokreti su vam stvarno potrebni." },
  ]
},
{
  slug: "zubni-most-ili-implant-kako-odabrati",
  title: "Zubni most ili implant: Kako odabrati",
  description: "Oba zamenjuju nedostajući zub, ali funkcionišu vrlo različito.",
  date: "2026-09-02",
  relatedTreatment: "zubni-most-istanbul-sr",
  body: [
    { h: "Temeljna razlika" },
    { p: "Implant direktno zamenjuje nedostajući koren zuba. Most zamenjuje samo vidljivi zub." },
    { h: "Zašto je most često brži" },
    { p: "Most ne zahteva operaciju ili period zarastanja." },
    { h: "Zašto je implant često jači dugoročni izbor" },
    { p: "Implant ne zahteva pripremu inače zdravih zuba." },
    { h: "Odlučujući faktor" },
    { p: "Ako susedni zubi već trebaju krunice, most je efikasan izbor." },
    { h: "Pošteno pitanje vredno postavljanja" },
    { p: "Pitajte kliniku direktno zašto preporučuju most." },
  ]
},
{
  slug: "sta-se-desava-tokom-lecenja-korenskog-kanala-korak-po-korak",
  title: "Šta se dešava tokom lečenja korenskog kanala, korak po korak",
  description: "Jasan, postupni prikaz lečenja korenskog kanala.",
  date: "2026-09-02",
  relatedTreatment: "lecenje-korenskog-kanala-istanbul",
  body: [
    { h: "Zašto ova procedura ima lošiju reputaciju od iskustva" },
    { p: "Nelagodnost obično dolazi od same infekcije, ne od procedure." },
    { h: "Korak 1 — Dijagnoza i rendgen" },
    { p: "Rendgen potvrđuje obim infekcije." },
    { h: "Korak 2 — Lokalna anestezija" },
    { p: "Zub se anestezira pre bilo čega drugog." },
    { h: "Korak 3 — Uklanjanje inficiranog tkiva" },
    { p: "Inficirana pulpa uklanja se iz kanala." },
    { h: "Korak 4 — Čišćenje i dezinfekcija" },
    { p: "Prostor kanala se čisti i dezinfikuje." },
    { h: "Korak 5 — Zatvaranje zuba" },
    { p: "Kanal se puni biokompatibilnim materijalom." },
    { h: "Korak 6 — Obično zaštitna krunica" },
    { p: "Krunica se obično preporučuje nakon toga." },
    { h: "Kako se oporavak zapravo oseća" },
    { p: "Blaga bol obično se kontroliše standardnim analgeticima." },
  ]
},

{
  slug: "znaci-da-vam-mozda-treba-gingivektomija",
  title: "Znaci da vam možda treba gingivektomija",
  description: "Gingivektomija nije namenjena samo za „osmeh sa previše desni“.",
  date: "2026-09-02",
  relatedTreatment: "gingivektomija-istanbul-sr",
  body: [
    { h: "Radi se o više od izgleda" },
    { p: "Gingivektomija se često spominje samo u kozmetičkom kontekstu, ali višak tkiva desni može biti i pravi problem oralnog zdravlja." },
    { h: "Znak 1 — Pri osmehu pokazujete primetno više desni nego zuba" },
    { p: "„Osmeh sa previše desni“, gde je široka traka tkiva desni vidljiva iznad zuba, najčešće je prepoznat razlog." },
    { h: "Znak 2 — Vaša linija desni je neravna duž prednjih zuba" },
    { p: "Neravne razine mogu učiniti inače dobro oblikovane zube nesuglasnim." },
    { h: "Znak 3 — Višak tkiva desni otežava pravilno čišćenje zuba" },
    { p: "Tkivo koje se preklapa oko zuba može zadržavati plak na način koji je stvarno teško efikasno četkati." },
    { h: "Znak 4 — Planirate ljuspice i vaše razine desni su neravne" },
    { p: "Procena desni često je deo ispravnog plana digitalnog dizajna osmeha." },
    { h: "Šta zapravo učiniti" },
    { p: "Nijedan od ovih znakova ne znači da je gingivektomija automatski ispravan odgovor upravo za vas." },
  ]
},
{
  slug: "pitanja-pre-odabira-klinike-u-inostranstvu",
  title: "Pitanja koja treba postaviti pre odabira stomatološke klinike u inostranstvu",
  description: "Praktičan kontrolni spisak onoga što stvarno pitati pre rezervacije stomatološkog lečenja u drugoj zemlji.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Sama poređenje cena ne govori mnogo" },
    { p: "Dve klinike mogu ponuditi istu cenu za „All-on-4“, a misliti na stvarno različite stvari." },
    { h: "1. Koju konkretnu marku implanta ili materijala koristite?" },
    { p: "Prave, etablirane marke imaju istoriju proizvodnje koja se može pratiti." },
    { h: "2. Da li je garancija pisana, i šta tačno pokriva?" },
    { p: "„Doživotna garancija“ trebalo bi da precizira šta je uključeno." },
    { h: "3. Ko radi planiranje slučaja, i da li se zasniva na mojim vlastitim skeniranjima?" },
    { p: "Vaš plan lečenja trebalo bi da bude izgrađen iz vaših vlastitih 3D skeniranja." },
    { h: "4. Šta se dešava ako nešto treba pažnju nakon što odem kući?" },
    { p: "Klinika sigurna u vlastiti rad trebalo bi da ima jasan odgovor." },
    { h: "5. Da li je klinika zvanično ovlašćena za međunarodne pacijente?" },
    { p: "Konkretno u Turskoj, klinike koje leče međunarodne pacijente trebalo bi da imaju važeću dozvolu za međunarodni zdravstveni turizam." },
    { h: "6. Šta je zapravo uključeno u navedenu cenu?" },
    { p: "Pitajte konkretno da li ponuda uključuje konsultaciju, sva skeniranja i kontrolne posete." },
  ]
},
{
  slug: "koje-sertifikate-bi-trebalo-da-ima-stomatoloska-klinika-u-inostranstvu",
  title: "Koje sertifikate bi stomatološka klinika u inostranstvu zapravo trebalo da ima?",
  description: "Sertifikate i akreditacione oznake lako je pokazati i teško proveriti samo sa veb sajta.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Nemaju svi sertifikati istu težinu" },
    { p: "Veb sajtovi klinika često prikazuju niz oznaka i pečata." },
    { h: "Dozvola za međunarodni zdravstveni turizam (specifična za Tursku)" },
    { p: "U Turskoj klinike koje zakonito leče međunarodne pacijente trebalo bi da imaju ovu dozvolu od Ministarstva zdravlja." },
    { h: "ISO sertifikati" },
    { p: "Ovo su opšti standardi upravljanja kvalitetom, ne specifični za stomatologiju." },
    { h: "Sertifikati proizvođača implanata" },
    { p: "Neke klinike pokazuju sertifikate koji potvrđuju da su ovlašćeni korisnici određene marke implanta." },
    { h: "Šta zapravo učiniti sa ovom informacijom" },
    { p: "Ne oslanjajte se isključivo na oznake prikazane na veb sajtu." },
  ]
},
{
  slug: "koliko-zapravo-traju-cirkonijumske-krunice",
  title: "Koliko zapravo traju cirkonijumske krunice?",
  description: "Realističan pogled na vek trajanja cirkonijumskih krunica.",
  date: "2026-09-02",
  relatedTreatment: "monolitni-cirkonijum-krunice-istanbul",
  body: [
    { h: "Opšti raspon" },
    { p: "Dobro izrađene cirkonijumske krunice obično traju 10 do 15 godina ili duže uz razumnu negu." },
    { h: "Zašto monolitni cirkonijum obično traje duže od starijih cirkonijumskih krunica" },
    { p: "Starije cirkonijumske krunice koristile su cirkonijumsku jezgru sa odvojenim slojem porcelana." },
    { h: "Šta zapravo skraćuje vek trajanja krunice" },
    { p: "Nelečeno škripanje zubima nanosi ponavljanu prekomernu silu na krunicu." },
    { h: "Šta možete učiniti da traje duže" },
    { p: "Normalno četkanje i korišćenje konca za zube baš kao sa prirodnim zubima." },
    { h: "Kada „neuspeh“ zapravo nije o krunici" },
    { p: "Ako krunica treba da bude zamenjena nakon nekoliko godina, vredi razumeti zašto." },
  ]
},
{
  slug: "monolitni-nasuprot-slojevitom-cirkonijumu-koja-je-razlika",
  title: "Monolitni nasuprot slojevitom cirkonijumu: Koja je razlika?",
  description: "Oboje se zove „cirkonijumske krunice“, ali konstrukcija je stvarno drugačija.",
  date: "2026-09-02",
  relatedTreatment: "monolitni-cirkonijum-krunice-istanbul",
  body: [
    { h: "Isti osnovni materijal, drugačija konstrukcija" },
    { p: "I monolitni i slojeviti cirkonijum koriste cirkonijum oksid." },
    { h: "Slojeviti cirkonijum" },
    { p: "Slojevita krunica ima cirkonijumsku jezgru za čvrstoću, okrunjenu odvojenim slojem porcelana." },
    { h: "Monolitni cirkonijum" },
    { p: "Monolitna krunica se u potpunosti glodav iz jednog cirkonijumskog bloka." },
    { h: "Gde se svaki tipično koristi" },
    { p: "Monolitni cirkonijum uglavnom se preferira za zadnje zube." },
    { h: "Zaključak" },
    { p: "Ako je izdržljivost protiv krhotina vaš glavni prioritet, monolitni cirkonijum je uglavnom sigurniji izbor." },
  ]
},
{
  slug: "mogu-li-se-implanti-i-ljuspice-kombinovati-u-jednom-putovanju",
  title: "Mogu li se implanti i ljuspice kombinovati u jednom putovanju?",
  description: "Kombinovanje lečenja je uobičajeno, ali raspored zarastanja implanta menja način planiranja.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Da, ali raspored implanta određuje tempo" },
    { p: "Kombinovanje implanata sa ljuspicama uobičajen je zahtev." },
    { h: "Kako se to obično planira" },
    { p: "Tokom prve posete postavljaju se implanti." },
    { h: "Zašto je vreme izbeljivanja ovde posebno važno" },
    { p: "Ako takođe dobijate ljuspice, izbeljivanje bi trebalo da bude pre njihove izrade." },
    { h: "Šta bi trebalo da vam kaže kombinovani plan lečenja" },
    { p: "Ispravan plan detaljno opisuje šta se dešava svaki dan." },
    { h: "Praktična prednost kombinovanja" },
    { p: "Kombinovanje lečenja stvarno smanjuje ukupno putovanje." },
  ]
},
{
  slug: "upravljanje-strahom-od-stomatologa-tokom-putovanja-na-lecenje",
  title: "Upravljanje strahom od stomatologa tokom putovanja na lečenje",
  description: "Strah od stomatologa ne nestaje samo zato što putujete na lečenje.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "To je uobičajena briga, ne neuobičajena" },
    { p: "Strah od stomatologa izuzetno je čest, a putovanje u inostranstvo može dodati dodatni sloj stresa." },
    { h: "Stvarno dostupne opcije sedacije" },
    { p: "Većina klinika nudi opcije osim same lokalne anestezije." },
    { h: "Komunikacija je važnija nego što ljudi očekuju" },
    { p: "Anksioznost je često gora kada u potpunosti ne razumete šta se dešava." },
    { h: "Planiranje pomaže više nego što većina ljudi shvata" },
    { p: "Poznavanje vašeg rasporeda unapred smanjuje neizvesnost." },
    { h: "Razumno je reći ovo unapred" },
    { p: "Direktno reći koordinatoru o strahu daje im priliku da planiraju oko toga." },
  ]
},
{
  slug: "sta-pripremiti-pre-stomatoloskog-lecenja-u-inostranstvu",
  title: "Šta pripremiti pre stomatološkog lečenja u inostranstvu",
  description: "Praktičan kontrolni spisak pre putovanja.",
  date: "2026-09-02",
  relatedTreatment: null,
  body: [
    { h: "Pre nego što bilo šta rezervišete" },
    { p: "Nabavite pisani plan lečenja na osnovu vlastitih fotografija ili skeniranja." },
    { h: "Medicinske informacije koje treba imati spremne" },
    { p: "Spisak lekova, alergija i relevantnih zdravstvenih stanja treba podeliti pre putovanja." },
    { h: "Postojeći stomatološki zapisi" },
    { p: "Nedavne rendgenske snimke mogu ubrzati planiranje." },
    { h: "Praktična logistika putovanja" },
    { p: "Potvrdite oba datuma posete unapred za slučajeve implanata." },
    { h: "Pitanja na koja treba dobiti odgovor pre leta" },
    { p: "Ukupan broj potrebnih poseta." },
    { h: "Šta zapravo spakovati" },
    { p: "Spisak lekova, udobnu odeću." },
  ]
},
{
  slug: "krunica-ili-plomba-koja-je-razlika",
  title: "Krunica ili plomba: Koja je razlika, i kada vam treba koja?",
  description: "Oboje popravlja oštećeni zub, ali na vrlo različitim nivoima oštećenja.",
  date: "2026-09-03",
  relatedTreatment: "monolitni-cirkonijum-krunice-istanbul",
  body: [
    { h: "Sve se svodi na to koliko zdravog zuba ostaje" },
    { p: "Plomba popravlja malo do umereno oštećeno područje, obično od karijesa." },
    { h: "Kada je plomba dovoljna" },
    { p: "Mali do srednji karijesi, uhvaćeni razumno rano, obično se dobro rešavaju plombom." },
    { h: "Kada plomba nije dovoljna" },
    { p: "Ako je karijes opsežan, ili je zub napukao, krunica umesto toga pruža puno pokriće." },
    { h: "Zašto postavljanje plombe gde je potrebna krunica ne traje" },
    { p: "Prevelika plomba u odnosu na preostalu strukturu zuba verovatnije će napuknuti." },
    { h: "Iskren odgovor dobrog stomatologa" },
    { p: "Stomatolog koji direktno gleda rendgen i sam zub može reći šta vam treba." },
  ]
},
{
  slug: "cena-all-on-4-sta-je-zapravo-ukljuceno",
  title: "Cena All-on-4: Šta je zapravo uključeno u cenu?",
  description: "All-on-4 ponude mogu izgledati vrlo različito između klinika iz razloga koji nemaju veze sa kvalitetom.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-implantati-istanbul",
  body: [
    { h: "Zašto ista procedura dobija vrlo različite ponude" },
    { p: "Dve klinike mogu obe ponuditi „All-on-4“ po vrlo različitim cenama." },
    { h: "Marka i kvalitet implanta" },
    { p: "Etablirane, klinički dokazane marke implanata obično koštaju više." },
    { h: "Šta je uključeno u navedenu cenu" },
    { p: "Pitajte konkretno da li ponuda uključuje početnu konsultaciju i 3D skeniranje." },
    { h: "Da li je koštani nadomestak ili podizanje sinusa verovatno, i da li je uključeno" },
    { p: "Ako vaš slučaj možda treba dodatni koštani rad, ponuda pre pregleda skeniranja to ne može uzeti u obzir." },
    { h: "Uslovi praćenja i garancije" },
    { p: "Proverite da li su kontrole nakon nege i garantni period uključeni u cenu." },
    { h: "Jedno pitanje koje razjašnjava većinu ovoga" },
    { p: "Pitajte direktno: „šta bi promenilo ovu konačnu cenu?“" },
  ]
},
{
  slug: "mogu-li-se-postaviti-zubni-implanti-ako-pusite",
  title: "Mogu li se postaviti zubni implanti ako pušite?",
  description: "Pušenje automatski ne isključuje implante, ali je pravi faktor koji stomatolozi shvataju ozbiljno.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-implantati-istanbul",
  body: [
    { h: "Pušenje je faktor rizika, ne automatska diskvalifikacija" },
    { p: "Mnogi pušači dobiju uspešne, dugotrajne zubne implante." },
    { h: "Zašto je period zarastanja ovde toliko važan" },
    { p: "Osteointegracija zavisi od zdrave opskrbe krvlju tog područja." },
    { h: "Šta stomatolozi zapravo preporučuju" },
    { p: "Mnoge klinike preporučuju prestanak pušenja, ili barem značajno smanjenje." },
    { h: "Iskrenost o tome je važna" },
    { p: "Reći svom stomatologu da pušite omogućuje mu da pravilno planira oko toga." },
    { h: "Zaključak" },
    { p: "Pušenje čini lečenje implantima nešto rizičnijim, ne nemogućim." },
  ]
},
{
  slug: "sta-je-osteointegracija-i-zasto-je-vazna-za-implante",
  title: "Šta je osteointegracija, i zašto je važna za implante?",
  description: "Pojam iza toga zašto lečenje implantima traje mesecima, ne danima.",
  date: "2026-09-03",
  relatedTreatment: "all-on-4-5-6-implantati-istanbul",
  body: [
    { h: "Reč koja objašnjava raspored implanta sa dve posete" },
    { p: "Osteointegracija je proces kojim se titanski implant fizički spaja sa okolnom vilicom." },
    { h: "Zašto konkretno titan" },
    { p: "Titan ima stvarno neobično svojstvo: žive koštane ćelije rastu direktno na njegovoj površini." },
    { h: "Koliko vremena traje" },
    { p: "Osteointegracija tipično traje nekoliko meseci, često se navodi kao otprilike tri do šest meseci." },
    { h: "Šta se dešava ako se ovaj korak požuri" },
    { p: "Opterećivanje implanta konačnom restauracijom pre završetka osteointegracije rizikuje." },
    { h: "Zašto je ovo važno pri poređenju klinika" },
    { p: "Klinika koja obećava potpuno trajnu implantnu restauraciju u jednoj kratkoj poseti radi sa neobično jednostavnim slučajem ili preskače korak." },
  ]
},
{
  slug: "koliko-kostaju-zubni-implantati-u-turskoj",
  title: "Koliko koštaju zubni implantati u Turskoj?",
  description: "Realističan pregled troškova zubnih implantata u Turskoj, zašto se cene razlikuju među klinikama i šta zapravo treba uporediti pre odluke.",
  date: "2026-09-10",
  relatedTreatment: "zubni-implantati-istanbul-sr",
  body: [
    { h: "Ne postoji jedan broj, a svaka klinika koja daje cenu pre nego što vidi vaš slučaj nagađa" },
    { p: "Cena implantata zavisi od marke korišćenog implantata, potrebe za koštanim kalemom i broja potrebnih implantata." },
    { h: "Marka implantata je najveći pojedinačni faktor cene" },
    { p: "Klinike obično nude više od jednog implantacionog sistema, a razlika u ceni između njih je stvarna — često 30-40% između ekonomičnog i premium sistema." },
    { h: "Koliko obično košta jedan implantat" },
    { p: "Za jedan zubni implantat (samo sam zavrtanj, bez krunice koja dolazi iznad), cene u klinikama u Istanbulu obično se kreću od oko 300€ do 450€+ za premium sisteme." },
    { h: "Zašto je krunica zasebna stavka" },
    { p: "Implantat zamenjuje koren; krunica zamenjuje vidljiv zub. Potpuna ponuda za \"implantat + krunicu\" treba jasno da prikaže oba." },
    { h: "Šta zapravo menja ukupan iznos" },
    { p: "Koštani kalem ili podizanje sinusa, ako to vaš slučaj zahteva, dodaje se ukupnom iznosu — to zaista zavisi od stanja vaše vilične kosti." },
    { h: "Kako dobiti stvaran broj za vaš slučaj" },
    { p: "Pošaljite nedavni panoramski rendgen ako ga imate, ili planirajte 3D skeniranje tokom konsultacije." },
  ]
},
{
  slug: "cena-all-on-4-turska-vs-uk-sad",
  title: "Cena All-on-4 u Turskoj vs UK i SAD: Šta zapravo upoređujete",
  description: "Zašto se ponude All-on-4 toliko razlikuju među zemljama, i šta zapravo uzrokuje razliku osim troška rada.",
  date: "2026-09-10",
  relatedTreatment: "all-on-4-5-6-implantati-istanbul",
  body: [
    { h: "Razlika je stvarna, ali to nije samo \"jeftinija radna snaga\"" },
    { p: "All-on-4 u Turskoj se obično nudi za približno trećinu do polovinu tipične cene u UK ili SAD." },
    { h: "Šta obično uključuje slučaj punog luka u Turskoj" },
    { p: "Potpun fiksni luk na četiri implantata, uključujući operaciju, obično košta od ~2900€ po luku sa pristupačnijim sistemom do 3400€ sa premium sistemom." },
    { h: "Zašto All-on-5 ili All-on-6 košta više" },
    { p: "Dodavanje petog ili šestog implantata povećava ukupan iznos za približno 300-450€ po dodatnom implantatu." },
    { h: "Šta UK i SAD cene mogu uključivati, a ponuda iz Turske nema" },
    { p: "Uporedite šta je zapravo uključeno u svaku ponudu: da li UK cena uključuje kontrolnu posetu?" },
    { h: "Stvarno razmatranje troška koje većina propušta" },
    { p: "Čak i računajući letove i smeštaj, ukupan iznos za slučaj punog luka u inostranstvu obično ostaje znatno niži." },
    { h: "Šta pitati pre poređenja dve ponude" },
    { p: "Pitajte svaku kliniku koju marku implantata koriste i šta zapravo pokriva garancija." },
  ]
},
{
  slug: "cena-laminiranih-ljuspica-istanbul",
  title: "Cena laminiranih ljuspica u Istanbulu: Šta je zapravo uključeno",
  description: "Jasan pregled onoga što određuje cenu laminiranih ljuspica u Istanbulu, i šta treba da sadrži ispravna ponuda.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Cena se obično navodi po zubu, ne po osmehu" },
    { p: "Cena laminiranih ljuspica je gotovo uvek po pojedinačnom zubu, tako da ukupan iznos u potpunosti zavisi od toga koliko zuba je uključeno u dizajn vašeg osmeha." },
    { h: "Koliko obično košta jedna ljuspica" },
    { p: "Cena po zubu za laminirane ljuspice u Istanbulu obično se kreće u rasponu od otprilike 300-400€." },
    { h: "Zašto materijal utiče na cenu i rezultat" },
    { p: "Tanki porcelanski laminati zahtevaju precizu, minimalnu pripremu zuba i veštog keramičara." },
    { h: "Šta treba da bude uključeno u ponuđenu cenu" },
    { p: "Ispravna ponuda za ljuspice treba da uključuje konsultaciju digitalnog dizajna osmeha i cementiranje." },
    { h: "Faza privremenih ljuspica" },
    { p: "Između pripremljenih zuba i postavljanja konačnih ljuspica obično nosite privremene ljuspice nekoliko dana." },
    { h: "Zašto najjeftinija ponuda nije automatski najbolja vrednost" },
    { p: "Značajno niža cena po zubu od svega ostalog što vidite zaslužuje direktno pitanje." },
  ]
},
{
  slug: "trosak-hollywood-smile-sta-odredjuje-cenu",
  title: "Trošak Hollywood Smile-a: Šta određuje konačnu cenu",
  description: "Cena Hollywood Smile-a varira više nego gotovo bilo koji drugi tretman jer nije jedan fiksni postupak.",
  date: "2026-09-10",
  relatedTreatment: "hollywood-smile-istanbul-sr",
  body: [
    { h: "\"Hollywood Smile\" opisuje rezultat, a ne fiksni cenovnik" },
    { p: "Pošto se Hollywood Smile može postići ljuspicama, krunicama ili mešavinom oboje, dve klinike sa veoma različitim ukupnim iznosima mogu zapravo određivati cenu različitih planova lečenja." },
    { h: "Broj uključenih zuba je najveći pojedinačni faktor" },
    { p: "Potpuna transformacija Hollywood Smile obično pokriva gornjih vidljivih 16-20 zuba." },
    { h: "Ljuspice vs krunice menjaju cenu po zubu" },
    { p: "Laminirane ljuspice i pune cirkonijumske krunice se cene različito." },
    { h: "Šta dodaje potpuni digitalni dizajn osmeha" },
    { p: "Ispravan plan Hollywood Smile počinje 3D digitalnim dizajnom osmeha." },
    { h: "Zašto se dva \"paketa Hollywood Smile\" mogu razlikovati za hiljade evra" },
    { p: "Najveće oscilacije dolaze od broja uključenih zuba i klase materijala." },
    { h: "Pitanje koje vredi postaviti direktno" },
    { p: "Pitajte tačno koliko zuba je uključeno u ponuđenu cenu." },
  ]
},
{
  slug: "cena-cirkonijumske-krunice-jeftinije-ne-znaci-uvek-bolje",
  title: "Cena cirkonijumske krunice: Jeftinije ne znači uvek bolje",
  description: "Šta zapravo utiče na cenu cirkonijumske krunice, i zašto najniža ponuda ponekad može koštati više dugoročno.",
  date: "2026-09-10",
  relatedTreatment: "monolitni-cirkonijum-krunice-istanbul",
  body: [
    { h: "Osnovna cena je obično skromna — gomilaju se upravo dodaci" },
    { p: "Jedna cirkonijumska krunica sama po sebi je jedna od pristupačnijih restorativnih opcija — obično 120-180€ po jedinici u Istanbulu." },
    { h: "Monolitni vs slojeviti cirkonijum" },
    { p: "Monolitni cirkonijum, glodan iz jednog čvrstog bloka, obično je otporniji na pucanje." },
    { h: "Šta dodaje titanijumska osnova" },
    { p: "Posebno za krunice na implantima, titanijumska osnova dodaje značajan iznos trošku." },
    { h: "Zašto mnogo jeftinija ponuda zaslužuje direktno pitanje" },
    { p: "Pitajte konkretno da li je reč o monolitnom ili slojevitom cirkonijumu, i koji garantni period je uključen." },
    { h: "Kako broj krunica brzo menja ukupan iznos" },
    { p: "Pošto je cena po jedinici, uzmite cenu jedinice i pomnožite je sami." },
    { h: "Šta zapravo određuje poštena ponuda" },
    { p: "Pouzdana ponuda navodi cenu po krunici, specifičan tip cirkonijuma i garantni period." },
  ]
},
{
  slug: "trosak-lecenja-korenskog-kanala-turska",
  title: "Trošak lečenja korenskog kanala u Turskoj: Šta očekivati",
  description: "Direktan pregled onoga koliko obično košta lečenje korenskog kanala u Turskoj, i šta vam još može trebati.",
  date: "2026-09-10",
  relatedTreatment: "lecenje-korenskog-kanala-istanbul",
  body: [
    { h: "Samo lečenje korenskog kanala je jedna od pristupačnijih procedura" },
    { p: "Samo po sebi, lečenje korenskog kanala u Istanbulu obično košta otprilike 130-170€ po zubu." },
    { h: "Zašto kutnjaci mogu koštati više od prednjih zuba" },
    { p: "Zub sa više kanala treba duže da se temeljno očisti i napuni." },
    { h: "Dodatni trošak koji ljudi ne uvek planiraju: krunica nakon toga" },
    { p: "Zub koji je prošao lečenje korenskog kanala skloniji je lomljenju vremenom." },
    { h: "Šta dodaje vlaknasti klin" },
    { p: "Ako nedostaje veliki deo prirodne strukture zuba, ponekad se pre krunice u kanal postavlja mali vlaknasti klin." },
    { h: "Poređenje troška lečenja korenskog kanala sa alternativom" },
    { p: "Vađenje zuba i zamena implantatom znatno je veći trošak." },
    { h: "Šta tražiti u svojoj ponudi" },
    { p: "Pitajte da li je ponuda samo za lečenje korenskog kanala ili uključuje sledeću krunicu." },
  ]
},
{
  slug: "trosak-pune-proteze-istanbul-opcije",
  title: "Trošak pune proteze u Istanbulu: Opcije i cene",
  description: "Koliko obično košta puna proteza u Istanbulu, kako se poredi sa opcijama na implantima.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Tradicionalna puna proteza je jedna od pristupačnijih opcija" },
    { p: "Puna pokretna proteza za jedan luk obično košta otprilike 700-900€ u Istanbulu." },
    { h: "Zašto košta manje od opcija na implantima" },
    { p: "Tradicionalna proteza ne uključuje operaciju implantata — postavlja se direktno na desni." },
    { h: "Kompromis koji vredi razumeti pre odluke" },
    { p: "Pokretna proteza zahteva više podešavanja vremenom." },
    { h: "Noćna udlaga je povezan, zaseban trošak" },
    { p: "Ako škripite zubima, noćna udlaga u svakom slučaju štiti vašu investiciju." },
    { h: "Kako se ovo poredi sa All-on-4" },
    { p: "All-on-4 košta značajno više unapred, uglavnom zbog operacije implantata." },
    { h: "Šta uključuje ispravna ponuda proteze" },
    { p: "Potpuna ponuda treba da navede da li je reč o punoj ili delimičnoj protezi." },
  ]
},
{
  slug: "trosak-podizanja-sinusa-kada-je-potrebno",
  title: "Trošak podizanja sinusa: Kada je potrebno i šta dodaje",
  description: "Jasno objašnjenje kada je podizanje sinusa zaista potrebno, i koliko obično košta.",
  date: "2026-09-10",
  relatedTreatment: "podizanje-sinusa-istanbul-sr",
  body: [
    { h: "Podizanje sinusa se dodaje samo kada vaš sken to zaista pokaže" },
    { p: "Ovo nije tretman koji neko bira unapred — dodaje se planu implantata samo kada 3D skeniranje pokaže nedovoljnu visinu kosti." },
    { h: "Koliko obično košta standardno podizanje sinusa" },
    { p: "Podizanje sinusa, kada je potrebno, obično dodaje otprilike 350-450€ planu lečenja implantima." },
    { h: "Zašto neki slučajevi to zaista trebaju, a drugi ne" },
    { p: "Nakon što zub nedostaje neko vreme, šupljina sinusa može postepeno da se proširi." },
    { h: "Razlika između \"zatvorenog\" i \"otvorenog\" podizanja sinusa" },
    { p: "Zatvoreno podizanje sinusa je manja, manje invazivna tehnika koja se koristi kada je potrebna samo mala dodatna visina." },
    { h: "Zašto ovo utiče ne samo na cenu, već i na vaš raspored lečenja" },
    { p: "Ako je potrebno otvoreno podizanje sinusa, ovo obično dodaje nekoliko meseci ukupnom rasporedu." },
    { h: "Iskren zaključak" },
    { p: "Nećete znati da li vam treba podizanje sinusa dok vaš slučaj zaista ne bude pregledan 3D skeniranjem." },
  ]
},
{
  slug: "zasto-su-stomatoloske-cene-u-turskoj-toliko-nize",
  title: "Zašto su stomatološke cene u Turskoj toliko niže? Stvarno objašnjenje",
  description: "Stvarni ekonomski razlozi zašto stomatološko lečenje u Turskoj košta manje.",
  date: "2026-09-10",
  relatedTreatment: null,
  body: [
    { h: "Nije zato što je stomatologija nižeg kvaliteta" },
    { p: "Razlika u ceni između Turske i Zapadne Evrope dolazi iz nekoliko kombinovanih faktora." },
    { h: "Troškovi života i režijski troškovi klinike" },
    { p: "Kirije i plate osoblja strukturno su niže u Turskoj nego u Londonu ili Berlinu." },
    { h: "Kursevi valuta rade u korist međunarodnih pacijenata" },
    { p: "Pošto su troškovi klinike uglavnom u turskim lirama, kursevi valuta pojačavaju cenovnu prednost." },
    { h: "Vladina podrška sektoru zdravstvenog turizma" },
    { p: "Turska vlada je aktivno ulagala u pozicioniranje zemlje kao destinacije zdravstvenog turizma." },
    { h: "Veći obim pacijenata menja ekonomiju" },
    { p: "Klinike koje vide mnogo međunarodnih pacijenata mogu da ulažu u sopstvene laboratorije." },
    { h: "Šta ovo ne znači" },
    { p: "Niža cena ne znači automatski niže standarde." },
  ]
},
{
  slug: "da-li-je-stomatoloski-turizam-u-turskoj-bezbedan",
  title: "Da li je stomatološki turizam u Turskoj bezbedan? Šta podaci zapravo pokazuju",
  description: "Činjenički pregled bezbednosti stomatološkog turizma u Turskoj — regulativa iza njega, obim industrije i šta zapravo štiti pacijente.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Ovo je prvo pitanje koje postavlja gotovo svaki potencijalni pacijent" },
    { p: "Kratak odgovor je da Turska ima formalan, državno regulisan okvir za ovo." },
    { h: "Regulatorni okvir je ojačan 2025. godine" },
    { p: "Propisi o zdravstvenom turizmu u Turskoj ojačani su u aprilu 2025." },
    { h: "Obim industrije u stvarnim brojkama" },
    { p: "Prema podacima Turskog udruženja zdravstvenog turizma, zemlja je 2025. primila preko 1,39 miliona posetilaca." },
    { h: "Specifična pozicija Turske u stomatološkom turizmu" },
    { p: "Prema podacima Ministarstva zdravlja, Turska je samo 2023. primila preko 400.000 stomatoloških turista." },
    { h: "Od čega zapravo zavisi \"bezbednost\"" },
    { p: "Bezbednost u ovom kontekstu nije svojstvo zemlje u celini." },
    { h: "Šta možete sami da proverite pre rezervacije" },
    { p: "Zatražite USTYB sertifikat klinike, proverite registraciju na HealthTürkiye portalu." },
  ]
},
{
  slug: "sertifikat-medjunarodnog-zdravstvenog-turizma-objasnjenje",
  title: "Turski sertifikat ovlašćenja za međunarodni zdravstveni turizam (USTYB) objašnjen",
  description: "Šta je USTYB sertifikat zapravo, zašto je važan, i kako proveriti da li ga klinika zaista poseduje.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Sertifikat koji odvaja ovlašćenu kliniku od neregulisane" },
    { p: "USTYB sertifikat izdaje Ministarstvo zdravlja Turske posebno zdravstvenim ustanovama ovlašćenim za lečenje međunarodnih pacijenata." },
    { h: "Šta klinika zapravo mora da dokaže da bi ga dobila" },
    { p: "Klinike koje traže ovo ovlašćenje moraju da ispune definisane standarde." },
    { h: "Zašto ovaj konkretan sertifikat ima veći značaj od opštih marketinških tvrdnji" },
    { p: "USTYB sertifikat je konkretno povezan sa proverljivom registracijom u Ministarstvu zdravlja." },
    { h: "Veza sa HealthTürkiye portalom" },
    { p: "Takođe se očekuje da su ovlašćene klinike navedene na zvaničnom portalu." },
    { h: "Šta zapravo pitati kliniku pre rezervacije" },
    { p: "Zatražite direktan uvid u sertifikat, ne samo logo na veb stranici." },
    { h: "Zašto vredi proveriti ovaj jedan detalj" },
    { p: "Uglađen veb sajt i atraktivne cene ne zamenjuju regulatornu legitimnost." },
  ]
},
{
  slug: "kako-proveriti-legitimnost-strane-stomatoloske-klinike",
  title: "Kako zapravo proveriti da je strana stomatološka klinika legitimna",
  description: "Praktična kontrolna lista za potvrdu da je strana stomatološka klinika ispravno sertifikovana i bezbedna.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Provera traje deset minuta" },
    { p: "Većina legitimnih klinika pozdravlja ova pitanja." },
    { h: "1. Zatražite USTYB sertifikat" },
    { p: "Legitimna klinika će vam direktno pokazati ovaj dokument." },
    { h: "2. Proverite registraciju na HealthTürkiye portalu" },
    { p: "Ovo je nezavisan način provere tvrdnji klinike." },
    { h: "3. Pitajte koje specifične marke implantata se koriste" },
    { p: "Specifična, imenovana marka sa dokumentovanom istorijom proizvodnje dobar je znak." },
    { h: "4. Pitajte da li je garancija pisana" },
    { p: "Usmena \"doživotna garancija\" znači malo bez pisanog dokumenta." },
    { h: "5. Tražite ISO sertifikate" },
    { p: "Oni ukazuju da je klinika uložila u formalne procese." },
    { h: "6. Pitajte ko zapravo planira vaš slučaj" },
    { p: "Vaš plan lečenja treba da bude izgrađen iz vaših sopstvenih skeniranja." },
  ]
},
{
  slug: "zasto-milioni-pacijenata-biraju-tursku-za-stomatolosku-negu",
  title: "Zašto milioni pacijenata biraju Tursku za stomatološku negu",
  description: "Stvarni obim stomatološkog turizma u Tursku, i faktori iza toga zašto toliko međunarodnih pacijenata bira da putuje tamo.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Brojevi iza trenda veći su nego što većina očekuje" },
    { p: "Turska je 2025. primila preko 1,39 miliona posetilaca zdravstvenog turizma." },
    { h: "Specifična pozicija Turske u globalnom stomatološkom turizmu" },
    { p: "Turska je u jednoj godini primila preko 400.000 stomatoloških turista." },
    { h: "Globalno tržište zaista se širi" },
    { p: "Globalno tržište stomatološkog turizma procenjeno je na oko 7,2 milijarde dolara 2024." },
    { h: "Trošak je najčešće pomenut razlog, ali retko jedini" },
    { p: "Osim cenovne razlike, pacijenti često navode bržu dostupnost termina." },
    { h: "Infrastruktura je sazrela zajedno sa potražnjom" },
    { p: "Vladine investicije učinile su ukupno iskustvo znatno strukturisanijim." },
    { h: "Šta ovaj trend znači za potencijalnog pacijenta" },
    { p: "Velika, ustaljena industrija znači više konkurencije i izbora." },
  ]
},
{
  slug: "nucleoss-implantati-najekonomicnija-pouzdana-opcija",
  title: "NucleOSS zubni implantati: Najekonomičnija pouzdana opcija u Turskoj",
  description: "Šta su NucleOSS implantati zapravo, zašto su jedna od pristupačnijih opcija.",
  date: "2026-09-12",
  relatedTreatment: "zubni-implantati-istanbul-sr",
  body: [
    { h: "Domaća turska marka, ne nepoznata" },
    { p: "NucleOSS je osnovan 2001. u Izmiru, Turska — prvi domaći proizvođač zubnih implantata u zemlji." },
    { h: "Zašto je pristupačnije cenjen od uvoznih sistema" },
    { p: "Jedan zavrtanj NucleOSS implantata obično se cenjen oko 150-200€." },
    { h: "Od čega je zapravo napravljen" },
    { p: "NucleOSS implantati se proizvode od čistog titanijuma." },
    { h: "Gde se koristi izvan Turske" },
    { p: "NucleOSS je distribuiran u više od 18 zemalja." },
    { h: "Šta ovde ne znači \"ekonomično\"" },
    { p: "Niža cena ne znači da implantat nije regulisan — NucleOSS je CE sertifikovan." },
    { h: "Kome zapravo odgovara ova opcija" },
    { p: "Za pacijente koji daju prioritet trošku, ovo je legitiman srednji put." },
    { h: "Iskren kompromis koji vredi znati" },
    { p: "U poređenju sa švajcarskim sistemima, NucleOSS ima kraću istoriju publikacija." },
  ]
},
{
  slug: "nucleoss-24-godine-turske-proizvodnje",
  title: "NucleOSS implantati: Šta zapravo znači 24 godine turske proizvodnje",
  description: "Pregled istorije proizvodnje NucleOSS-a i šta dve decenije kontinuirane proizvodnje govore o pouzdanosti.",
  date: "2026-09-12",
  relatedTreatment: "zubni-implantati-istanbul-sr",
  body: [
    { h: "Dugovečnost kao proizvođača je stvaran signal" },
    { p: "Kompanija koja kontinuirano proizvodi od 2001. ima 24+ godina stvarnih kliničkih povratnih informacija." },
    { h: "Asortiman proizvoda odražava stvarno ulaganje u istraživanje i razvoj" },
    { p: "NucleOSS nudi nekoliko linija implantata dizajniranih za različite kliničke situacije." },
    { h: "Proizvedeno u Turskoj, ne samo sklopljeno" },
    { p: "NucleOSS implantati se proizvode domaće u Izmiru." },
    { h: "Šta \"konusni\" vs \"pravi\" dizajn implantata znači za vas" },
    { p: "Različiti oblici tela implantata odgovaraju različitim stanjima kosti." },
    { h: "Pitanje kompatibilnosti komponenti" },
    { p: "Širok kompatibilan ekosistem komponenti znači delove dostupne godinama kasnije." },
    { h: "Kako se ovo praktično poredi sa izborom novije marke" },
    { p: "Marka sa kraćom istorijom jednostavno nije imala toliko vremena da dokaže dugoročne rezultate." },
    { h: "Šta ovo znači za vašu odluku" },
    { p: "24-godišnja kontinuirana istorija NucleOSS-a legitiman je faktor u njenu korist." },
  ]
},
{
  slug: "porcelan-vs-cirkonijum-krunice-koja-odgovara-vasem-budzetu",
  title: "Porcelan vs cirkonijum krunice: Koja zapravo odgovara vašem budžetu i slučaju",
  description: "Direktno, praktično poređenje između metalokeramičkih i cirkonijumskih krunica.",
  date: "2026-09-12",
  relatedTreatment: null,
  body: [
    { h: "Dve legitimne opcije, ne izbor \"dobro vs loše\"" },
    { p: "I metalokeramičke i cirkonijumske krunice su ustaljene, pouzdane restauracije." },
    { h: "Razlika u ceni u praksi" },
    { p: "PFM krunice obično koštaju otprilike 80-100€, monolitni cirkonijum otprilike 120-180€." },
    { h: "Trajnost: bliže nego što većina pretpostavlja" },
    { p: "Obe vrste materijala su zaista trajne kada su pravilno postavljene." },
    { h: "Izgled: gde se pokazuje stvarna razlika" },
    { p: "Najveća prednost cirkonijuma je što uopšte ne sadrži metal." },
    { h: "Razuman način razmišljanja o mešanju oboje" },
    { p: "Mnogi pacijenti razumno biraju cirkonijum za svoje vidljive prednje zube." },
    { h: "Šta određuje koju će vaš zubar preporučiti" },
    { p: "Vaš zubar će uzeti u obzir koliko prirodne strukture zuba ostaje." },
    { h: "Pitanje koje treba postaviti pre odluke" },
    { p: "Pitajte svog zubara direktno koji materijal bi preporučio." },
  ]
},
{
  slug: "cena-izbeljivanja-zuba-jedan-tretman-vs-paket",
  title: "Цена избељивања зуба: Један третман vs пакет",
  description: "Колико обично кошта професионално избељивање зуба и зашто се често комбинује са другим третманима.",
  date: "2026-09-10",
  relatedTreatment: "izbeljivanje-zuba-istanbul",
  body: [
    { h: "Избељивање је један од приступачнијих самосталних третмана" },
    { p: "Један професионални третман избељивања, укључујући претходно чишћење, обично кошта отприлике 130-170€ у Истанбулу." },
    { h: "Зашто се често укључује заједно са другим радом" },
    { p: "Ако такође радите љуспице, избељивање преосталих природних зуба обично се ради унапред." },
    { h: "Чишћење каменца које је обично укључено" },
    { p: "Исправан третман избељивања обично прво укључује уклањање површинског каменца." },
    { h: "Зашто резултати варирају међу пацијентима" },
    { p: "Колико светлији постају ваши зуби зависи од ваше почетне нијансе." },
    { h: "Један третман vs више" },
    { p: "Већина пацијената види свој пуни резултат после једног третмана у клиници." },
    { h: "Шта потврдити пре резервације" },
    { p: "Потврдите да ли предложена цена укључује чишћење пре избељивања." },
  ]
},
{
  slug: "marke-zubnih-implantata-zasto-uticu-na-cenu",
  title: "Марке зубних имплантата: Зашто толико утичу на цену",
  description: "Зашто иста имплантациона процедура може бити наплаћена веома различито у зависности од коришћеног имплантационог система.",
  date: "2026-09-10",
  relatedTreatment: "zubni-implantati-istanbul-sr",
  body: [
    { h: "Нису сви имплантати исти производ" },
    { p: "Имплант је титанијумски завртањ, произведен од стране одређене компаније, са сопственим истраживањем." },
    { h: "Шта обично разликује премијум систем од приступачнијег" },
    { p: "Премијум имплантациони системи обично имају дужу историју објављених дугорочних клиничких студија." },
    { h: "Зашто је то важно ако у крајњем случају посетите другог стоматолога" },
    { p: "Широко признату међународну марку је обично лакше пронаћи у деловима." },
    { h: "Ово не значи да је приступачнија опција лош избор" },
    { p: "И премијум и приступачнији имплантациони системи су легитимни медицински уређаји са CE ознаком." },
    { h: "Разлика у цени у пракси" },
    { p: "Разлика је обично око 30-40% по импланту." },
    { h: "Једино питање које заиста има значаја" },
    { p: "Питајте било коју клинику тачно коју марку импланта нуде." },
  ]
},
{
  slug: "sta-se-desava-ako-nesto-krene-po-zlu-posle-povratka-kuci",
  title: "Шта се дешава ако нешто крене по злу после повратка кући?",
  description: "Директан преглед накнадне неге и гарантне заштите за пацијенте који путују у иностранство на стоматолошко лечење.",
  date: "2026-09-11",
  relatedTreatment: null,
  body: [
    { h: "Ово је брига која стоји иза скоро сваког оклевања око лечења у иностранству" },
    { p: "Клиника која је заиста опремљена за међународне пацијенте има стварне одговоре на ово." },
    { h: "Шта одређује прави гарантни документ" },
    { p: "Исправна писана гаранција прецизно одређује шта је покривено и колико дуго." },
    { h: "Даљинско праћење пре него нешто постане хитно" },
    { p: "Многи проблеми могу прво да се процене на даљину." },
    { h: "Када је заправо потребна повратна посета" },
    { p: "За стварне гарантне случајеве, легитимна клиника треба да покрије само лечење." },
    { h: "Са чим могу и не могу да помогну локални стоматолози у вашој земљи" },
    { p: "Стоматолог у вашој домовини обично може да се носи са стварним хитним случајевима." },
    { h: "Поштен одговор" },
    { p: "Реалистична већина зарастања имплантата пролази без инцидената." },
  ]
},
{
  slug: "cena-porcelanske-krunice-istanbul-budzetska-opcija",
  title: "Цена порцеланске крунице у Истанбулу: Традиционална, буџетска опција",
  description: "Колико обично кошта металокерамичка круница, како се разликује од цирконијума.",
  date: "2026-09-12",
  relatedTreatment: null,
  body: [
    { h: "Старији, добро устаљен тип крунице — не назадовање, другачија опција" },
    { p: "Металокерамичке (PFM) крунице се у стоматологији користе деценијама." },
    { h: "Колико обично кошта порцеланска круница" },
    { p: "У Истанбулу, PFM круница обично кошта отприлике 80-100€ по јединици." },
    { h: "Како је заправо изграђена" },
    { p: "PFM круница има металну подструктуру за чврстоћу." },
    { h: "Једини поштен компромис који вреди знати" },
    { p: "Након много година, метални руб код десни може постати благо видљив." },
    { h: "Где порцеланске крунице заправо имају смисла" },
    { p: "За задње кутњаке где је круница ретко видљива, ово је разуман избор." },
    { h: "Где се цирконијум обично преферира уместо тога" },
    { p: "За предње, видљиве зубе, већина се сада нагиње ка цирконијуму." },
    { h: "Шта одређује поштена понуда" },
    { p: "Исправна понуда треба јасно да наведе да ли је реч о PFM или цирконијуму." },
  ]
},
];
